LehrFEM++: lf::mesh::hybrid2d::Segment Class Reference
lf::mesh::hybrid2d::Segment Class Reference
An edge object for a 2D hybrid mesh.
#include <lf/mesh/hybrid2d/segment.h>
Public Member Functions
Segment ()=default
default constructors, needed by std::vector
Segment (size_type index, std::unique_ptr< geometry::Geometry > &&geometry, const Point *endpoint0, const Point *endpoint1)
constructor, is called from MeshFactory
unsigned Codim () const override
an edge is an entity of co-dimension 1
std::span< const Entity *const > SubEntities (unsigned rel_codim) const override
Access to all subentities selected by relative co-dimension.
std::span< const lf::mesh::Orientation > RelativeOrientations () const override
Access to relative orientations of endpoints.
size_type index () const
access to index of an entity
~Segment () override=default
Default and disabled constructors
Segment (const Segment &)=delete
Segment (Segment &&) noexcept=default
Segment & operator= (const Segment &)=delete
Segment & operator= (Segment &&) noexcept=default
Standard methods of an Entity object
See also
mesh::Entity
const geometry::Geometry * Geometry () const override
Describes the geometry of this entity.
base::RefEl RefEl () const override
Describes the reference element type of this entity.
bool operator== (const mesh::Entity &rhs) const override
Check if two entities are the same.
Public Member Functions inherited from lf::mesh::Entity
bool operator!= (const Entity &rhs) const
Check if two entities are different.
virtual ~Entity ()=default
Virtual Destructor.
Private Types
using size_type = mesh::Mesh::size_type
Private Attributes
size_type index_ = -1
std::unique_ptr< geometry::Geometry > geometry_
std::array< const Point *, 2 > nodes_ {}
Entity * this_ = nullptr
Static Private Attributes
static constexpr std::array< lf::mesh::Orientation, 2 > endpoint_ori_
Additional Inherited Members
Protected Member Functions inherited from lf::mesh::Entity
Entity ()=default
Entity (const Entity &)=default
Entity (Entity &&)=default
Entity & operator= (const Entity &)=default
Entity & operator= (Entity &&)=default
Related Symbols inherited from lf::mesh::Entity
void PrintInfo (std::ostream &stream, const lf::mesh::Entity &e, int output_ctrl=0)
Prints info about an entity.
Detailed Description
An edge object for a 2D hybrid mesh.
An topological edge object is define through two distinct references to node objects of the mesh. Their ordering reflects the intrinsic orientation of the mesh
Note
Every Segment object owns a smart pointer to an associated geometry object.
Definition at line 29 of file segment.h.
Member Typedef Documentation
size_type
using lf::mesh::hybrid2d::Segment::size_type = mesh::Mesh::size_type private
Definition at line 30 of file segment.h.
Constructor & Destructor Documentation
Segment() [1/4]
lf::mesh::hybrid2d::Segment::Segment () default
default constructors, needed by std::vector
Referenced by operator=(), operator=(), Segment(), Segment(), and Segment().
Segment() [2/4]
lf::mesh::hybrid2d::Segment::Segment (const Segment &) delete
References Segment().
Segment() [3/4]
lf::mesh::hybrid2d::Segment::Segment (Segment &&) default noexcept
References Segment().
Segment() [4/4]
lf::mesh::hybrid2d::Segment::Segment (size_type index, std::unique_ptr< geometry::Geometry > && geometry, const Point * endpoint0, const Point * endpoint1) inline explicit
constructor, is called from MeshFactory
Parameters
index index of the entity to be created; will usually be retrieved via the Index() method of Mesh
geometry pointer to a geometry object providing the shape of the edge
endpoint0 pointer to the first node
endpoint1 pointer to the second node
Note
Note that you need to create a suitable geometry object for the entity before you can initialize the entity object itseld.
Definition at line 56 of file segment.h.
References Geometry(), geometry_, index(), index_, nodes_, and Segment().
~Segment()
lf::mesh::hybrid2d::Segment::~Segment () override default
Member Function Documentation
Codim()
unsigned lf::mesh::hybrid2d::Segment::Codim () const inline nodiscard override virtual
an edge is an entity of co-dimension 1
Implements lf::mesh::Entity.
Definition at line 74 of file segment.h.
Geometry()
const geometry::Geometry * lf::mesh::hybrid2d::Segment::Geometry () const inline nodiscard override virtual
Describes the geometry of this entity.
Returns
A pointer to a Geometry object that will remain valid for as long as the Mesh remains valid.
Why does this member function return a pointer instead of a reference? One reason is that entities without a geometric shape are conceivable as building block of a "mesh graph", where only topological information matters. Another reason is that during the construction of a mesh, it turns out to be convenient to build entities "without geometry" first and then endow them with geometric information. A nullptr is a good way to indicate missing geometric information.
Implements lf::mesh::Entity.
Definition at line 102 of file segment.h.
References geometry_.
Referenced by Segment().
index()
size_type lf::mesh::hybrid2d::Segment::index () const inline nodiscard
access to index of an entity
Definition at line 96 of file segment.h.
References index_.
Referenced by Segment().
operator=() [1/2]
Segment & lf::mesh::hybrid2d::Segment::operator= (const Segment &) delete
References Segment().
operator=() [2/2]
Segment & lf::mesh::hybrid2d::Segment::operator= (Segment &&) default noexcept
References Segment().
operator==()
bool lf::mesh::hybrid2d::Segment::operator== (const mesh::Entity & rhs) const inline nodiscard override virtual
Check if two entities are the same.
Parameters
rhs Check if this entity is the same as the rhs entity.
Note
The behavior of this method is undefined if the rhs entity belongs to a different Mesh.
Implements lf::mesh::Entity.
Definition at line 108 of file segment.h.
RefEl()
base::RefEl lf::mesh::hybrid2d::Segment::RefEl () const inline nodiscard override virtual
Describes the reference element type of this entity.
Returns
An object of type lf::base::RefEl.
Implements lf::mesh::Entity.
Definition at line 105 of file segment.h.
References lf::base::RefEl::kSegment().
RelativeOrientations()
std::span< const lf::mesh::Orientation > lf::mesh::hybrid2d::Segment::RelativeOrientations () const inline nodiscard override virtual
Access to relative orientations of endpoints.
This method just returns {+,-}, because points always have the intrinsic orientation + and the orientation of an edge is defined through the ordering of its vertices.
Implements lf::mesh::Entity.
Definition at line 90 of file segment.h.
References endpoint_ori_.
SubEntities()
std::span< const Entity *const > lf::mesh::hybrid2d::Segment::SubEntities (unsigned rel_codim) const nodiscard override virtual
Access to all subentities selected by relative co-dimension.
Parameters
rel_codim if 1 select endnodes, if 0 select edge itself
Returns
for rel_codim == 1: return 2-range covering endnodes
for rel_codim == 0: return the Segment entity itself
Implements lf::mesh::Entity.
Definition at line 14 of file segment.cc.
References lf::mesh::Entity::Entity(), nodes_, and this_.
Member Data Documentation
endpoint_ori_
std::array<lf::mesh::Orientation, 2> lf::mesh::hybrid2d::Segment::endpoint_ori_ static constexpr private
Initial value:
{
      lf::mesh::Orientation::negative,
      lf::mesh::Orientation::positive}
Definition at line 120 of file segment.h.
Referenced by RelativeOrientations().
geometry_
std::unique_ptr<geometry::Geometry> lf::mesh::hybrid2d::Segment::geometry_ private
Definition at line 117 of file segment.h.
Referenced by Geometry(), and Segment().
index_
size_type lf::mesh::hybrid2d::Segment::index_ = -1 private
Definition at line 116 of file segment.h.
Referenced by index(), and Segment().
nodes_
std::array<const Point*, 2> lf::mesh::hybrid2d::Segment::nodes_ {} private
Definition at line 118 of file segment.h.
Referenced by Segment(), and SubEntities().
this_
Entity* lf::mesh::hybrid2d::Segment::this_ = nullptr private
Definition at line 119 of file segment.h.
Referenced by SubEntities().
The documentation for this class was generated from the following files:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/mesh/hybrid2d/segment.h
/home/runner/work/lehrfempp/lehrfempp/lib/lf/mesh/hybrid2d/segment.cc