LehrFEM++: lf::uscalfe::FeLagrangeO2Tria< SCALAR > Class Template Reference
lf::uscalfe::FeLagrangeO2Tria< SCALAR > Class Template Reference final
Quadratic Lagrangian finite element on a triangular reference element.
#include <lf/uscalfe/uscalfe.h>
Public Member Functions
FeLagrangeO2Tria (const FeLagrangeO2Tria &)=default
FeLagrangeO2Tria (FeLagrangeO2Tria &&) noexcept=default
FeLagrangeO2Tria & operator= (const FeLagrangeO2Tria &)=default
FeLagrangeO2Tria & operator= (FeLagrangeO2Tria &&) noexcept=default
FeLagrangeO2Tria ()=default
~FeLagrangeO2Tria () override=default
base::RefEl RefEl () const override
Tells the type of reference cell underlying the parametric finite element.
unsigned Degree () const override
Quadratic Lagrangian finite elements rely on polynomials of degree 2.
size_type NumRefShapeFunctions () const override
Six local shape functions are associated with a triangular cell in the case of quadratic Lagrangian finite elements.
size_type NumRefShapeFunctions (dim_t codim) const override
One shape function attached to each node and one to each edge of the triangle. There are no interior shape functions.
size_type NumRefShapeFunctions (dim_t codim, sub_idx_t) const override
One shape function attached to each node and one to each edge of the triangle. There are no interior shape functions.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > EvalReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Point evaluation of reference shape functions.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > GradientsReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Point evaluations of gradients of reference shape functions.
Eigen::MatrixXd EvaluationNodes () const override
Evaluation nodes are the three vertices of the triangle and the three midpoints of its edges.
size_type NumEvaluationNodes () const override
Six evaluation nodes, the same number as local shape functions.
Public Member Functions inherited from lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >
virtual ~ScalarReferenceFiniteElement ()=default
dim_t Dimension () const
Returns the spatial dimension of the reference cell.
virtual Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > NodalValuesToDofs (const Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > &nodvals) const
Computes the linear combination of reference shape functions matching function values at evaluation nodes.
Additional Inherited Members
Public Types inherited from lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >
using Scalar = SCALAR
The underlying scalar type.
Protected Member Functions inherited from lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >
ScalarReferenceFiniteElement ()=default
ScalarReferenceFiniteElement (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement (ScalarReferenceFiniteElement &&) noexcept=default
ScalarReferenceFiniteElement & operator= (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement & operator= (ScalarReferenceFiniteElement &&) noexcept=default
Related Functions inherited from lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >
template<class SCALAR >
void PrintInfo (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &srfe, unsigned int ctrl=0)
Print information about a ScalarReferenceFiniteElement to the given stream.
template<typename SCALAR >
std::ostream & operator<< (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &fe_desc)
Stream output operator: just calls the ScalarReferenceFiniteElement::print() method.
Detailed Description
template<typename SCALAR>
class lf::uscalfe::FeLagrangeO2Tria< SCALAR >
Quadratic Lagrangian finite element on a triangular reference element.
This is a specialization of ScalarReferenceFiniteElement.
The reference shape functions are combinations of the barycentric coordinate functions on the reference triangle, see Example 2.6.1.2.
The first three shape functions are associated to the vertices, the other three shape functions to the edges of the triangle. There are no interior shape functions, see Equation 2.6.1.6:
\begin{eqnarray} \hat{b}^1({\bf x}) &=& 2(1-x_1-x_2)(\frac12 -x_1 -x_2)\;,\\ \hat{b}^2({\bf x}) &=& 2x_1(x_1-\frac12)\;,\\ \hat{b}^3({\bf x}) &=& 2x_2(x_2-\frac12)\;,\\ \hat{b}^4({\bf x}) &=& 4(1-x_1-x_2)x_1\;,\\ \hat{b}^5({\bf x}) &=& 4x_1x_2\;,\\ \hat{b}^6({\bf x}) &=& 4(1-x_1-x_2)x_2\;. \end{eqnarray}
The numbering convention for the local shape functions is explained in Example 2.7.4.12.
See also
ScalarReferenceFiniteElement
Definition at line 751 of file lagr_fe.h.
Constructor & Destructor Documentation
FeLagrangeO2Tria() [1/3]
template<typename SCALAR > lf::uscalfe::FeLagrangeO2Tria< SCALAR >::FeLagrangeO2Tria (const FeLagrangeO2Tria< SCALAR > &) default
FeLagrangeO2Tria() [2/3]
template<typename SCALAR > lf::uscalfe::FeLagrangeO2Tria< SCALAR >::FeLagrangeO2Tria (FeLagrangeO2Tria< SCALAR > &&) default noexcept
FeLagrangeO2Tria() [3/3]
template<typename SCALAR > lf::uscalfe::FeLagrangeO2Tria< SCALAR >::FeLagrangeO2Tria () default
~FeLagrangeO2Tria()
template<typename SCALAR > lf::uscalfe::FeLagrangeO2Tria< SCALAR >::~FeLagrangeO2Tria () override default
Member Function Documentation
Degree()
template<typename SCALAR > unsigned lf::uscalfe::FeLagrangeO2Tria< SCALAR >::Degree () const inline override virtual
Quadratic Lagrangian finite elements rely on polynomials of degree 2.
Implements lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 769 of file lagr_fe.h.
EvalReferenceShapeFunctions()
template<typename SCALAR > Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic> lf::uscalfe::FeLagrangeO2Tria< SCALAR >::EvalReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline override virtual
Point evaluation of reference shape functions.
The formulas of the reference shape functions are given in the class documentation of FeLagrangeO2Tria.
See also
ScalarReferenceFiniteElement::EvalReferenceShapeFunctions()
Implements lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 809 of file lagr_fe.h.
EvaluationNodes()
template<typename SCALAR > Eigen::MatrixXd lf::uscalfe::FeLagrangeO2Tria< SCALAR >::EvaluationNodes () const inline override virtual
Evaluation nodes are the three vertices of the triangle and the three midpoints of its edges.
The reference shape functions as implemented by this class are a cardinal basis of the space of quadratic two-variate polynomials with respect to these evaluation nodes.
The numbering of evluation nodes is fixed by the numbering of the local shape functions.
See also
ScalarReferenceFiniteElement::EvaluationNodes()
Implements lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 879 of file lagr_fe.h.
GradientsReferenceShapeFunctions()
template<typename SCALAR > Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic> lf::uscalfe::FeLagrangeO2Tria< SCALAR >::GradientsReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline override virtual
Point evaluations of gradients of reference shape functions.
Refer to Example 2.7.5.7 for related explanations
See also
ScalarReferenceFiniteElement::GradientsReferenceShapeFunctions()
Implements lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 836 of file lagr_fe.h.
NumEvaluationNodes()
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO2Tria< SCALAR >::NumEvaluationNodes () const inline override virtual
Six evaluation nodes, the same number as local shape functions.
See also
ScalarReferenceFiniteElement::NumEvaluationNodes()
Implements lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 893 of file lagr_fe.h.
References lf::uscalfe::FeLagrangeO2Tria< SCALAR >::NumRefShapeFunctions().
NumRefShapeFunctions() [1/3]
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO2Tria< SCALAR >::NumRefShapeFunctions () const inline override virtual
Six local shape functions are associated with a triangular cell in the case of quadratic Lagrangian finite elements.
See also
ScalarReferenceFiniteElement::NumRefShapeFunctions()
Reimplemented from lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 776 of file lagr_fe.h.
Referenced by lf::uscalfe::FeLagrangeO2Tria< SCALAR >::NumEvaluationNodes().
NumRefShapeFunctions() [2/3]
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO2Tria< SCALAR >::NumRefShapeFunctions (dim_t codim) const inline override virtual
One shape function attached to each node and one to each edge of the triangle. There are no interior shape functions.
See also
ScalarReferenceFiniteElement::NumRefShapeFunctions(dim_t)
Reimplemented from lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 784 of file lagr_fe.h.
NumRefShapeFunctions() [3/3]
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO2Tria< SCALAR >::NumRefShapeFunctions (dim_t codim, sub_idx_t) const inline override virtual
One shape function attached to each node and one to each edge of the triangle. There are no interior shape functions.
See also
ScalarReferenceFiniteElement::NumRefShapeFunctions(dim_t,sub_idx_t)
Implements lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 795 of file lagr_fe.h.
operator=() [1/2]
template<typename SCALAR > FeLagrangeO2Tria& lf::uscalfe::FeLagrangeO2Tria< SCALAR >::operator= (const FeLagrangeO2Tria< SCALAR > &) default
operator=() [2/2]
template<typename SCALAR > FeLagrangeO2Tria& lf::uscalfe::FeLagrangeO2Tria< SCALAR >::operator= (FeLagrangeO2Tria< SCALAR > &&) default noexcept
RefEl()
template<typename SCALAR > base::RefEl lf::uscalfe::FeLagrangeO2Tria< SCALAR >::RefEl () const inline override virtual
Tells the type of reference cell underlying the parametric finite element.
Implements lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 762 of file lagr_fe.h.
References lf::base::RefEl::kTria().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/uscalfe/lagr_fe.h