LehrFEM++: lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF > Class Template Reference
lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF > Class Template Reference
Concepts » MeshFunction
A MeshFunction representing an element from a ScalarUniformFESpace (e.g. solution of BVP)
#include <lf/uscalfe/uscalfe.h>
Public Types
using Scalar = decltype(SCALAR_FE(0) *SCALAR_COEFF(0))
Public Member Functions
MeshFunctionFE (std::shared_ptr< const UniformScalarFESpace< SCALAR_FE >> fe_space, const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > &coeff_vector)
Create a new MeshFunctionFE from a ScalarUniformFESpace and a coefficient vector.
std::vector< Scalar > operator() (const lf::mesh::Entity &e, const Eigen::MatrixXd &local) const
std::shared_ptr< const mesh::Mesh > getMesh () const
Convenience method to retrieve the underlying mesh.
std::shared_ptr< const UniformScalarFESpace< SCALAR_FE > > getFESpace () const
Convenience method to retrieve the finite element space in which the mesh function lives.
Private Attributes
std::shared_ptr< const UniformScalarFESpace< SCALAR_FE > > fe_space_
const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > & dof_vector_
std::array< std::shared_ptr< const ScalarReferenceFiniteElement< SCALAR_FE > >, 5 > fe_
Detailed Description
template<class SCALAR_FE, class SCALAR_COEFF>
class lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >
A MeshFunction representing an element from a ScalarUniformFESpace (e.g. solution of BVP)
Template Parameters
SCALAR_FE The scalar type of the finite element basis functions.
SCALAR_COEFF The scalar type of the coefficient vector
The MeshFunctionFE takes essentially two parameters:
A ScalarUniformFESpace which defines the space of all approximation functions.
A Coefficient Vector which defines what element should be picked from the FeSpace. This is a simple Eigen::Vector which defines the coefficient in front of every basis function of the FeSpace (same ordering).
Note
A MeshFunctionFE can be evaluated on entities of all codimensions. The mesh function will simply use the ScalarReferenceFiniteElement from the feSpace.
Use case
double computeL2ErrorNorm(
    std::shared_ptr<const lf::uscalfe::UniformScalarFESpace<double>> fe_space_p,
    const Eigen::VectorXd& mu) {
  // Reference to underlying mesh
  const lf::mesh::Mesh& mesh{*(fe_space_p->Mesh())};
  // Lambda function providing the "exact solution"
  auto u = [](Eigen::Vector2d x) -> double {
    return std::log(x[0] * x[0] + x[1] + 1.0);
  };
  // Has to be wrapped into a mesh function for error computation
  lf::mesh::utils::MeshFunctionGlobal mf_u{u};
  // create mesh functions representing solution
  auto mf_sol = lf::uscalfe::MeshFunctionFE<double, double>(fe_space_p, mu);
  // compute errors with 10-th order quadrature rules
  double L2err_2 =  // NOLINT
      std::sqrt(IntegrateMeshFunction(mesh, squaredNorm(mf_sol - mf_u), 2));
  return std::sqrt(L2err_2);
}
Definition at line 44 of file mesh_function_fe.h.
Member Typedef Documentation
Scalar
template<class SCALAR_FE , class SCALAR_COEFF > using lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::Scalar = decltype(SCALAR_FE(0) * SCALAR_COEFF(0))
Definition at line 46 of file mesh_function_fe.h.
Constructor & Destructor Documentation
MeshFunctionFE()
template<class SCALAR_FE , class SCALAR_COEFF > lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::MeshFunctionFE (std::shared_ptr< const UniformScalarFESpace< SCALAR_FE >> fe_space, const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > & coeff_vector) inline
Create a new MeshFunctionFE from a ScalarUniformFESpace and a coefficient vector.
Parameters
fe_space the approximation space in which the function lies.
coeff_vector Defines the coefficients in front of the basis functions of fe_space
Definition at line 55 of file mesh_function_fe.h.
References lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_, lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_space_, lf::base::RefEl::kPoint(), lf::base::RefEl::kQuad(), lf::base::RefEl::kSegment(), and lf::base::RefEl::kTria().
Member Function Documentation
getFESpace()
template<class SCALAR_FE , class SCALAR_COEFF > std::shared_ptr<const UniformScalarFESpace<SCALAR_FE> > lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::getFESpace () const inline
Convenience method to retrieve the finite element space in which the mesh function lives.
Returns
shared_ptr to UniformScalarFESpace in which the mesh function lives.
Definition at line 99 of file mesh_function_fe.h.
References lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_space_.
getMesh()
template<class SCALAR_FE , class SCALAR_COEFF > std::shared_ptr<const mesh::Mesh> lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::getMesh () const inline
Convenience method to retrieve the underlying mesh.
Returns
The mesh on which this mesh function is defined.
Definition at line 88 of file mesh_function_fe.h.
References lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_space_.
operator()()
template<class SCALAR_FE , class SCALAR_COEFF > std::vector<Scalar> lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::operator() (const lf::mesh::Entity & e, const Eigen::MatrixXd & local) const inline
Evaluate the mesh function on a MeshEntity
Definition at line 66 of file mesh_function_fe.h.
References lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::dof_vector_, lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_, lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_space_, lf::base::RefEl::Id(), and lf::mesh::Entity::RefEl().
Member Data Documentation
dof_vector_
template<class SCALAR_FE , class SCALAR_COEFF > const Eigen::Matrix<SCALAR_COEFF, Eigen::Dynamic, 1>& lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::dof_vector_ private
Definition at line 105 of file mesh_function_fe.h.
Referenced by lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::operator()().
fe_
template<class SCALAR_FE , class SCALAR_COEFF > std::array<std::shared_ptr<const ScalarReferenceFiniteElement<SCALAR_FE> >, 5> lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_ private
Definition at line 107 of file mesh_function_fe.h.
Referenced by lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::MeshFunctionFE(), and lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::operator()().
fe_space_
template<class SCALAR_FE , class SCALAR_COEFF > std::shared_ptr<const UniformScalarFESpace<SCALAR_FE> > lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::fe_space_ private
Definition at line 104 of file mesh_function_fe.h.
Referenced by lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::getFESpace(), lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::getMesh(), lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::MeshFunctionFE(), and lf::uscalfe::MeshFunctionFE< SCALAR_FE, SCALAR_COEFF >::operator()().
The documentation for this class was generated from the following file:
/home/travis/build/craffael/lehrfempp/lib/lf/uscalfe/mesh_function_fe.h