LehrFEM++: lf::mesh::utils::MeshFunctionGlobal< F > Class Template Reference
lf::mesh::utils::MeshFunctionGlobal< F > Class Template Reference
MeshFunction
MeshFunction wrapper for a simple function of physical coordinates.
#include <lf/uscalfe/uscalfe.h>
Public Member Functions
MeshFunctionGlobal (const MeshFunctionGlobal &)=default
MeshFunctionGlobal (MeshFunctionGlobal &&) noexcept=default
MeshFunctionGlobal & operator= (const MeshFunctionGlobal &)=delete
MeshFunctionGlobal & operator= (MeshFunctionGlobal &&)=delete
MeshFunctionGlobal (F f)
std::vector< F_return_type > operator() (const mesh::Entity &e, const Eigen::MatrixXd &local) const
MeshFunction compliant evaluation operator.
virtual ~MeshFunctionGlobal ()=default
Private Types
using F_return_type
Private Attributes
F f_
Detailed Description
template<class F>
class lf::mesh::utils::MeshFunctionGlobal< F >
MeshFunction wrapper for a simple function of physical coordinates.
Template Parameters
F a functor type, offering an evaluation operator that acccepts a single coordinate vector.
MeshFunctionGlobal essentially wraps a function object which represents a function defined on the mesh that depends only on the global coordinates. An example is e.g. the function \(\vec{x} \mapsto \norm{x}^2 \).
Requirements for F
F is a function object that should overload the call operator as follows:
auto operator()(const Eigen::Vector2d& x) const
which should return the value of the mesh function at the global coordinates x. The return type of the call operator can in principle be anything, but usually it is one of:
double for a scalar valued mesh function
std::complex<double> for complex valued mesh function
Eigen::Vector2d for a tensor valued mesh function.
For instance, a MeshFunctionGlobal object may be instantiated with a lambda function.
Note
For DimGlobal==3, the call operator should of course accept a Eigen::Vector3d.
Use case
  // Define a tensor field through a lambda function
  auto alpha = [](Eigen::Vector2d x) -> Eigen::Matrix<double, 2, 2> {
    return (Eigen::Matrix<double, 2, 2>() << (3.0 + x[1]), x[0], x[0],
            (2.0 + x[0]))
        .finished();
  };
  // Wrap the tensor field into a MeshFunction
  lf::mesh::utils::MeshFunctionGlobal mf_alpha{alpha};
  // evaluate the tensor field at the nodes of the mesh
  const Eigen::Matrix<double, 0, 1> dummy;
  for (const lf::mesh::Entity* node : mesh.Entities(2)) {
    const std::vector<Eigen::Matrix<double, 2, 2>> a{mf_alpha(*node, dummy)};
    std::cout << a[0] << std::endl;
  }
Definition at line 55 of file mesh_function_global.h.
Member Typedef Documentation
F_return_type
template<class F> using lf::mesh::utils::MeshFunctionGlobal< F >::F_return_type private
Initial value:
      decltype(std::declval<F>()(std::declval<Eigen::Vector2d>()))
Definition at line 56 of file mesh_function_global.h.
Constructor & Destructor Documentation
MeshFunctionGlobal() [1/3]
template<class F> lf::mesh::utils::MeshFunctionGlobal< F >::MeshFunctionGlobal (const MeshFunctionGlobal< F > &) default
References MeshFunctionGlobal().
Referenced by MeshFunctionGlobal(), MeshFunctionGlobal(), MeshFunctionGlobal(), operator=(), and operator=().
MeshFunctionGlobal() [2/3]
template<class F> lf::mesh::utils::MeshFunctionGlobal< F >::MeshFunctionGlobal (MeshFunctionGlobal< F > &&) default noexcept
References MeshFunctionGlobal().
MeshFunctionGlobal() [3/3]
template<class F> lf::mesh::utils::MeshFunctionGlobal< F >::MeshFunctionGlobal (F f) inline explicit
Definition at line 72 of file mesh_function_global.h.
References f_, and MeshFunctionGlobal().
~MeshFunctionGlobal()
template<class F> virtual lf::mesh::utils::MeshFunctionGlobal< F >::~MeshFunctionGlobal () virtual default
Member Function Documentation
operator()()
template<class F> std::vector< F_return_type > lf::mesh::utils::MeshFunctionGlobal< F >::operator() (const mesh::Entity & e, const Eigen::MatrixXd & local) const inline
MeshFunction compliant evaluation operator.
Definition at line 77 of file mesh_function_global.h.
References lf::base::RefEl::Dimension(), f_, lf::mesh::Entity::Geometry(), lf::geometry::Geometry::Global(), and lf::mesh::Entity::RefEl().
operator=() [1/2]
template<class F> MeshFunctionGlobal & lf::mesh::utils::MeshFunctionGlobal< F >::operator= (const MeshFunctionGlobal< F > &) delete
References MeshFunctionGlobal().
operator=() [2/2]
template<class F> MeshFunctionGlobal & lf::mesh::utils::MeshFunctionGlobal< F >::operator= (MeshFunctionGlobal< F > &&) delete
References MeshFunctionGlobal().
Member Data Documentation
f_
template<class F> F lf::mesh::utils::MeshFunctionGlobal< F >::f_ private
Definition at line 93 of file mesh_function_global.h.
Referenced by MeshFunctionGlobal(), and operator()().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/mesh/utils/mesh_function_global.h