LehrFEM++: lf::refinement::EntityCenterPositionSelector< POSPRED > Class Template Reference
lf::refinement::EntityCenterPositionSelector< POSPRED > Class Template Reference
Utility class: selection of entities according to the position of their midpoint.
#include <lf/refinement/mesh_hierarchy.h>
Public Member Functions
EntityCenterPositionSelector (const EntityCenterPositionSelector &)=default
EntityCenterPositionSelector (EntityCenterPositionSelector &&) noexcept=default
EntityCenterPositionSelector & operator= (const EntityCenterPositionSelector &)=default
EntityCenterPositionSelector & operator= (EntityCenterPositionSelector &&) noexcept=default
EntityCenterPositionSelector (POSPRED pos_pred)
Preparing reference coordinates of "centers".
bool operator() (const lf::mesh::Entity &ent) const
Operator testing location of "center".
virtual ~EntityCenterPositionSelector ()=default
Private Attributes
POSPRED pos_pred_
Static Private Attributes
static const Eigen::MatrixXd kpoint_center_
static const Eigen::MatrixXd kedge_center_
static const Eigen::MatrixXd ktria_center_
static const Eigen::MatrixXd kquad_center_
Detailed Description
template<typename POSPRED>
class lf::refinement::EntityCenterPositionSelector< POSPRED >
Utility class: selection of entities according to the position of their midpoint.
Template Parameters
POSPRED predicate depending on physical point location
Type requirements
POSPRED must have an evaluation operator that accepts an Eigen matrix/vector object whose columns are viewed as coordinate vectors. It should return a boolean value.
Definition at line 497 of file mesh_hierarchy.h.
Constructor & Destructor Documentation
EntityCenterPositionSelector() [1/3]
template<typename POSPRED > lf::refinement::EntityCenterPositionSelector< POSPRED >::EntityCenterPositionSelector (const EntityCenterPositionSelector< POSPRED > &) default
EntityCenterPositionSelector() [2/3]
template<typename POSPRED > lf::refinement::EntityCenterPositionSelector< POSPRED >::EntityCenterPositionSelector (EntityCenterPositionSelector< POSPRED > &&) default noexcept
EntityCenterPositionSelector() [3/3]
template<typename POSPRED > lf::refinement::EntityCenterPositionSelector< POSPRED >::EntityCenterPositionSelector (POSPRED pos_pred) inline explicit
Preparing reference coordinates of "centers".
Parameters
pos_pred object for true/false classification of physicals points
Definition at line 511 of file mesh_hierarchy.h.
~EntityCenterPositionSelector()
template<typename POSPRED > virtual lf::refinement::EntityCenterPositionSelector< POSPRED >::~EntityCenterPositionSelector () virtual default
Member Function Documentation
operator()()
template<typename POSPRED > bool lf::refinement::EntityCenterPositionSelector< POSPRED >::operator() (const lf::mesh::Entity & ent) const inline
Operator testing location of "center".
Parameters
ent reference to a mesh entity
Returns
value of the predicate when given the center of the entity
Definition at line 517 of file mesh_hierarchy.h.
References lf::mesh::Entity::Geometry(), lf::geometry::Geometry::Global(), lf::refinement::EntityCenterPositionSelector< POSPRED >::kedge_center_, lf::base::RefEl::kPoint(), lf::refinement::EntityCenterPositionSelector< POSPRED >::kpoint_center_, lf::base::RefEl::kQuad(), lf::refinement::EntityCenterPositionSelector< POSPRED >::kquad_center_, lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), lf::refinement::EntityCenterPositionSelector< POSPRED >::ktria_center_, lf::refinement::EntityCenterPositionSelector< POSPRED >::pos_pred_, and lf::mesh::Entity::RefEl().
operator=() [1/2]
template<typename POSPRED > EntityCenterPositionSelector& lf::refinement::EntityCenterPositionSelector< POSPRED >::operator= (const EntityCenterPositionSelector< POSPRED > &) default
operator=() [2/2]
template<typename POSPRED > EntityCenterPositionSelector& lf::refinement::EntityCenterPositionSelector< POSPRED >::operator= (EntityCenterPositionSelector< POSPRED > &&) default noexcept
Member Data Documentation
kedge_center_
template<typename POSPRED > const Eigen::MatrixXd lf::refinement::EntityCenterPositionSelector< POSPRED >::kedge_center_ static private
Initial value:
=
    (Eigen::MatrixXd(1, 1) << 0.5).finished()
Definition at line 554 of file mesh_hierarchy.h.
Referenced by lf::refinement::EntityCenterPositionSelector< POSPRED >::operator()().
kpoint_center_
template<typename POSPRED > const Eigen::MatrixXd lf::refinement::EntityCenterPositionSelector< POSPRED >::kpoint_center_ static private
Initial value:
=
    Eigen::MatrixXd::Zero(0, 1)
Definition at line 553 of file mesh_hierarchy.h.
Referenced by lf::refinement::EntityCenterPositionSelector< POSPRED >::operator()().
kquad_center_
template<typename POSPRED > const Eigen::MatrixXd lf::refinement::EntityCenterPositionSelector< POSPRED >::kquad_center_ static private
Initial value:
=
    (Eigen::MatrixXd(2, 1) << 0.5, 0.5).finished()
Definition at line 556 of file mesh_hierarchy.h.
Referenced by lf::refinement::EntityCenterPositionSelector< POSPRED >::operator()().
ktria_center_
template<typename POSPRED > const Eigen::MatrixXd lf::refinement::EntityCenterPositionSelector< POSPRED >::ktria_center_ static private
Initial value:
=
    (Eigen::MatrixXd(2, 1) << 0.33, 0.33).finished()
Definition at line 555 of file mesh_hierarchy.h.
Referenced by lf::refinement::EntityCenterPositionSelector< POSPRED >::operator()().
pos_pred_
template<typename POSPRED > POSPRED lf::refinement::EntityCenterPositionSelector< POSPRED >::pos_pred_ private
object for true/false classification of of physicals points
Definition at line 551 of file mesh_hierarchy.h.
Referenced by lf::refinement::EntityCenterPositionSelector< POSPRED >::operator()().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/refinement/mesh_hierarchy.h