LehrFEM++: lf::uscalfe::FeLagrangeO3Segment< SCALAR > Class Template Reference
lf::uscalfe::FeLagrangeO3Segment< SCALAR > Class Template Reference final
Cubic Lagrangian finite element on a line segment.
#include <lf/uscalfe/uscalfe.h>
Public Member Functions
FeLagrangeO3Segment (const FeLagrangeO3Segment &)=default
FeLagrangeO3Segment (FeLagrangeO3Segment &&) noexcept=default
FeLagrangeO3Segment & operator= (const FeLagrangeO3Segment &)=default
FeLagrangeO3Segment & operator= (FeLagrangeO3Segment &&) noexcept=default
FeLagrangeO3Segment ()=default
~FeLagrangeO3Segment () override=default
base::RefEl RefEl () const override
Tells the type of reference cell underlying the parametric finite element.
unsigned Degree () const override
Request the maximal polynomial degree of the basis functions in this finite element.
size_type NumRefShapeFunctions () const override
Total number of reference shape functions associated with the reference cell.
size_type NumRefShapeFunctions (dim_t codim) const override
One shape function attached to each node and two interior shape functions.
size_type NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const override
One shape function attached to each node and two interior shape functions.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > EvalReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Evaluation of all reference shape functions in a number of points.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > GradientsReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Computation of the gradients of all reference shape functions in a number of points.
Eigen::MatrixXd EvaluationNodes () const override
Returns reference coordinates of "evaluation nodes" for evaluation of parametric degrees of freedom, nodal interpolation in the simplest case.
size_type NumEvaluationNodes () const override
Four evaluation nodes.
Public Member Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
virtual ~ScalarReferenceFiniteElement ()=default
dim_t Dimension () const
Returns the spatial dimension of the reference cell.
virtual Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > NodalValuesToDofs (const Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > &nodvals) const
Computes the linear combination of reference shape functions matching function values at evaluation nodes.
Additional Inherited Members
Public Types inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
using Scalar = SCALAR
The underlying scalar type.
Protected Member Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
ScalarReferenceFiniteElement ()=default
ScalarReferenceFiniteElement (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement (ScalarReferenceFiniteElement &&) noexcept=default
ScalarReferenceFiniteElement & operator= (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement & operator= (ScalarReferenceFiniteElement &&) noexcept=default
Related Symbols inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
template<class SCALAR>
void PrintInfo (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &srfe, unsigned int ctrl=0)
Print information about a ScalarReferenceFiniteElement to the given stream.
template<typename SCALAR>
std::ostream & operator<< (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &fe_desc)
Stream output operator: just calls the ScalarReferenceFiniteElement::print() method.
Detailed Description
template<typename SCALAR>
class lf::uscalfe::FeLagrangeO3Segment< SCALAR >
Cubic Lagrangian finite element on a line segment.
This is a specialization of ScalarReferenceFiniteElement. Refer to its documentation.
The first two shape functins are associated with vertices of the segment. The last two are interior shape functions.
See also
ScalarReferenceFiniteElement
Definition at line 1155 of file lagr_fe.h.
Constructor & Destructor Documentation
FeLagrangeO3Segment() [1/3]
template<typename SCALAR> lf::uscalfe::FeLagrangeO3Segment< SCALAR >::FeLagrangeO3Segment (const FeLagrangeO3Segment< SCALAR > &) default
References FeLagrangeO3Segment().
Referenced by FeLagrangeO3Segment(), FeLagrangeO3Segment(), FeLagrangeO3Segment(), operator=(), operator=(), and ~FeLagrangeO3Segment().
FeLagrangeO3Segment() [2/3]
template<typename SCALAR> lf::uscalfe::FeLagrangeO3Segment< SCALAR >::FeLagrangeO3Segment (FeLagrangeO3Segment< SCALAR > &&) default noexcept
References FeLagrangeO3Segment().
FeLagrangeO3Segment() [3/3]
template<typename SCALAR> lf::uscalfe::FeLagrangeO3Segment< SCALAR >::FeLagrangeO3Segment () default
References FeLagrangeO3Segment().
~FeLagrangeO3Segment()
template<typename SCALAR> lf::uscalfe::FeLagrangeO3Segment< SCALAR >::~FeLagrangeO3Segment () override default
References FeLagrangeO3Segment().
Member Function Documentation
Degree()
template<typename SCALAR> unsigned lf::uscalfe::FeLagrangeO3Segment< SCALAR >::Degree () const inline nodiscard override virtual
Request the maximal polynomial degree of the basis functions in this finite element.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1169 of file lagr_fe.h.
EvalReferenceShapeFunctions()
template<typename SCALAR> Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > lf::uscalfe::FeLagrangeO3Segment< SCALAR >::EvalReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline nodiscard override virtual
Evaluation of all reference shape functions in a number of points.
Parameters
refcoords coordinates of N points in the reference cell passed as columns of a matrix of size dim x N, where dim is the dimension of the reference element, that is =0 for points, =1 for edges, =2 for triangles and quadrilaterals
Returns
An Eigen Matrix of size NumRefShapeFunctions() x refcoords.cols() which contains the shape functions evaluated at every quadrature point.
Concerning the numbering of local shape functions, please consult the documentation of lf::assemble::DofHandler or the documentation of the class.
Note
shape functions are assumed to be real-valued.
Example: Triangular Linear Lagrangian finite elements
There are three reference shape functions \(\hat{b}^1,\hat{b}^2,\hat{b}^3\) associated with the vertices of the reference triangle. Let us assume that the refcoords argument is a 2x2 matrix \([\mathbf{x}_1\;\mathbf{x}_2]\), which corresponds to passing the coordinates of two points in the reference triangle. Then this method will return a 3x2 matrix:
\[ \begin{pmatrix}\hat{b}^1(\mathbf{x}_1) & \hat{b}^1(\mathbf{x}_2) \\ \hat{b}^2(\mathbf{x}_1) & \hat{b}^2(\mathbf{x}_2) \\ \hat{b}^3(\mathbf{x}_1)\ & \hat{b}^3(\mathbf{x}_2) \end{pmatrix} \]
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1199 of file lagr_fe.h.
EvaluationNodes()
template<typename SCALAR> Eigen::MatrixXd lf::uscalfe::FeLagrangeO3Segment< SCALAR >::EvaluationNodes () const inline nodiscard override virtual
Returns reference coordinates of "evaluation nodes" for evaluation of parametric degrees of freedom, nodal interpolation in the simplest case.
Returns
A d x N matrix, where d is the dimension of the reference cell, and N the number of interpolation nodes. The columns of this matrix contain their reference coordinates.
Every parametric scalar finite element implicitly defines a local interpolation operator by duality with the reference shape functions. This interpolation operator can be realized through evaluations at certain evaluation nodes, which are provided by this method.
Unisolvence
The evaluation points must satisfy the following requirement: If the values of a function belonging to the span of the reference shape functions are known in the evaluation nodes, then this function is uniquely determined. This entails that the number of evaluation nodes must be at least as big as the number of reference shape functions.
Note
It is not required that any vector a values at evaluation nodes can be produced by a suitable linear combination of reference shape functions. For instance, this will not be possible, if there are more evaluation points than reference shape functions. If both sets have the same size, however, the interpolation problem has a solution for any vector of values at the evluation points.
Example: Principal lattice
For triangular Lagrangian finite elements of degree p the evaluation nodes, usually called "interpolation nodes" in this context, can be chosen as \(\left(\frac{j}{p},\frac{k}{p}\right),\; 0\leq j,k \leq p, j+k\leq p\).
Moment-based degrees of freedom
For some finite element spaces the interpolation functional may be defined based on integrals over edges. In this case the evaluation nodes will be quadrature nodes for the approximate evaluation of these integrals.
The quadrature rule must be exact for the polynomials contained in the local finite element spaces.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1240 of file lagr_fe.h.
GradientsReferenceShapeFunctions()
template<typename SCALAR> Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > lf::uscalfe::FeLagrangeO3Segment< SCALAR >::GradientsReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline nodiscard override virtual
Computation of the gradients of all reference shape functions in a number of points.
Parameters
refcoords coordinates of N points in the reference cell passed as columns of a matrix of size dim x N.
Returns
An Eigen Matrix of size NumRefShapeFunctions() x (dim * refcoords.cols()) where dim is the dimension of the reference finite element. The gradients are returned in chunks of rows of this matrix.
Concerning the numbering of local shape functions, please consult the documentation of lf::assemble::DofHandler.
Example: Triangular Linear Lagrangian finite elements
There are three reference shape functions \(\hat{b}^1,\hat{b}^2,\hat{b}^3\) associated with the vertices of the reference triangle. Let us assume that the refcoords argument is a 2x2 matrix \([\mathbf{x}_1\;\mathbf{x}_2]\), which corresponds to passing the coordinates of two points in the reference triangle. Then this method will return a 3x4 matrix:
\[\begin{pmatrix} \grad^T\hat{b}^1(\mathbf{x}_1) & \grad^T\hat{b}^1(\mathbf{x}_2) \\ \grad^T\hat{b}^2(\mathbf{x}_1) & \grad^T\hat{b}^2(\mathbf{x}_2) \\ \grad^T\hat{b}^3(\mathbf{x}_1) & \grad^T\hat{b}^3(\mathbf{x}_2) \end{pmatrix} \]
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1220 of file lagr_fe.h.
NumEvaluationNodes()
template<typename SCALAR> size_type lf::uscalfe::FeLagrangeO3Segment< SCALAR >::NumEvaluationNodes () const inline nodiscard override virtual
Four evaluation nodes.
Tell the number of evaluation (interpolation) nodes.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1249 of file lagr_fe.h.
References NumRefShapeFunctions().
NumRefShapeFunctions() [1/3]
template<typename SCALAR> size_type lf::uscalfe::FeLagrangeO3Segment< SCALAR >::NumRefShapeFunctions () const inline nodiscard override virtual
Total number of reference shape functions associated with the reference cell.
Note
the total number of shape functions is the sum of the number of interior shape functions for all sub-entities and the entity itself.
Reimplemented from lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1171 of file lagr_fe.h.
Referenced by NumEvaluationNodes().
NumRefShapeFunctions() [2/3]
template<typename SCALAR> size_type lf::uscalfe::FeLagrangeO3Segment< SCALAR >::NumRefShapeFunctions (dim_t codim) const inline nodiscard override virtual
One shape function attached to each node and two interior shape functions.
The number of interior reference shape functions for sub-entities of a particular co-dimension.
Parameters
codim co-dimension of the subentity
Returns
number of interior reference shape function belonging to the specified sub-entity.
Note
this method will throw an exception when different numbers of reference shape functions are assigned to different sub-entities of the same co-dimension
Reimplemented from lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1179 of file lagr_fe.h.
NumRefShapeFunctions() [3/3]
template<typename SCALAR> size_type lf::uscalfe::FeLagrangeO3Segment< SCALAR >::NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const inline nodiscard override virtual
One shape function attached to each node and two interior shape functions.
The number of interior reference shape functions for every sub-entity.
Parameters
codim do-dimension of the subentity
subidx local index of the sub-entity
Returns
number of interior reference shape function belonging to the specified sub-entity.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1190 of file lagr_fe.h.
operator=() [1/2]
template<typename SCALAR> FeLagrangeO3Segment & lf::uscalfe::FeLagrangeO3Segment< SCALAR >::operator= (const FeLagrangeO3Segment< SCALAR > &) default
References FeLagrangeO3Segment().
operator=() [2/2]
template<typename SCALAR> FeLagrangeO3Segment & lf::uscalfe::FeLagrangeO3Segment< SCALAR >::operator= (FeLagrangeO3Segment< SCALAR > &&) default noexcept
References FeLagrangeO3Segment().
RefEl()
template<typename SCALAR> base::RefEl lf::uscalfe::FeLagrangeO3Segment< SCALAR >::RefEl () const inline nodiscard override virtual
Tells the type of reference cell underlying the parametric finite element.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 1165 of file lagr_fe.h.
References lf::base::RefEl::kSegment(), and RefEl().
Referenced by RefEl().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/uscalfe/lagr_fe.h