LehrFEM++: lf::geometry::QuadO2 Class Reference
lf::geometry::QuadO2 Class Reference
A second-order quadrilateral in the plane or in 3D space.
#include <lf/geometry/quad_o2.h>
Public Member Functions
QuadO2 (Eigen::Matrix< double, Eigen::Dynamic, 8 > coords)
Constructor building quadrilateral from vertex/midpoint coordinates.
dim_t DimLocal () const override
Dimension of the domain of this mapping.
dim_t DimGlobal () const override
Dimension of the image of this mapping.
base::RefEl RefEl () const override
The Reference element that defines the domain of this mapping.
Eigen::MatrixXd Global (const Eigen::MatrixXd &local) const override
Map a number of points in local coordinates into the global coordinate system.
Eigen::MatrixXd Jacobian (const Eigen::MatrixXd &local) const override
Evaluate the jacobian of the mapping simultaneously at numPoints points.
Eigen::MatrixXd JacobianInverseGramian (const Eigen::MatrixXd &local) const override
Evaluate the Jacobian * Inverse Gramian (\(J (J^T J)^{-1}\)) simultaneously at numPoints.
Eigen::VectorXd IntegrationElement (const Eigen::MatrixXd &local) const override
The integration element (factor appearing in integral transformation formula, see below) at number of evaluation points (specified in local coordinates).
std::unique_ptr< Geometry > SubGeometry (dim_t codim, dim_t i) const override
Construct a new Geometry() object that describes the geometry of the i-th sub-entity with codimension=codim
std::vector< std::unique_ptr< Geometry > > ChildGeometry (const RefinementPattern &ref_pat, lf::base::dim_t codim) const override
Generate geometry objects for child entities created in the course of refinement.
Public Member Functions inherited from lf::geometry::Geometry
virtual bool isAffine () const
element shape by affine mapping from reference element
virtual ~Geometry ()=default
Virtual destructor.
Private Attributes
Eigen::Matrix< double, Eigen::Dynamic, 8 > coords_
Coordinates of the 8 vertices/midpoints, stored in matrix columns.
Eigen::Matrix< double, Eigen::Dynamic, 1 > alpha_
Eigen::Matrix< double, Eigen::Dynamic, 2 > beta_
Eigen::Matrix< double, Eigen::Dynamic, 2 > gamma_
Eigen::Matrix< double, Eigen::Dynamic, 1 > delta_
Eigen::Matrix< double, Eigen::Dynamic, 2 > epsilon_
Eigen::Matrix< double, Eigen::Dynamic, 2 > gamma_x_2_
Eigen::Matrix< double, Eigen::Dynamic, 2 > epsilon_x_2_
Additional Inherited Members
Public Types inherited from lf::geometry::Geometry
using dim_t = base::RefEl::dim_t
Protected Member Functions inherited from lf::geometry::Geometry
Geometry ()=default
Geometry (const Geometry &)=default
Geometry (Geometry &&)=default
Geometry & operator= (const Geometry &)=default
Geometry & operator= (Geometry &&)=default
Related Symbols inherited from lf::geometry::Geometry
void PrintInfo (std::ostream &o, const Geometry &geom, int output_ctrl=0)
Diagnostic output operator for Geometry.
std::ostream & operator<< (std::ostream &stream, const Geometry &geom)
Operator overload to print a Geometry to a stream, such as std::cout
Detailed Description
A second-order quadrilateral in the plane or in 3D space.
Coordinates \(coords = [A, B, C, D, E, F, G, H] \) are mapped to the reference element as follows:
(0.0, 1.0) - (0.5, 1.0) - (1.0, 1.0)                  D - G - C
     |                         |                      |       |
(0.0, 0.5)                (1.0, 0.5)        ->        H       F
     |                         |                      |       |
(0.0, 0.0) - (0.5, 0.0) - (1.0, 0.0)                  A - E - B
Definition at line 29 of file quad_o2.h.
Constructor & Destructor Documentation
QuadO2()
lf::geometry::QuadO2::QuadO2 (Eigen::Matrix< double, Eigen::Dynamic, 8 > coords) explicit
Constructor building quadrilateral from vertex/midpoint coordinates.
Parameters
coords w x 8 matrix, w = world dimension, whose columns contain the world coordinates of the vertices/midpoints
Definition at line 19 of file quad_o2.cc.
References alpha_, beta_, coords_, delta_, epsilon_, epsilon_x_2_, gamma_, and gamma_x_2_.
Member Function Documentation
ChildGeometry()
std::vector< std::unique_ptr< Geometry > > lf::geometry::QuadO2::ChildGeometry (const RefinementPattern & ref_pat, lf::base::dim_t codim) const override virtual
Generate geometry objects for child entities created in the course of refinement.
Parameters
ref_pat An object encoding the details of refinement
codim relative codimension of child entities whose shape is requested
Returns
an array of unique pointers pointers to geometry objects for child entities of the specified co-dimension and the given refinement pattern. The numbering of child entities is a convention.
Implementation of local mesh refinement entails splitting of elements into parts ("children"), whose shape will depend on the refinement pattern. This method creates the geometry objects describing the shape of children. The details of subdivisions corresponding to particular refinement patterns are fixed by the method RefinementPattern::ChildPolygons() and should be documented there.
See also
class lf::geometry::RefinementPattern
For a detailed description of the indexing of the vertices of child entities see Refinement.xoj
Implements lf::geometry::Geometry.
Definition at line 184 of file quad_o2.cc.
References lf::geometry::RefinementPattern::ChildPolygons(), Global(), lf::base::RefEl::kQuad(), lf::geometry::RefinementPattern::LatticeConst(), lf::geometry::RefinementPattern::NumChildren(), lf::geometry::RefinementPattern::RefEl(), and lf::base::RefEl::ToString().
DimGlobal()
dim_t lf::geometry::QuadO2::DimGlobal () const inline override virtual
Dimension of the image of this mapping.
Implements lf::geometry::Geometry.
Definition at line 39 of file quad_o2.h.
References coords_.
Referenced by IntegrationElement(), JacobianInverseGramian(), and SubGeometry().
DimLocal()
dim_t lf::geometry::QuadO2::DimLocal () const inline override virtual
Dimension of the domain of this mapping.
Implements lf::geometry::Geometry.
Definition at line 38 of file quad_o2.h.
Global()
Eigen::MatrixXd lf::geometry::QuadO2::Global (const Eigen::MatrixXd & local) const override virtual
Map a number of points in local coordinates into the global coordinate system.
Parameters
local A Matrix of size DimLocal() x numPoints that contains in its columns the coordinates of the points at which the mapping function should be evaluated.
Returns
A Matrix of size DimGlobal() x numPoints that contains the mapped points as column vectors. Here numPoints is the number of columns of the matrix passed in the local argument.
\[ \mathtt{Global}\left(\left[\widehat{x}^1,\ldots,\widehat{x}^k\right]\right) = \left[ \mathbf{\Phi}_K(\widehat{x}^1),\ldots,\mathbf{\Phi}_K(\widehat{x}^k)\right]\;,\quad \widehat{x}^{\ell}\in\widehat{K}\;, \]
where \(\mathbf{\Phi}\) is the mapping taking the reference element to the current element \(K\).
This method provides a complete description of the shape of an entity through a parameterization over the corresponding reference element = parameter domain. The method takes as arguments a number of coordinate vectors of points in the reference element. For the sake of efficiency, these coordinate vectors are passed as the columns of a dynamic matrix type as supplied by Eigen.
For instance, this method is used in lf::geometry::Corners()
inline Eigen::MatrixXd Corners(const Geometry& geo) {
return geo.Global(geo.RefEl().NodeCoords()); }
Additional explanations in Lecture Document Paragraph 2.7.5.17.
Implements lf::geometry::Geometry.
Definition at line 56 of file quad_o2.cc.
References alpha_, beta_, delta_, epsilon_, and gamma_.
Referenced by ChildGeometry().
IntegrationElement()
Eigen::VectorXd lf::geometry::QuadO2::IntegrationElement (const Eigen::MatrixXd & local) const override virtual
The integration element (factor appearing in integral transformation formula, see below) at number of evaluation points (specified in local coordinates).
Parameters
local A Matrix of size DimLocal() x numPoints that contains the evaluation points (in local = reference coordinates) as column vectors.
Returns
A Vector of size numPoints x 1 that contains the integration elements at every evaluation point.
For a transformation \(\Phi : K \mapsto R^{\text{DimGlobal}}\) with Jacobian \(D\Phi : K \mapsto R^{\text{DimGlobal} \times \text{DimLocal}} \) the integration element \(g \) at point \(\xi \in K \) is defined by
\[ g(\xi) := \sqrt{\mathrm{det}\left|D\Phi^T(\xi) D\Phi(\xi) \right|} \]
More information also related to the use of lovcal quadrature rules is given in Lecture Document Paragraph 2.7.5.24.
Implements lf::geometry::Geometry.
Definition at line 134 of file quad_o2.cc.
References DimGlobal(), and Jacobian().
Jacobian()
Eigen::MatrixXd lf::geometry::QuadO2::Jacobian (const Eigen::MatrixXd & local) const override virtual
Evaluate the jacobian of the mapping simultaneously at numPoints points.
Parameters
local A Matrix of size DimLocal x numPoints that contains the evaluation points as column vectors
Returns
A Matrix of size DimGlobal() x (DimLocal() * numPoints) that contains the jacobians at the evaluation points.
This method allows access to the derivative of the parametrization mapping in a number of points, passed as the columns of a dynamic matrix. The derivative of the parametrization in a point is a Jacobian matrix of size ‘DimGlobal() x DimLocal()’. For the sake of efficiency, these matrices are stacked horizontally and returned as one big dynamic matrix. Use Eigen's ‘block()’ method of Eigen::MatrixXd to extract the individual Jacobians from the returned matrix.
Implements lf::geometry::Geometry.
Definition at line 69 of file quad_o2.cc.
References beta_, delta_, epsilon_, epsilon_x_2_, gamma_, and gamma_x_2_.
Referenced by IntegrationElement(), and JacobianInverseGramian().
JacobianInverseGramian()
Eigen::MatrixXd lf::geometry::QuadO2::JacobianInverseGramian (const Eigen::MatrixXd & local) const override virtual
Evaluate the Jacobian * Inverse Gramian (\(J (J^T J)^{-1}\)) simultaneously at numPoints.
Parameters
local A Matrix of size DimLocal() x numPoints that contains the evaluation points as column vectors.
Returns
A Matrix of size DimGlobal() x (DimLocal() * numPoints) that contains the Jacobian multiplied with the Inverse Gramian (\(J (J^T J)^{-1}\)) at every evaluation point.
Note
If DimLocal() == DimGlobal() then \(J (J^T J)^{-1} = J^{-T} \), i.e. this method returns the inverse of the transposed jacobian.
Example for recovering a single transposed inverse Jacobian.
If both dimensions agree and have the value D, then the method returns the transposed of the inverse Jacobians of the transformation at the passed points. These are square DxD matrices.
To retrieve the j-th inverse transposed Jacobian from the returned matrix, use the block methdod of Eigen (case (D = DimLocal()) == DimGlobal())
JacobianInverseGramian(local).block(0,i*D,D,D)
More explanations in Paragraph 2.8.3.14.
Implements lf::geometry::Geometry.
Definition at line 100 of file quad_o2.cc.
References DimGlobal(), and Jacobian().
RefEl()
base::RefEl lf::geometry::QuadO2::RefEl () const inline override virtual
The Reference element that defines the domain of this mapping.
Implements lf::geometry::Geometry.
Definition at line 40 of file quad_o2.h.
References lf::base::RefEl::kQuad().
SubGeometry()
std::unique_ptr< Geometry > lf::geometry::QuadO2::SubGeometry (dim_t codim, dim_t i) const override virtual
Construct a new Geometry() object that describes the geometry of the i-th sub-entity with codimension=codim
Parameters
codim The codimension of the sub-entity (w.r.t. DimLocal())
i The zero-based index of the sub-entity.
Returns
A new Geometry object that describes the geometry of the specified sub-entity.
Let \(\mathbf{\Phi} : K \mapsto \mathbb{R}^\text{DimGlobal} \) be the mapping of this Geometry object and let \(\mathbf{\xi} : \mathbb{R}^{\text{DimLocal}-codim} \mapsto K\) be the first-order mapping that maps the reference element RefEl().SubType(codim,i) to the i-th sub-entity of RefEl(). I.e. for every node \(\mathbf{n_j} \) of RefEl().SubType(codim,i) it holds that \(\mathbf{\xi}(\mathbf{n_j}) = \) RefEl().NodeCoords(RefEl().SubSubEntity2SubEntity(codim, i, DimLocal()-codim, j)).
Then the geometry element returned by this method describes exactly the mapping \(\mathbf{\Phi} \circ \mathbf{\xi} \)
Implements lf::geometry::Geometry.
Definition at line 160 of file quad_o2.cc.
References coords_, and DimGlobal().
Member Data Documentation
alpha_
Eigen::Matrix<double, Eigen::Dynamic, 1> lf::geometry::QuadO2::alpha_ private
Definition at line 77 of file quad_o2.h.
Referenced by Global(), and QuadO2().
beta_
Eigen::Matrix<double, Eigen::Dynamic, 2> lf::geometry::QuadO2::beta_ private
Definition at line 78 of file quad_o2.h.
Referenced by Global(), Jacobian(), and QuadO2().
coords_
Eigen::Matrix<double, Eigen::Dynamic, 8> lf::geometry::QuadO2::coords_ private
Coordinates of the 8 vertices/midpoints, stored in matrix columns.
Definition at line 70 of file quad_o2.h.
Referenced by DimGlobal(), QuadO2(), and SubGeometry().
delta_
Eigen::Matrix<double, Eigen::Dynamic, 1> lf::geometry::QuadO2::delta_ private
Definition at line 80 of file quad_o2.h.
Referenced by Global(), Jacobian(), and QuadO2().
epsilon_
Eigen::Matrix<double, Eigen::Dynamic, 2> lf::geometry::QuadO2::epsilon_ private
Definition at line 81 of file quad_o2.h.
Referenced by Global(), Jacobian(), and QuadO2().
epsilon_x_2_
Eigen::Matrix<double, Eigen::Dynamic, 2> lf::geometry::QuadO2::epsilon_x_2_ private
Definition at line 85 of file quad_o2.h.
Referenced by Jacobian(), and QuadO2().
gamma_
Eigen::Matrix<double, Eigen::Dynamic, 2> lf::geometry::QuadO2::gamma_ private
Definition at line 79 of file quad_o2.h.
Referenced by Global(), Jacobian(), and QuadO2().
gamma_x_2_
Eigen::Matrix<double, Eigen::Dynamic, 2> lf::geometry::QuadO2::gamma_x_2_ private
Definition at line 84 of file quad_o2.h.
Referenced by Jacobian(), and QuadO2().
The documentation for this class was generated from the following files:
/__w/lehrfempp/lehrfempp/lib/lf/geometry/quad_o2.h
/__w/lehrfempp/lehrfempp/lib/lf/geometry/quad_o2.cc