LehrFEM++: nonstd::span_lite Namespace Reference
nonstd::span_lite Namespace Reference
Classes
class span
A view over a contiguous, single-dimension sequence of objects, backport of std::span to C++17.
Typedefs
using index_t = span_CONFIG_INDEX_TYPE
using extent_t = std::ptrdiff_t
Functions
template<class T >
span_constexpr index_t to_size (T size)
template<class T1 , extent_t E1, class T2 , extent_t E2>
span_constexpr bool operator== (span< T1, E1 > const &l, span< T2, E2 > const &r)
template<class T1 , extent_t E1, class T2 , extent_t E2>
span_constexpr bool operator< (span< T1, E1 > const &l, span< T2, E2 > const &r)
template<class T1 , extent_t E1, class T2 , extent_t E2>
span_constexpr bool operator!= (span< T1, E1 > const &l, span< T2, E2 > const &r)
template<class T1 , extent_t E1, class T2 , extent_t E2>
span_constexpr bool operator<= (span< T1, E1 > const &l, span< T2, E2 > const &r)
template<class T1 , extent_t E1, class T2 , extent_t E2>
span_constexpr bool operator> (span< T1, E1 > const &l, span< T2, E2 > const &r)
template<class T1 , extent_t E1, class T2 , extent_t E2>
span_constexpr bool operator>= (span< T1, E1 > const &l, span< T2, E2 > const &r)
template<class T , extent_t Extent>
span_constexpr std::size_t size (span< T, Extent > const &spn)
template<class T , extent_t Extent>
span_constexpr std::ptrdiff_t ssize (span< T, Extent > const &spn)
Variables
const span_constexpr extent_t dynamic_extent = -1
Typedef Documentation
extent_t
using nonstd::span_lite::extent_t = typedef std::ptrdiff_t
Definition at line 520 of file span.h.
index_t
using nonstd::span_lite::index_t = typedef span_CONFIG_INDEX_TYPE
Definition at line 518 of file span.h.
Function Documentation
operator!=()
template<class T1 , extent_t E1, class T2 , extent_t E2> span_constexpr bool nonstd::span_lite::operator!= (span< T1, E1 > const & l, span< T2, E2 > const & r) inline
Definition at line 1243 of file span.h.
operator<()
template<class T1 , extent_t E1, class T2 , extent_t E2> span_constexpr bool nonstd::span_lite::operator< (span< T1, E1 > const & l, span< T2, E2 > const & r) inline
Definition at line 1237 of file span.h.
References nonstd::span_lite::span< T, Extent >::begin(), and nonstd::span_lite::span< T, Extent >::end().
operator<=()
template<class T1 , extent_t E1, class T2 , extent_t E2> span_constexpr bool nonstd::span_lite::operator<= (span< T1, E1 > const & l, span< T2, E2 > const & r) inline
Definition at line 1249 of file span.h.
operator==()
template<class T1 , extent_t E1, class T2 , extent_t E2> span_constexpr bool nonstd::span_lite::operator== (span< T1, E1 > const & l, span< T2, E2 > const & r) inline
Definition at line 1227 of file span.h.
References nonstd::span_lite::span< T, Extent >::begin(), nonstd::span_lite::span< T, Extent >::end(), and nonstd::span_lite::span< T, Extent >::size().
operator>()
template<class T1 , extent_t E1, class T2 , extent_t E2> span_constexpr bool nonstd::span_lite::operator> (span< T1, E1 > const & l, span< T2, E2 > const & r) inline
Definition at line 1255 of file span.h.
operator>=()
template<class T1 , extent_t E1, class T2 , extent_t E2> span_constexpr bool nonstd::span_lite::operator>= (span< T1, E1 > const & l, span< T2, E2 > const & r) inline
Definition at line 1261 of file span.h.
size()
template<class T , extent_t Extent> span_constexpr std::size_t nonstd::span_lite::size (span< T, Extent > const & spn)
Definition at line 1352 of file span.h.
References nonstd::span_lite::span< T, Extent >::size().
Referenced by nonstd::span_lite::span< T, Extent >::back(), nonstd::span_lite::span< T, Extent >::cend(), nonstd::span_lite::span< T, Extent >::empty(), nonstd::span_lite::span< T, Extent >::end(), nonstd::span_lite::span< T, Extent >::first(), nonstd::span_lite::span< T, Extent >::last(), nonstd::span_lite::span< T, Extent >::operator[](), nonstd::span_lite::span< T, Extent >::size_bytes(), nonstd::span_lite::span< T, Extent >::subspan(), and to_size().
ssize()
template<class T , extent_t Extent> span_constexpr std::ptrdiff_t nonstd::span_lite::ssize (span< T, Extent > const & spn)
Definition at line 1357 of file span.h.
References nonstd::span_lite::span< T, Extent >::size().
to_size()
template<class T > span_constexpr index_t nonstd::span_lite::to_size (T size) inline
Definition at line 806 of file span.h.
References size().
Referenced by nonstd::span_lite::span< T, Extent >::size_bytes(), and nonstd::span_lite::span< T, Extent >::span().
Variable Documentation
dynamic_extent
const span_constexpr extent_t nonstd::span_lite::dynamic_extent = -1
Definition at line 522 of file span.h.
Referenced by nonstd::span_lite::span< T, Extent >::span(), and nonstd::span_lite::span< T, Extent >::subspan().