LehrFEM++: lf::assemble::EntityMatrixProviderAT< SCALAR > Struct Template Reference
lf::assemble::EntityMatrixProviderAT< SCALAR > Struct Template Reference
Archetype for the EntityMatrixProvider concept.
#include <lf/assemble/assemble_concepts.h>
Public Member Functions
EntityMatrixProviderAT (const EntityMatrixProviderAT &) noexcept=delete
Copy constructor deleted because not part of the concept.
EntityMatrixProviderAT (EntityMatrixProviderAT &&) noexcept=delete
Move constructor deleted because not part of the concept.
auto operator= (const EntityMatrixProviderAT &) noexcept -> EntityMatrixProviderAT &=delete
Copy assignment operator deleted because not part of the concept.
auto operator= (EntityMatrixProviderAT &&) noexcept -> EntityMatrixProviderAT &=delete
Move assignment operator deleted because not part of the concept.
~EntityMatrixProviderAT () noexcept=delete
Destructor.
bool isActive (const mesh::Entity &e)
Defines whether the entity e is taken into account by the assembly routine.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > Eval (const mesh::Entity &e)
Returns the local element matrix for mesh entity e. Is only called if emp.isActive(e)==true.
Detailed Description
template<class SCALAR>
struct lf::assemble::EntityMatrixProviderAT< SCALAR >
Archetype for the EntityMatrixProvider concept.
Template Parameters
SCALAR The scalar type of the matrix entries.
See also
archetypes
Definition at line 108 of file assemble_concepts.h.
Constructor & Destructor Documentation
EntityMatrixProviderAT() [1/2]
template<class SCALAR> lf::assemble::EntityMatrixProviderAT< SCALAR >::EntityMatrixProviderAT (const EntityMatrixProviderAT< SCALAR > &) delete noexcept
Copy constructor deleted because not part of the concept.
References EntityMatrixProviderAT().
Referenced by EntityMatrixProviderAT(), EntityMatrixProviderAT(), operator=(), operator=(), and ~EntityMatrixProviderAT().
EntityMatrixProviderAT() [2/2]
template<class SCALAR> lf::assemble::EntityMatrixProviderAT< SCALAR >::EntityMatrixProviderAT (EntityMatrixProviderAT< SCALAR > &&) delete noexcept
Move constructor deleted because not part of the concept.
References EntityMatrixProviderAT().
~EntityMatrixProviderAT()
template<class SCALAR> lf::assemble::EntityMatrixProviderAT< SCALAR >::~EntityMatrixProviderAT () delete noexcept
Destructor.
References EntityMatrixProviderAT().
Member Function Documentation
Eval()
template<class SCALAR> Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > lf::assemble::EntityMatrixProviderAT< SCALAR >::Eval (const mesh::Entity & e) inline
Returns the local element matrix for mesh entity e. Is only called if emp.isActive(e)==true.
Parameters
e The entity for which the local element matrix should be returned.
Returns
The local element matrix for mesh entity e.
Definition at line 144 of file assemble_concepts.h.
isActive()
template<class SCALAR> bool lf::assemble::EntityMatrixProviderAT< SCALAR >::isActive (const mesh::Entity & e) inline
Defines whether the entity e is taken into account by the assembly routine.
Parameters
e The entity which should be queried.
Returns
true, if the entity e is taken into account by the assembly. Otherwise false.
Definition at line 133 of file assemble_concepts.h.
References isActive().
Referenced by isActive().
operator=() [1/2]
template<class SCALAR> auto lf::assemble::EntityMatrixProviderAT< SCALAR >::operator= (const EntityMatrixProviderAT< SCALAR > &) -> EntityMatrixProviderAT &=delete delete noexcept
Copy assignment operator deleted because not part of the concept.
References EntityMatrixProviderAT().
operator=() [2/2]
template<class SCALAR> auto lf::assemble::EntityMatrixProviderAT< SCALAR >::operator= (EntityMatrixProviderAT< SCALAR > &&) -> EntityMatrixProviderAT &=delete delete noexcept
Move assignment operator deleted because not part of the concept.
References EntityMatrixProviderAT().
The documentation for this struct was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/assemble/assemble_concepts.h