LehrFEM++: lf::base::LehrFemInfo Class Reference
lf::base::LehrFemInfo Class Reference
Provides extra information about this version of LehrFEM++, in particular licensing information.
#include <lf/base/lehrfem_info.h>
Static Public Member Functions
static std::string getVersionSha ()
Get the git sha1 of this commit of LehrFEM++ (agrees with the sha1 of the respective commit on github)
static std::string getVersionDateTime ()
Get the date and time of this commit of LehrFEM++.
static std::string getVersionTag ()
Get the name of a git Tag attached to this commit. (Mostly the empty string)
static void PrintInfo (std::ostream &stream)
Prints the LehrFEM++ banner to the given stream including version information.
static void PrintLicense (std::ostream &stream)
Print the MIT License which applies to the LehrFEM++ code.
static void Print3rdPartyLicenses (std::ostream &stream)
Print information about third-party libraries used by LehrFEM++ to the given stream.
Detailed Description
Provides extra information about this version of LehrFEM++, in particular licensing information.
Definition at line 20 of file lehrfem_info.h.
Member Function Documentation
getVersionDateTime()
std::string lf::base::LehrFemInfo::getVersionDateTime () static
Get the date and time of this commit of LehrFEM++.
Returns
The date and time in ISO 8601 form. Can be the empty string, if we could not determine this.
Definition at line 21 of file lehrfem_info.cc.
Referenced by PrintInfo().
getVersionSha()
std::string lf::base::LehrFemInfo::getVersionSha () static
Get the git sha1 of this commit of LehrFEM++ (agrees with the sha1 of the respective commit on github)
Returns
The commit sha1. Can be the empty string, if we cannot determine it.
Definition at line 19 of file lehrfem_info.cc.
Referenced by PrintInfo().
getVersionTag()
std::string lf::base::LehrFemInfo::getVersionTag () static
Get the name of a git Tag attached to this commit. (Mostly the empty string)
Returns
The git Tag, if there is one. Otherwise the empty string.
Note
This function may return an empty string, even if the commit of this version of LehrFEM++ has a tag attached on github. There is no guarantee, that this tag will be returned here, but it might.
Definition at line 23 of file lehrfem_info.cc.
Referenced by PrintInfo().
Print3rdPartyLicenses()
void lf::base::LehrFemInfo::Print3rdPartyLicenses (std::ostream & stream) static
Print information about third-party libraries used by LehrFEM++ to the given stream.
Parameters
stream The stream to which the information should be printed.
Definition at line 72 of file lehrfem_info.cc.
PrintInfo()
void lf::base::LehrFemInfo::PrintInfo (std::ostream & stream) static
Prints the LehrFEM++ banner to the given stream including version information.
Parameters
stream The stream to which the banner should be written.
Definition at line 25 of file lehrfem_info.cc.
References getVersionDateTime(), getVersionSha(), and getVersionTag().
PrintLicense()
void lf::base::LehrFemInfo::PrintLicense (std::ostream & stream) static
Print the MIT License which applies to the LehrFEM++ code.
Parameters
stream The stream to which the license should be output.
Definition at line 68 of file lehrfem_info.cc.
The documentation for this class was generated from the following files:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/base/lehrfem_info.h
/home/runner/work/lehrfempp/lehrfempp/lib/lf/base/lehrfem_info.cc