LehrFEM++: projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF > Class Template Reference
projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF > Class Template Reference
Class for local quadrature based computations of sub element matrices corresponding to diffusion element matrices.
#include <projects/dpg/loc_comp_dpg.h>
Public Types
using elem_mat_t = typename SubElementMatrixProvider< SCALAR >::elem_mat_t
inherited types for element matrices
using ElemMat = typename SubElementMatrixProvider< SCALAR >::ElemMat
Public Types inherited from projects::dpg::SubElementMatrixProvider< SCALAR >
using size_type = lf::uscalfe::size_type
using elem_mat_t = Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic >
internal type for element matrices
using ElemMat = elem_mat_t
Public Member Functions
DiffusionElementMatrixProvider (const DiffusionElementMatrixProvider &)=delete
DiffusionElementMatrixProvider (DiffusionElementMatrixProvider &&) noexcept=default
DiffusionElementMatrixProvider & operator= (const DiffusionElementMatrixProvider &)=delete
DiffusionElementMatrixProvider & operator= (DiffusionElementMatrixProvider &&)=delete
DiffusionElementMatrixProvider (std::shared_ptr< ProductUniformFESpace< SCALAR >> fe_space_trial, std::shared_ptr< ProductUniformFESpace< SCALAR >> fe_space_test, size_type trial_component, size_type test_component, DIFF_COEFF alpha)
Constructor: performs cell-independent precomputations.
ElemMat Eval (const lf::mesh::Entity &cell) override
main routine for the computation of element matrices
size_type TrialComponent () const override
returns the index of the trial space component \(u_{i_k} \) which is the trial space for the bilinear form \(b_k \)
size_type TestComponent () const override
returns the index of the test space component \(v_{j_k} \) which is the test space for the bilinear form \(b_k \)
~DiffusionElementMatrixProvider () override=default
Public Member Functions inherited from projects::dpg::SubElementMatrixProvider< SCALAR >
SubElementMatrixProvider ()=default
virtual ~SubElementMatrixProvider ()=default
SubElementMatrixProvider (const SubElementMatrixProvider &)=delete
standard constructors
SubElementMatrixProvider (SubElementMatrixProvider &&) noexcept=default
SubElementMatrixProvider & operator= (const SubElementMatrixProvider &)=delete
SubElementMatrixProvider & operator= (SubElementMatrixProvider &&)=delete
virtual bool isActive (const lf::mesh::Entity &)
All cells are considered active in the default implementation.
Private Attributes
DIFF_COEFF alpha_
functor providing the diffusion coefficient
std::array< lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >, 5 > fe_precomp_trial_
array containing the precomputed information for the trial space: fe_precomp_trial[i] contains the precomputed reference finite element of the trial space component u for ref_el i.
std::array< lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >, 5 > fe_precomp_test_
array containing the precomputed information for the test space: fe_precomp_trial[i] contains the precomputed reference finite element of the test space component v for ref_el i.
size_type trial_component_
index of trial component u
size_type test_component_
index of test component v
Detailed Description
template<typename SCALAR, typename DIFF_COEFF>
class projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >
Class for local quadrature based computations of sub element matrices corresponding to diffusion element matrices.
Template Parameters
SCALAR type for the entries of the element matrices. Must be a field type such as double or std::complex<double>
DIFF_COEFF a MeshFunction that defines the diffusion coefficient \(\mathbf{\alpha} \). It should be either scalar- or matrix-valued.
Note
This class complies with the type requirements for the template argument ENTITY_MATRIX_PROVIDER of the function lf::assemble::AssembleMatrixLocally().
The element matrix corresponds to the (local) bilinear form
\[ (u,v) \mapsto\int\limits_{K}\mathbf{grad}\,u \cdot \boldsymbol{\alpha}(\mathbf{x})\mathbf{grad}\,v \mathrm{d}\mathbf{x} \;, \]
with diffusion coefficient \(\mathbf{\alpha}\). \(u\) is a component of the trial space and \(v\) a component of the test space.
Template parameter requirement
SCALAR must be a type like double
DIFF_COEFF must provide an evaluation operator operator (const Entity &,ref_coord_t) that returns either a scalar or a matrix type that is compatible with Eigen's matrices. Usually it will be an Eigen::Matrix either of variable or fixed size.
Definition at line 70 of file loc_comp_dpg.h.
Member Typedef Documentation
elem_mat_t
template<typename SCALAR , typename DIFF_COEFF > using projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::elem_mat_t = typename SubElementMatrixProvider<SCALAR>::elem_mat_t
inherited types for element matrices
Definition at line 75 of file loc_comp_dpg.h.
ElemMat
template<typename SCALAR , typename DIFF_COEFF > using projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::ElemMat = typename SubElementMatrixProvider<SCALAR>::ElemMat
Definition at line 76 of file loc_comp_dpg.h.
Constructor & Destructor Documentation
DiffusionElementMatrixProvider() [1/3]
template<typename SCALAR , typename DIFF_COEFF > projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::DiffusionElementMatrixProvider (const DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF > &) delete
DiffusionElementMatrixProvider() [2/3]
template<typename SCALAR , typename DIFF_COEFF > projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::DiffusionElementMatrixProvider (DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF > &&) default noexcept
DiffusionElementMatrixProvider() [3/3]
template<typename SCALAR , typename DIFF_COEFF > projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::DiffusionElementMatrixProvider (std::shared_ptr< ProductUniformFESpace< SCALAR >> fe_space_trial, std::shared_ptr< ProductUniformFESpace< SCALAR >> fe_space_test, size_type trial_component, size_type test_component, DIFF_COEFF alpha)
Constructor: performs cell-independent precomputations.
Parameters
fe_space_trial collection of specifications for the trial fe space
fe_space_test collection of specifications for the test fe space
trial_component Index of the trial space component \(u\)
test_component Index of the test space component \(v\)
alpha mesh function for the (matrix or scalar valued) diffusion coefficient.
This constructur uses local quadrature rules with the degree of exactness chosen as the sum of the polynomial degrees of the two components \(u\) and \(v \)
Definition at line 160 of file loc_comp_dpg.h.
References projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::fe_precomp_test_, projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::fe_precomp_trial_, lf::base::RefEl::kQuad(), lf::base::RefEl::kTria(), lf::quad::make_QuadRule(), projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::test_component_, and projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::trial_component_.
~DiffusionElementMatrixProvider()
template<typename SCALAR , typename DIFF_COEFF > projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::~DiffusionElementMatrixProvider () override default
Member Function Documentation
Eval()
template<typename SCALAR , typename DIFF_COEFF > DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::ElemMat projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::Eval (const lf::mesh::Entity & cell) override virtual
main routine for the computation of element matrices
Parameters
cell reference to a (triangular or quadrilateral) cell for which the element matirx should be computed.
Returns
small dense matrix containing the element matrix
Actual computation is based on numerical quadrature and mapping techniques.
Throws an assertion, in case any specification is missing for the type of cell.
Implements projects::dpg::SubElementMatrixProvider< SCALAR >.
Definition at line 196 of file loc_comp_dpg.h.
References lf::geometry::Geometry::DimGlobal(), lf::geometry::Geometry::DimLocal(), lf::mesh::Entity::Geometry(), lf::base::RefEl::Id(), lf::geometry::Geometry::IntegrationElement(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::isInitialized(), lf::geometry::Geometry::JacobianInverseGramian(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::NumRefShapeFunctions(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::PrecompGradientsReferenceShapeFunctions(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::Qr(), and lf::mesh::Entity::RefEl().
operator=() [1/2]
template<typename SCALAR , typename DIFF_COEFF > DiffusionElementMatrixProvider& projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::operator= (const DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF > &) delete
operator=() [2/2]
template<typename SCALAR , typename DIFF_COEFF > DiffusionElementMatrixProvider& projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::operator= (DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF > &&) delete
TestComponent()
template<typename SCALAR , typename DIFF_COEFF > size_type projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::TestComponent () const inline override virtual
returns the index of the test space component \(v_{j_k} \) which is the test space for the bilinear form \(b_k \)
Implements projects::dpg::SubElementMatrixProvider< SCALAR >.
Definition at line 122 of file loc_comp_dpg.h.
References projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::test_component_.
TrialComponent()
template<typename SCALAR , typename DIFF_COEFF > size_type projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::TrialComponent () const inline override virtual
returns the index of the trial space component \(u_{i_k} \) which is the trial space for the bilinear form \(b_k \)
Implements projects::dpg::SubElementMatrixProvider< SCALAR >.
Definition at line 118 of file loc_comp_dpg.h.
References projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::trial_component_.
Member Data Documentation
alpha_
template<typename SCALAR , typename DIFF_COEFF > DIFF_COEFF projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::alpha_ private
functor providing the diffusion coefficient
Definition at line 130 of file loc_comp_dpg.h.
fe_precomp_test_
template<typename SCALAR , typename DIFF_COEFF > std::array<lf::uscalfe::PrecomputedScalarReferenceFiniteElement<SCALAR>, 5> projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::fe_precomp_test_ private
array containing the precomputed information for the test space: fe_precomp_trial[i] contains the precomputed reference finite element of the test space component v for ref_el i.
Definition at line 141 of file loc_comp_dpg.h.
Referenced by projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::DiffusionElementMatrixProvider().
fe_precomp_trial_
template<typename SCALAR , typename DIFF_COEFF > std::array<lf::uscalfe::PrecomputedScalarReferenceFiniteElement<SCALAR>, 5> projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::fe_precomp_trial_ private
array containing the precomputed information for the trial space: fe_precomp_trial[i] contains the precomputed reference finite element of the trial space component u for ref_el i.
Definition at line 136 of file loc_comp_dpg.h.
Referenced by projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::DiffusionElementMatrixProvider().
test_component_
template<typename SCALAR , typename DIFF_COEFF > size_type projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::test_component_ private
index of test component v
Definition at line 146 of file loc_comp_dpg.h.
Referenced by projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::DiffusionElementMatrixProvider(), and projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::TestComponent().
trial_component_
template<typename SCALAR , typename DIFF_COEFF > size_type projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::trial_component_ private
index of trial component u
Definition at line 144 of file loc_comp_dpg.h.
Referenced by projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::DiffusionElementMatrixProvider(), and projects::dpg::DiffusionElementMatrixProvider< SCALAR, DIFF_COEFF >::TrialComponent().
The documentation for this class was generated from the following file:
/home/travis/build/craffael/lehrfempp/projects/dpg/loc_comp_dpg.h