LehrFEM++: projects::dpg::ProductUniformFESpaceFactory< SCALAR > Class Template Reference
projects::dpg::ProductUniformFESpaceFactory< SCALAR > Class Template Reference
Factory class to build a ProductUniformFESpace.
#include </home/runner/work/lehrfempp/lehrfempp/projects/dpg/product_fe_space_factory.h>
Public Member Functions
ProductUniformFESpaceFactory (const ProductUniformFESpaceFactory &)=delete
standard constructors
ProductUniformFESpaceFactory (ProductUniformFESpaceFactory &&) noexcept=delete
ProductUniformFESpaceFactory & operator= (const ProductUniformFESpaceFactory &)=delete
ProductUniformFESpaceFactory & operator= (ProductUniformFESpaceFactory &&)=delete
ProductUniformFESpaceFactory (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
main constructor, constructs a new builder
size_type AddH1Component (size_type degree)
Adds a \(H^1(\Omega) \)-conforming finite element to the space.
size_type AddL2Component (size_type degree)
Adds a \(L^2(\Omega) \)-conforming finite element to the space.
size_type AddFluxComponent (size_type degree)
Adds a \(H^{-1/2}(S) \)-conforming finite element to the space, that represents a flux on the mesh skeleton.
size_type AddTraceComponent (size_type degree)
Adds a \(H^{1/2}(S) \)-conforming finite element to the space, that represents a trace on the mesh skeleton.
std::shared_ptr< ProductUniformFESpace< SCALAR > > Build ()
Build the ProductUniformFespace based on the provided specifications.
size_type NumComponents ()
return the number of components that have already been added.
virtual ~ProductUniformFESpaceFactory ()=default
Private Member Functions
std::shared_ptr< const lf::fe::ScalarReferenceFiniteElement< SCALAR > > ReferenceFiniteElement (lf::base::RefEl ref_el, size_type degree)
returns Lagrangian shape functions of a specified degree on a specific reference element.
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::vector< std::shared_ptr< const lf::fe::ScalarReferenceFiniteElement< SCALAR > > > rfs_tria_v_
std::vector< std::shared_ptr< const lf::fe::ScalarReferenceFiniteElement< SCALAR > > > rfs_quad_v_
std::vector< std::shared_ptr< const lf::fe::ScalarReferenceFiniteElement< SCALAR > > > rfs_segment_v_
std::vector< std::shared_ptr< const lf::fe::ScalarReferenceFiniteElement< SCALAR > > > rfs_point_v_
size_type num_components_ = 0
Detailed Description
template<typename SCALAR>
class projects::dpg::ProductUniformFESpaceFactory< SCALAR >
Factory class to build a ProductUniformFESpace.
This class can be used to construct a ProductUniformFESpace. The class provides several methods to add new components based on different continuity properties as well as the degree of the local shape functiosn .
Definition at line 33 of file product_fe_space_factory.h.
Constructor & Destructor Documentation
ProductUniformFESpaceFactory() [1/3]
template<typename SCALAR> projects::dpg::ProductUniformFESpaceFactory< SCALAR >::ProductUniformFESpaceFactory (const ProductUniformFESpaceFactory< SCALAR > &) delete
standard constructors
References ProductUniformFESpaceFactory().
Referenced by operator=(), operator=(), ProductUniformFESpaceFactory(), ProductUniformFESpaceFactory(), and ProductUniformFESpaceFactory().
ProductUniformFESpaceFactory() [2/3]
template<typename SCALAR> projects::dpg::ProductUniformFESpaceFactory< SCALAR >::ProductUniformFESpaceFactory (ProductUniformFESpaceFactory< SCALAR > &&) delete noexcept
References ProductUniformFESpaceFactory().
ProductUniformFESpaceFactory() [3/3]
template<typename SCALAR> projects::dpg::ProductUniformFESpaceFactory< SCALAR >::ProductUniformFESpaceFactory (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline explicit
main constructor, constructs a new builder
Parameters
mesh_p the underlying mesh, on which the ProductUniformFESpace will be built.
Definition at line 49 of file product_fe_space_factory.h.
References mesh_p_, and ProductUniformFESpaceFactory().
~ProductUniformFESpaceFactory()
template<typename SCALAR> virtual projects::dpg::ProductUniformFESpaceFactory< SCALAR >::~ProductUniformFESpaceFactory () virtual default
Member Function Documentation
AddFluxComponent()
template<typename SCALAR> size_type projects::dpg::ProductUniformFESpaceFactory< SCALAR >::AddFluxComponent (size_type degree)
Adds a \(H^{-1/2}(S) \)-conforming finite element to the space, that represents a flux on the mesh skeleton.
Parameters
degree the polynomial degree for the local shape functions
Returns
The zero based index of the added component.
Since fluxes only live on the mesh skeleton, local reference shape functions are only specified on segments and not on triangles or quadrilaterals.
Definition at line 252 of file product_fe_space_factory.h.
References lf::base::RefEl::kSegment(), num_components_, ReferenceFiniteElement(), rfs_point_v_, rfs_quad_v_, rfs_segment_v_, and rfs_tria_v_.
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
AddH1Component()
template<typename SCALAR> size_type projects::dpg::ProductUniformFESpaceFactory< SCALAR >::AddH1Component (size_type degree)
Adds a \(H^1(\Omega) \)-conforming finite element to the space.
Parameters
degree the polynomial degree for the local shape functions
Returns
The zero based index of the added component.
Since \(H^1(\Omega) \)-conforming finite elements are well defined on mesh interfaces, reference shape functions on triangles, quadrilaterals and segments will be specified.
Definition at line 220 of file product_fe_space_factory.h.
References lf::base::RefEl::kQuad(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), num_components_, ReferenceFiniteElement(), rfs_point_v_, rfs_quad_v_, rfs_segment_v_, and rfs_tria_v_.
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
AddL2Component()
template<typename SCALAR> size_type projects::dpg::ProductUniformFESpaceFactory< SCALAR >::AddL2Component (size_type degree)
Adds a \(L^2(\Omega) \)-conforming finite element to the space.
Parameters
degree the polynomial degree for the local shape functions
Returns
The zero based index of the added component.
Since \(L^2(\Omega) \)-conforming finite elements are no longer well defined on mesh interfaces, reference shape functions will only be specified on triangles and quadrilaterals and no longer on segments.
Note
Since the local shape functions are polynomials this function can also be used for \(H^1(\mathcal M) \) or \(H(\text{div}, \mathcal M) \)-conforming finite elements.
Definition at line 237 of file product_fe_space_factory.h.
References lf::base::RefEl::kQuad(), lf::base::RefEl::kTria(), num_components_, ReferenceFiniteElement(), rfs_point_v_, rfs_quad_v_, rfs_segment_v_, and rfs_tria_v_.
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
AddTraceComponent()
template<typename SCALAR> size_type projects::dpg::ProductUniformFESpaceFactory< SCALAR >::AddTraceComponent (size_type degree)
Adds a \(H^{1/2}(S) \)-conforming finite element to the space, that represents a trace on the mesh skeleton.
Parameters
degree the polynomial degree for the local shape functions
Returns
The zero based index of the added component.
Since traces live on the mesh skeleton, local reference shape functions on segments are specified. To to simplify assembly procedures local shape functions on triangles and quadrilaterals using the TraceScalarReferenceFiniteElement wrapper are also provided.
Definition at line 265 of file product_fe_space_factory.h.
References lf::base::RefEl::kQuad(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), num_components_, ReferenceFiniteElement(), rfs_point_v_, rfs_quad_v_, rfs_segment_v_, and rfs_tria_v_.
Build()
template<typename SCALAR> std::shared_ptr< ProductUniformFESpace< SCALAR > > projects::dpg::ProductUniformFESpaceFactory< SCALAR >::Build ()
Build the ProductUniformFespace based on the provided specifications.
Definition at line 283 of file product_fe_space_factory.h.
References mesh_p_, rfs_point_v_, rfs_quad_v_, rfs_segment_v_, and rfs_tria_v_.
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
NumComponents()
template<typename SCALAR> size_type projects::dpg::ProductUniformFESpaceFactory< SCALAR >::NumComponents () inline
return the number of components that have already been added.
Definition at line 117 of file product_fe_space_factory.h.
References num_components_.
operator=() [1/2]
template<typename SCALAR> ProductUniformFESpaceFactory & projects::dpg::ProductUniformFESpaceFactory< SCALAR >::operator= (const ProductUniformFESpaceFactory< SCALAR > &) delete
References ProductUniformFESpaceFactory().
operator=() [2/2]
template<typename SCALAR> ProductUniformFESpaceFactory & projects::dpg::ProductUniformFESpaceFactory< SCALAR >::operator= (ProductUniformFESpaceFactory< SCALAR > &&) delete
References ProductUniformFESpaceFactory().
ReferenceFiniteElement()
template<typename SCALAR> std::shared_ptr< const lf::fe::ScalarReferenceFiniteElement< SCALAR > > projects::dpg::ProductUniformFESpaceFactory< SCALAR >::ReferenceFiniteElement (lf::base::RefEl ref_el, size_type degree) private
returns Lagrangian shape functions of a specified degree on a specific reference element.
Parameters
ref_el the reference element for which the shape functions should be defined
degree the degree of the shape functions
Returns
returns a Pointer to an object representing Lagrangian shape functions of the specified degree and on the specified reference element.
Definition at line 158 of file product_fe_space_factory.h.
References lf::base::RefEl::kPoint(), lf::base::RefEl::kQuad(), lf::base::RefEl::kSegment(), and lf::base::RefEl::kTria().
Referenced by AddFluxComponent(), AddH1Component(), AddL2Component(), and AddTraceComponent().
Member Data Documentation
mesh_p_
template<typename SCALAR> std::shared_ptr<const lf::mesh::Mesh> projects::dpg::ProductUniformFESpaceFactory< SCALAR >::mesh_p_ private
the underlying mesh on which the fe-space will be built.
Definition at line 135 of file product_fe_space_factory.h.
Referenced by Build(), and ProductUniformFESpaceFactory().
num_components_
template<typename SCALAR> size_type projects::dpg::ProductUniformFESpaceFactory< SCALAR >::num_components_ = 0 private
the number of already added components.
Definition at line 153 of file product_fe_space_factory.h.
Referenced by AddFluxComponent(), AddH1Component(), AddL2Component(), AddTraceComponent(), and NumComponents().
rfs_point_v_
template<typename SCALAR> std::vector< std::shared_ptr<const lf::fe::ScalarReferenceFiniteElement<SCALAR> > > projects::dpg::ProductUniformFESpaceFactory< SCALAR >::rfs_point_v_ private
Definition at line 150 of file product_fe_space_factory.h.
Referenced by AddFluxComponent(), AddH1Component(), AddL2Component(), AddTraceComponent(), and Build().
rfs_quad_v_
template<typename SCALAR> std::vector< std::shared_ptr<const lf::fe::ScalarReferenceFiniteElement<SCALAR> > > projects::dpg::ProductUniformFESpaceFactory< SCALAR >::rfs_quad_v_ private
Definition at line 144 of file product_fe_space_factory.h.
Referenced by AddFluxComponent(), AddH1Component(), AddL2Component(), AddTraceComponent(), and Build().
rfs_segment_v_
template<typename SCALAR> std::vector< std::shared_ptr<const lf::fe::ScalarReferenceFiniteElement<SCALAR> > > projects::dpg::ProductUniformFESpaceFactory< SCALAR >::rfs_segment_v_ private
Definition at line 147 of file product_fe_space_factory.h.
Referenced by AddFluxComponent(), AddH1Component(), AddL2Component(), AddTraceComponent(), and Build().
rfs_tria_v_
template<typename SCALAR> std::vector< std::shared_ptr<const lf::fe::ScalarReferenceFiniteElement<SCALAR> > > projects::dpg::ProductUniformFESpaceFactory< SCALAR >::rfs_tria_v_ private
descriptions of reference shape functions for already added components on different types of entities
Definition at line 141 of file product_fe_space_factory.h.
Referenced by AddFluxComponent(), AddH1Component(), AddL2Component(), AddTraceComponent(), and Build().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/projects/dpg/product_fe_space_factory.h