LehrFEM++: projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF > Class Template Reference
projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF > Class Template Reference
Class for local quadrature based computations of sub element matrices corresponding to reaction element matrices.
#include <projects/dpg/loc_comp_dpg.h>
Public Types
using elem_mat_t = typename SubElementMatrixProvider<SCALAR>::elem_mat_t
inherited types for element matrices
using ElemMat = typename SubElementMatrixProvider<SCALAR>::ElemMat
Public Types inherited from projects::dpg::SubElementMatrixProvider< SCALAR >
using size_type = lf::uscalfe::size_type
using elem_mat_t = Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic>
internal type for element matrices
using ElemMat = elem_mat_t
Public Member Functions
ReactionElementMatrixProvider (const ReactionElementMatrixProvider &)=delete
ReactionElementMatrixProvider (ReactionElementMatrixProvider &&) noexcept=default
ReactionElementMatrixProvider & operator= (const ReactionElementMatrixProvider &)=delete
ReactionElementMatrixProvider & operator= (ReactionElementMatrixProvider &&)=delete
ReactionElementMatrixProvider (std::shared_ptr< ProductUniformFESpace< SCALAR > > fe_space_trial, std::shared_ptr< ProductUniformFESpace< SCALAR > > fe_space_test, size_type trial_component, size_type test_component, REACTION_COEFF gamma)
Constructor: performs cell-independent precomputations.
ElemMat Eval (const lf::mesh::Entity &cell) override
main routine for the computation of element matrices
size_type TrialComponent () const override
returns the index of the trial space component \(u_{i_k} \) which is the trial space for the bilinear form \(b_k \)
size_type TestComponent () const override
returns the index of the test space component \(v_{j_k} \) which is the test space for the bilinear form \(b_k \)
~ReactionElementMatrixProvider () override=default
Public Member Functions inherited from projects::dpg::SubElementMatrixProvider< SCALAR >
SubElementMatrixProvider ()=default
virtual ~SubElementMatrixProvider ()=default
SubElementMatrixProvider (const SubElementMatrixProvider &)=delete
standard constructors
SubElementMatrixProvider (SubElementMatrixProvider &&) noexcept=default
SubElementMatrixProvider & operator= (const SubElementMatrixProvider &)=delete
SubElementMatrixProvider & operator= (SubElementMatrixProvider &&)=delete
virtual bool isActive (const lf::mesh::Entity &)
All cells are considered active in the default implementation.
Private Attributes
REACTION_COEFF gamma_
functor providing reaction coefficient
std::array< lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >, 5 > fe_precomp_trial_
array containing the precomputed information for the trial space: fe_precomp_trial[i] contains the precomputed reference finite element of the trial space component u for ref_el i.
std::array< lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >, 5 > fe_precomp_test_
array containing the precomputed information for the test space: fe_precomp_trial[i] contains the precomputed reference finite element of the test space component v for ref_el i.
size_type trial_component_
index of trial component u
size_type test_component_
index of test component v
Detailed Description
template<typename SCALAR, typename REACTION_COEFF>
class projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >
Class for local quadrature based computations of sub element matrices corresponding to reaction element matrices.
Template Parameters
SCALAR type for the entries of the element matrices. Must be a field type such as double or std::complex<double>
REACTION_COEFF a MeshFunction that defines the reaction coefficient \(\gamma \). It should be scalar valued
Note
This class complies with the type requirements for the template argument ENTITY_MATRIX_PROVIDER of the function lf::assemble::AssembleMatrixLocally().
The element matrix corresponds to the (local) bilinear form
\[ (u,v) \mapsto\int\limits_{K} \gamma(\mathbf{x})u\,v\,\mathrm{d}\mathbf{x} \;, \]
with reaction coefficient \(\gamma \). \(u\) is a component of the trial space and \(v\) a component of the test space.
Template parameter requirement
SCALAR must be a type like double
REACTION_COEFF must provide an evaluation operator operator (const Entity &,ref_coord_t) that returns a scalar type. Usually it will be double.
Definition at line 303 of file loc_comp_dpg.h.
Member Typedef Documentation
elem_mat_t
template<typename SCALAR, typename REACTION_COEFF> using projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::elem_mat_t = typename SubElementMatrixProvider<SCALAR>::elem_mat_t
inherited types for element matrices
Definition at line 308 of file loc_comp_dpg.h.
ElemMat
template<typename SCALAR, typename REACTION_COEFF> using projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::ElemMat = typename SubElementMatrixProvider<SCALAR>::ElemMat
Definition at line 309 of file loc_comp_dpg.h.
Constructor & Destructor Documentation
ReactionElementMatrixProvider() [1/3]
template<typename SCALAR, typename REACTION_COEFF> projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::ReactionElementMatrixProvider (const ReactionElementMatrixProvider< SCALAR, REACTION_COEFF > &) delete
References ReactionElementMatrixProvider().
Referenced by operator=(), operator=(), ReactionElementMatrixProvider(), and ReactionElementMatrixProvider().
ReactionElementMatrixProvider() [2/3]
template<typename SCALAR, typename REACTION_COEFF> projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::ReactionElementMatrixProvider (ReactionElementMatrixProvider< SCALAR, REACTION_COEFF > &&) default noexcept
References ReactionElementMatrixProvider().
ReactionElementMatrixProvider() [3/3]
template<typename SCALAR, typename REACTION_COEFF> projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::ReactionElementMatrixProvider (std::shared_ptr< ProductUniformFESpace< SCALAR > > fe_space_trial, std::shared_ptr< ProductUniformFESpace< SCALAR > > fe_space_test, size_type trial_component, size_type test_component, REACTION_COEFF gamma)
Constructor: performs cell-independent precomputations.
Parameters
fe_space_trial collection of specifications for the trial fe space
fe_space_test collection of specifications for the test fe space
trial_component Index of the trial space component \(u\)
test_component Index of the test space component \(v\)
gamma mesh function for the (scalar valued) reaction coefficient.
This constructur uses local quadrature rules with the degree of exactness chosen as the sum of the polynomial degrees of the two components \(u\) and \(v \)
Definition at line 392 of file loc_comp_dpg.h.
References fe_precomp_test_, fe_precomp_trial_, gamma_, lf::base::RefEl::kQuad(), lf::base::RefEl::kTria(), lf::quad::make_QuadRule(), test_component_, and trial_component_.
~ReactionElementMatrixProvider()
template<typename SCALAR, typename REACTION_COEFF> projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::~ReactionElementMatrixProvider () override default
Member Function Documentation
Eval()
template<typename SCALAR, typename REACTION_COEFF> ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::ElemMat projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::Eval (const lf::mesh::Entity & cell) override virtual
main routine for the computation of element matrices
Parameters
cell reference to a (triangular or quadrilateral) cell for which the element matirx should be computed.
Returns
small dense matrix containing the element matrix
Actual computation is based on numerical quadrature and mapping techniques.
Throws an assertion, in case any specification is missing for the type of cell.
Implements projects::dpg::SubElementMatrixProvider< SCALAR >.
Definition at line 430 of file loc_comp_dpg.h.
References lf::geometry::Geometry::DimLocal(), fe_precomp_test_, fe_precomp_trial_, gamma_, lf::mesh::Entity::Geometry(), lf::base::RefEl::Id(), lf::geometry::Geometry::IntegrationElement(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::isInitialized(), lf::quad::QuadRule::NumPoints(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::NumRefShapeFunctions(), lf::quad::QuadRule::Points(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::PrecompReferenceShapeFunctions(), lf::uscalfe::PrecomputedScalarReferenceFiniteElement< SCALAR >::Qr(), lf::mesh::Entity::RefEl(), and lf::quad::QuadRule::Weights().
Referenced by operator=().
operator=() [1/2]
template<typename SCALAR, typename REACTION_COEFF> ReactionElementMatrixProvider & projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::operator= (const ReactionElementMatrixProvider< SCALAR, REACTION_COEFF > &) delete
References ReactionElementMatrixProvider().
operator=() [2/2]
template<typename SCALAR, typename REACTION_COEFF> ReactionElementMatrixProvider & projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::operator= (ReactionElementMatrixProvider< SCALAR, REACTION_COEFF > &&) delete
References Eval(), and ReactionElementMatrixProvider().
TestComponent()
template<typename SCALAR, typename REACTION_COEFF> size_type projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::TestComponent () const inline nodiscard override virtual
returns the index of the test space component \(v_{j_k} \) which is the test space for the bilinear form \(b_k \)
Implements projects::dpg::SubElementMatrixProvider< SCALAR >.
Definition at line 354 of file loc_comp_dpg.h.
References test_component_.
TrialComponent()
template<typename SCALAR, typename REACTION_COEFF> size_type projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::TrialComponent () const inline nodiscard override virtual
returns the index of the trial space component \(u_{i_k} \) which is the trial space for the bilinear form \(b_k \)
Implements projects::dpg::SubElementMatrixProvider< SCALAR >.
Definition at line 350 of file loc_comp_dpg.h.
References trial_component_, and TrialComponent().
Referenced by TrialComponent().
Member Data Documentation
fe_precomp_test_
template<typename SCALAR, typename REACTION_COEFF> std::array<lf::uscalfe::PrecomputedScalarReferenceFiniteElement<SCALAR>, 5> projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::fe_precomp_test_ private
array containing the precomputed information for the test space: fe_precomp_trial[i] contains the precomputed reference finite element of the test space component v for ref_el i.
Definition at line 373 of file loc_comp_dpg.h.
Referenced by Eval(), and ReactionElementMatrixProvider().
fe_precomp_trial_
template<typename SCALAR, typename REACTION_COEFF> std::array<lf::uscalfe::PrecomputedScalarReferenceFiniteElement<SCALAR>, 5> projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::fe_precomp_trial_ private
array containing the precomputed information for the trial space: fe_precomp_trial[i] contains the precomputed reference finite element of the trial space component u for ref_el i.
Definition at line 368 of file loc_comp_dpg.h.
Referenced by Eval(), and ReactionElementMatrixProvider().
gamma_
template<typename SCALAR, typename REACTION_COEFF> REACTION_COEFF projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::gamma_ private
functor providing reaction coefficient
Definition at line 362 of file loc_comp_dpg.h.
Referenced by Eval(), and ReactionElementMatrixProvider().
test_component_
template<typename SCALAR, typename REACTION_COEFF> size_type projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::test_component_ private
index of test component v
Definition at line 379 of file loc_comp_dpg.h.
Referenced by ReactionElementMatrixProvider(), and TestComponent().
trial_component_
template<typename SCALAR, typename REACTION_COEFF> size_type projects::dpg::ReactionElementMatrixProvider< SCALAR, REACTION_COEFF >::trial_component_ private
index of trial component u
Definition at line 376 of file loc_comp_dpg.h.
Referenced by ReactionElementMatrixProvider(), and TrialComponent().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/projects/dpg/loc_comp_dpg.h