LehrFEM++: lf::refinement::MeshFunctionTransfer< MF > Class Template Reference
lf::refinement::MeshFunctionTransfer< MF > Class Template Reference
A MeshFunction representing interpolation on a lf::refinement::MeshHierarchy.
#include <lf/refinement/mesh_function_transfer.h>
Public Member Functions
MeshFunctionTransfer (const lf::refinement::MeshHierarchy &mh, const MF &mf, lf::base::size_type level_coarse, lf::base::size_type level_fine)
Constructor.
decltype(auto) operator() (const lf::mesh::Entity &e, const Eigen::MatrixXd &local) const
Evaluate the MeshFunction.
std::shared_ptr< const lf::mesh::Mesh > getMesh () const
Access the underlying Mesh.
Private Types
using mf_t = std::remove_cv_t< std::remove_reference_t< MF > >
Static Private Member Functions
template<typename MF_TEST , typename = decltype(std::declval<MF_TEST>().getMesh())>
static std::true_type has_getMesh_impl (int)
template<typename MF_TEST >
static std::false_type has_getMesh_impl (...)
Private Attributes
const lf::refinement::MeshHierarchy & mh_
const MF & mf_
const lf::base::size_type level_coarse_
const lf::base::size_type level_fine_
Static Private Attributes
static constexpr bool provides_getMesh
Detailed Description
template<typename MF>
class lf::refinement::MeshFunctionTransfer< MF >
A MeshFunction representing interpolation on a lf::refinement::MeshHierarchy.
Template Parameters
The type of mesh function to interpolate on a finer mesh
Definition at line 19 of file mesh_function_transfer.h.
Member Typedef Documentation
mf_t
template<typename MF > using lf::refinement::MeshFunctionTransfer< MF >::mf_t = std::remove_cv_t<std::remove_reference_t<MF> > private
Definition at line 20 of file mesh_function_transfer.h.
Constructor & Destructor Documentation
MeshFunctionTransfer()
template<typename MF > lf::refinement::MeshFunctionTransfer< MF >::MeshFunctionTransfer (const lf::refinement::MeshHierarchy & mh, const MF & mf, lf::base::size_type level_coarse, lf::base::size_type level_fine) inline
Constructor.
Parameters
mh The lf::refinement::MeshHierarchy along which the function should be interpolated
mf The mesh function to be interpolated on a finer mesh
level_coarse The level of the Mesh which mf is defined on
level_fine The level of the Mesh this wrapper MeshFunction is defined on
Definition at line 43 of file mesh_function_transfer.h.
References lf::refinement::MeshHierarchy::getMesh(), lf::refinement::MeshHierarchy::NumLevels(), and lf::refinement::MeshFunctionTransfer< MF >::provides_getMesh.
Member Function Documentation
getMesh()
template<typename MF > std::shared_ptr<const lf::mesh::Mesh> lf::refinement::MeshFunctionTransfer< MF >::getMesh () const inline
Access the underlying Mesh.
Returns
A shared pointer to the Mesh on which this MeshFunction is defined
Definition at line 92 of file mesh_function_transfer.h.
References lf::refinement::MeshHierarchy::getMesh(), lf::refinement::MeshFunctionTransfer< MF >::level_coarse_, and lf::refinement::MeshFunctionTransfer< MF >::mh_.
has_getMesh_impl() [1/2]
template<typename MF > template<typename MF_TEST > static std::false_type lf::refinement::MeshFunctionTransfer< MF >::has_getMesh_impl (...) static private
has_getMesh_impl() [2/2]
template<typename MF > template<typename MF_TEST , typename = decltype(std::declval<MF_TEST>().getMesh())> static std::true_type lf::refinement::MeshFunctionTransfer< MF >::has_getMesh_impl (int) static private
operator()()
template<typename MF > decltype(auto) lf::refinement::MeshFunctionTransfer< MF >::operator() (const lf::mesh::Entity & e, const Eigen::MatrixXd & local) const inline
Evaluate the MeshFunction.
Parameters
e The Entity on which to evaluate this MeshFunction
local The local coordinates inside e where the MeshFunction should be evaluated
Returns
A std::vector of point evaluations of the MeshFunction
Definition at line 74 of file mesh_function_transfer.h.
References lf::refinement::MeshHierarchy::GeometryInParent(), lf::refinement::MeshFunctionTransfer< MF >::level_coarse_, lf::refinement::MeshFunctionTransfer< MF >::level_fine_, lf::refinement::MeshFunctionTransfer< MF >::mf_, lf::refinement::MeshFunctionTransfer< MF >::mh_, and lf::refinement::MeshHierarchy::ParentEntity().
Member Data Documentation
level_coarse_
template<typename MF > const lf::base::size_type lf::refinement::MeshFunctionTransfer< MF >::level_coarse_ private
Definition at line 99 of file mesh_function_transfer.h.
Referenced by lf::refinement::MeshFunctionTransfer< MF >::getMesh(), and lf::refinement::MeshFunctionTransfer< MF >::operator()().
level_fine_
template<typename MF > const lf::base::size_type lf::refinement::MeshFunctionTransfer< MF >::level_fine_ private
Definition at line 100 of file mesh_function_transfer.h.
Referenced by lf::refinement::MeshFunctionTransfer< MF >::operator()().
mf_
template<typename MF > const MF& lf::refinement::MeshFunctionTransfer< MF >::mf_ private
Definition at line 98 of file mesh_function_transfer.h.
Referenced by lf::refinement::MeshFunctionTransfer< MF >::operator()().
mh_
template<typename MF > const lf::refinement::MeshHierarchy& lf::refinement::MeshFunctionTransfer< MF >::mh_ private
Definition at line 97 of file mesh_function_transfer.h.
Referenced by lf::refinement::MeshFunctionTransfer< MF >::getMesh(), and lf::refinement::MeshFunctionTransfer< MF >::operator()().
provides_getMesh
template<typename MF > constexpr bool lf::refinement::MeshFunctionTransfer< MF >::provides_getMesh static constexpr private
Initial value:
=
      decltype(has_getMesh_impl<mf_t>(int{})){}
Definition at line 30 of file mesh_function_transfer.h.
Referenced by lf::refinement::MeshFunctionTransfer< MF >::MeshFunctionTransfer().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/refinement/mesh_function_transfer.h