LehrFEM++: projects::dpg::ProductUniformFEDofHandler Class Reference
projects::dpg::ProductUniformFEDofHandler Class Reference
Dofhandler for uniform finite element spaces that discretizes a cartesian/product space.
#include </home/travis/build/craffael/lehrfempp/projects/dpg/product_dofhandler.h>
Public Member Functions
ProductUniformFEDofHandler (std::shared_ptr< const lf::mesh::Mesh > mesh_p, std::vector< dof_map_t > dofmaps)
Construction from a vector of map objects.
size_type NumDofs () const override
size_type NumDofs (size_type component) const
tells the total number of dofs handled, that belong to a component of the Product space.
size_type NumLocalDofs (const lf::mesh::Entity &entity) const override
tells the number of degrees of freedom subordinate/_belonging_ to to an entity
size_type NumLocalDofs (const lf::mesh::Entity &entity, size_type component) const
tells the number of dofs subordinate to an entity and belonging to a component of the product space.
size_type NumInteriorDofs (const lf::mesh::Entity &entity) const override
provides number of shape functions associated with an entity
size_type NumInteriorDofs (const lf::mesh::Entity &entity, size_type component) const
tells the number of dofs associated to an entity and belonging to a component of the product space.
nonstd::span< const gdof_idx_t > GlobalDofIndices (const lf::mesh::Entity &entity) const override
access to indices of global dof's belonging to an entity
nonstd::span< const gdof_idx_t > InteriorGlobalDofIndices (const lf::mesh::Entity &entity) const override
global indices of shape functions associated with an entity_
const lf::mesh::Entity & Entity (gdof_idx_t dofnum) const override
retrieve unique entity at which a basis function is located
size_type Component (glb_idx_t dofnum) const
retrive the unique index of the component to which a global basis function belongs.
std::shared_ptr< const lf::mesh::Mesh > Mesh () const override
Acess to underlying mesh object.
const lf::assemble::UniformFEDofHandler & ComponentDofHandler (size_type component) const
Returns a DofHandler object, that handles degrees of freedoms belonging to a component.
ldof_idx_t LocalStartIndex (const lf::mesh::Entity &entity, size_type component) const
Returns the first/smallest index of a local shape functions that is associated/subordinate and that belongs to a component on a certain entity.
size_type NumComponents () const
returns the number of components of the product space.
size_type Offset (size_type component) const
Returns the first/smallest index of a global shape function belonging to a certain component.
Public Member Functions inherited from lf::assemble::DofHandler
DofHandler ()=default
The constructor just stores the mesh pointer.
virtual ~DofHandler ()=default
DofHandler (const DofHandler &)=delete
DofHandler (DofHandler &&)=delete
DofHandler & operator= (const DofHandler &)=delete
DofHandler & operator= (DofHandler &&)=delete
Private Member Functions
void initIndexArrays ()
initialization of internal index arrays.
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::vector< std::shared_ptr< lf::assemble::UniformFEDofHandler > > component_dof_handlers_
size_type num_components_
std::array< std::vector< std::vector< gdof_idx_t > >, 3 > dofs_
std::vector< glb_idx_t > offsets_
Additional Inherited Members
Related Functions inherited from lf::assemble::DofHandler
void PrintInfo (std::ostream &stream, const DofHandler &dof_handler, unsigned int ctrl=0)
Output information about the given dof handler to the given stream object.
Detailed Description
Dofhandler for uniform finite element spaces that discretizes a cartesian/product space.
This class for indices of global shape functions is suitable for situations where the FE-space is based on a Cartesian Product function space and where every geometric entity of a particular type has exactly the same number of shape functions.
Additional terminology:
We use the term "product space" or "cartesian space" for function spaces \(U \) that have the following structure
\[ U = U_0 \times U_1 \times \dots \times U_{n-1} \]
where each of the \(U_i \) is a function space of scalar valued functions.
A function in such a space represents several variables \(u = (u_0, \dots u_{n-1}) \). We usually use the term component to refer to such a variable. Each component \(u_i \) is associated to a unique component index \(i \in \{ 0,\dots n-1 \} \) representing its position
Rules for ordering global shape functions.
The following rules are used to order global shape functions in such a product space:
Dofs belonging to components of smaller component index are arranged before dofs belonging to components of larger component index.
Within each component the ususal rules for ordering global shape functions specified in lf::assemble::DofHandler apply.
Rules for ordering local shape functions.
Dofs belonging to components of smaller component index are arranged before dofs associated to components of larger component index.
Within each component the usual rules for ordering local shape functions specified in lf::assemble::DofHandler apply.
These rules result in a block structure of both Element matrices and system matrices.
This construction of the dof handler also implicitly defines a basis on the Cartesian space based on the bases on the component spaces in the following way: If the dofhandler manages dofs on the Product space \(U_h \times Q_h \) , where \(U_h\) and \(Q_h\) have bases \(\{u_i\}\) and \(\{q_j\}\), then the basis on the Cartesian space is given by: \(\{(u_i,0)\} \cup \{(0,q_j)\} \), as one would expect.
Definition at line 74 of file product_dofhandler.h.
Constructor & Destructor Documentation
ProductUniformFEDofHandler()
projects::dpg::ProductUniformFEDofHandler::ProductUniformFEDofHandler (std::shared_ptr< const lf::mesh::Mesh > mesh_p, std::vector< dof_map_t > dofmaps)
Construction from a vector of map objects.
Parameters
mesh The underlying mesh
dofmaps A vector of maps describing the local dof layout for each component. The dofmaps describe the number of interior dofs for every type of entity.
Definition at line 8 of file product_dofhandler.cc.
References component_dof_handlers_, initIndexArrays(), mesh_p_, num_components_, and offsets_.
Member Function Documentation
Component()
size_type projects::dpg::ProductUniformFEDofHandler::Component (glb_idx_t dofnum) const
retrive the unique index of the component to which a global basis function belongs.
Parameters
dofnum global index of the basis function
This function returns the unique component of the product space, to which a particular global shape function belongs.
Definition at line 143 of file product_dofhandler.cc.
References num_components_, NumDofs(), and offsets_.
Referenced by Entity().
ComponentDofHandler()
const lf::assemble::UniformFEDofHandler& projects::dpg::ProductUniformFEDofHandler::ComponentDofHandler (size_type component) const inline
Returns a DofHandler object, that handles degrees of freedoms belonging to a component.
Parameters
component index of the component for which a dofhandler should be obtained
Returns a dofhandler object that manages the global shape functions belonging to a given component. This object then numbers the shape functions of this component from 0 to NumDofs(component)-1.
Note
The resulting object no longer has any information about the product space from which it was created.
Definition at line 159 of file product_dofhandler.h.
References component_dof_handlers_.
Referenced by projects::dpg::InitEssentialConditionsFromFunctions().
Entity()
const lf::mesh::Entity & projects::dpg::ProductUniformFEDofHandler::Entity (gdof_idx_t dofnum) const override virtual
retrieve unique entity at which a basis function is located
Parameters
dofnum global index of the basis function/degree of freedom
This function returns the unique geometric entity to which a particular basis function = degree of freedom is associated.
This function is hardly ever needed in finite element codes and is supplied for debugging purposes.
See also
GlobalDofIndices()
Implements lf::assemble::DofHandler.
Definition at line 127 of file product_dofhandler.cc.
References Component(), component_dof_handlers_, and offsets_.
GlobalDofIndices()
nonstd::span< const gdof_idx_t > projects::dpg::ProductUniformFEDofHandler::GlobalDofIndices (const lf::mesh::Entity & entity) const override virtual
access to indices of global dof's belonging to an entity
Parameters
entity reference to the entity for which the dof's are to be fetched. This entity must belong to the underlying mesh.
Returns
cardinal number range of global dof indices, see std::span data type documentation.
The basis functions of every finite element space must be associated with a unique geometric entity. Conversely, every entity can possess a finite number of basis functions = degrees of freedom. This member function returns the global indices of all basis functions associated with the entity and its sub-entitites (the covering local shape functions).
The size of the returned range must agree with the value returned by NumLocalDofs() when supplied with the same arguments.
Consult Lecture Document Paragraph 2.7.4.13 for more information.
Implements lf::assemble::DofHandler.
Definition at line 101 of file product_dofhandler.cc.
References lf::base::RefEl::Dimension(), dofs_, mesh_p_, and lf::mesh::Entity::RefEl().
Referenced by projects::dpg::ElementErrorEstimators(), and initIndexArrays().
initIndexArrays()
void projects::dpg::ProductUniformFEDofHandler::initIndexArrays () private
initialization of internal index arrays.
Definition at line 34 of file product_dofhandler.cc.
References component_dof_handlers_, dofs_, GlobalDofIndices(), InteriorGlobalDofIndices(), mesh_p_, num_components_, and offsets_.
Referenced by ProductUniformFEDofHandler().
InteriorGlobalDofIndices()
nonstd::span< const gdof_idx_t > projects::dpg::ProductUniformFEDofHandler::InteriorGlobalDofIndices (const lf::mesh::Entity & entity) const override virtual
global indices of shape functions associated with an entity_
Parameters
entity entity for which shape functin indices are queried
Returns
cardinal number range of global indices of shape functions, see std::span data type documentation.
Each global shape function is associated with a unique mesh entity. This method provides all the global indices of the shape function associated to the entity specified by the function arguments, see Lecture Document Paragraph 2.7.4.13 for additional explanations.
Note
Be aware of the difference of GlobalDofIndices() and InteriorGlobalDofIndices()
Implements lf::assemble::DofHandler.
Definition at line 113 of file product_dofhandler.cc.
References lf::base::RefEl::Dimension(), mesh_p_, and lf::mesh::Entity::RefEl().
Referenced by initIndexArrays().
LocalStartIndex()
ldof_idx_t projects::dpg::ProductUniformFEDofHandler::LocalStartIndex (const lf::mesh::Entity & entity, size_type component) const
Returns the first/smallest index of a local shape functions that is associated/subordinate and that belongs to a component on a certain entity.
Parameters
entity reference to the entity for which this information is to be fetched.
component index of the component for which this information is to be fetched.
The extended rules for the ordering of local shape functions state that local shape functions belonging to certain component are numbered consecutively. This function returns the smallest local index of a shape function that bleongs to the component and is subordinate/associated to the entity.
Note
The local shape functions belonging to this component and that are subordinate/associated to the entity will have local indieces in the range \(\{ \) LocalStartIndex(entity,component), \(\dots \), LocalStartIndex(entity,component) + NoLocalDofs(entity,component) \(\} \)
Definition at line 134 of file product_dofhandler.cc.
References NumLocalDofs().
Mesh()
std::shared_ptr< const lf::mesh::Mesh > projects::dpg::ProductUniformFEDofHandler::Mesh () const override virtual
Acess to underlying mesh object.
Every DofHandler object has to be associated with a unique mesh. All entities passed to the DofHandler object must belong to that mesh.
Implements lf::assemble::DofHandler.
Definition at line 123 of file product_dofhandler.cc.
References mesh_p_.
Referenced by projects::dpg::ElementErrorEstimators().
NumComponents()
size_type projects::dpg::ProductUniformFEDofHandler::NumComponents () const inline
returns the number of components of the product space.
Definition at line 191 of file product_dofhandler.h.
References num_components_.
NumDofs() [1/2]
size_type projects::dpg::ProductUniformFEDofHandler::NumDofs () const override virtual
Implements lf::assemble::DofHandler.
Definition at line 67 of file product_dofhandler.cc.
References num_components_, and offsets_.
Referenced by Component(), and projects::dpg::InitEssentialConditionsFromFunctions().
NumDofs() [2/2]
size_type projects::dpg::ProductUniformFEDofHandler::NumDofs (size_type component) const
tells the total number of dofs handled, that belong to a component of the Product space.
Parameters
component index identifying a component of the product space.
Definition at line 71 of file product_dofhandler.cc.
References component_dof_handlers_.
NumInteriorDofs() [1/2]
size_type projects::dpg::ProductUniformFEDofHandler::NumInteriorDofs (const lf::mesh::Entity & entity) const override virtual
provides number of shape functions associated with an entity
Parameters
entity entity of underlying mesh whose number of shape functions is queried
The return value of this method must be equal to the length of the range built by InteriorGlobalDofIndices().
See also
InteriorGlobalDofIndices()
Implements lf::assemble::DofHandler.
Definition at line 88 of file product_dofhandler.cc.
References lf::base::RefEl::Dimension(), mesh_p_, and lf::mesh::Entity::RefEl().
NumInteriorDofs() [2/2]
size_type projects::dpg::ProductUniformFEDofHandler::NumInteriorDofs (const lf::mesh::Entity & entity, size_type component) const
tells the number of dofs associated to an entity and belonging to a component of the product space.
Parameters
entity entity of the underlying mesh whose number of shape functions is queried
component index identifying the component of the product space.
Definition at line 96 of file product_dofhandler.cc.
References component_dof_handlers_.
NumLocalDofs() [1/2]
size_type projects::dpg::ProductUniformFEDofHandler::NumLocalDofs (const lf::mesh::Entity & entity) const override virtual
tells the number of degrees of freedom subordinate/_belonging_ to to an entity
Parameters
entity reference to an entity of the underlying mesh
This method informs about the length of the vector returned by GlobalDofIndices().
See also
GlobalDofIndices()
Implements lf::assemble::DofHandler.
Definition at line 75 of file product_dofhandler.cc.
References lf::base::RefEl::Dimension(), dofs_, mesh_p_, and lf::mesh::Entity::RefEl().
Referenced by projects::dpg::ElementErrorEstimators(), and LocalStartIndex().
NumLocalDofs() [2/2]
size_type projects::dpg::ProductUniformFEDofHandler::NumLocalDofs (const lf::mesh::Entity & entity, size_type component) const
tells the number of dofs subordinate to an entity and belonging to a component of the product space.
Parameters
entity entity of the underlying mesh whose number of shape functions is queried
component index identifying the component of the product space.
Definition at line 83 of file product_dofhandler.cc.
References component_dof_handlers_.
Offset()
size_type projects::dpg::ProductUniformFEDofHandler::Offset (size_type component) const inline
Returns the first/smallest index of a global shape function belonging to a certain component.
Parameters
component index of the component for which this information is to be fetched.
The extended rules for the ordering of global shape functions state that global shape functions associated with certain component are numbered consecutively. This function returns the smallest global index of a shape functions that belongs to a certain component component.
Note
The global shape functions associated with this component will have global indices in the range \(\{ \) Offset(component), \(\dots\) , Offset(component) + NumDofs(component) \(\} \)
Definition at line 208 of file product_dofhandler.h.
References offsets_.
Referenced by projects::dpg::InitEssentialConditionsFromFunctions().
Member Data Documentation
component_dof_handlers_
std::vector<std::shared_ptr<lf::assemble::UniformFEDofHandler> > projects::dpg::ProductUniformFEDofHandler::component_dof_handlers_ private
dof handlers for each component:
Definition at line 223 of file product_dofhandler.h.
Referenced by ComponentDofHandler(), Entity(), initIndexArrays(), NumDofs(), NumInteriorDofs(), NumLocalDofs(), and ProductUniformFEDofHandler().
dofs_
std::array<std::vector<std::vector<gdof_idx_t> >, 3> projects::dpg::ProductUniformFEDofHandler::dofs_ private
vector of global indices of dofs subordinate to entities of different topological type
Definition at line 231 of file product_dofhandler.h.
Referenced by GlobalDofIndices(), initIndexArrays(), and NumLocalDofs().
mesh_p_
std::shared_ptr<const lf::mesh::Mesh> projects::dpg::ProductUniformFEDofHandler::mesh_p_ private
mesh on which the degrees of freedom are defined
Definition at line 219 of file product_dofhandler.h.
Referenced by GlobalDofIndices(), initIndexArrays(), InteriorGlobalDofIndices(), Mesh(), NumInteriorDofs(), NumLocalDofs(), and ProductUniformFEDofHandler().
num_components_
size_type projects::dpg::ProductUniformFEDofHandler::num_components_ private
the total number of components
Definition at line 226 of file product_dofhandler.h.
Referenced by Component(), initIndexArrays(), NumComponents(), NumDofs(), and ProductUniformFEDofHandler().
offsets_
std::vector<glb_idx_t> projects::dpg::ProductUniformFEDofHandler::offsets_ private
stores the global offsets for the different components:
Definition at line 239 of file product_dofhandler.h.
Referenced by Component(), Entity(), initIndexArrays(), NumDofs(), Offset(), and ProductUniformFEDofHandler().
The documentation for this class was generated from the following files:
/home/travis/build/craffael/lehrfempp/projects/dpg/product_dofhandler.h
/home/travis/build/craffael/lehrfempp/projects/dpg/product_dofhandler.cc