LehrFEM++: projects::dpg::ProductElementVectorProviderBuilder< SCALAR > Class Template Reference
projects::dpg::ProductElementVectorProviderBuilder< SCALAR > Class Template Reference
Builder class to build a ProductElementVectorProvider.
#include </home/runner/work/lehrfempp/lehrfempp/projects/dpg/product_element_vector_provider_builder.h>
Public Member Functions
ProductElementVectorProviderBuilder (const ProductElementVectorProviderBuilder &)=delete
standard constructor
ProductElementVectorProviderBuilder (ProductElementVectorProviderBuilder &&) noexcept=delete
ProductElementVectorProviderBuilder & operator= (const ProductElementVectorProviderBuilder &)=delete
ProductElementVectorProviderBuilder & operator= (ProductElementVectorProviderBuilder &&)=delete
ProductElementVectorProviderBuilder (std::shared_ptr< ProductUniformFESpace< SCALAR > > fe_space_test)
main contructor, construct a new builder
template<typename FUNCTOR>
ProductElementVectorProviderBuilder & AddLoadElementVectorProvider (size_type test_component, FUNCTOR f)
Adds a linear form \(l_k \) to \(l \) representing a simple load linear form.
std::shared_ptr< ProductElementVectorProvider< SCALAR > > Build ()
Build the ProductElementVectorProvider based on the provided linear forms.
~ProductElementVectorProviderBuilder ()=default
default destructor
template<typename FUNCTOR>
ProductElementVectorProviderBuilder< SCALAR > & AddLoadElementVectorProvider (size_type test_component, FUNCTOR f)
Private Attributes
std::shared_ptr< ProductUniformFESpace< SCALAR > > fe_space_test_
collection of specifications for the test space
std::vector< std::shared_ptr< SubElementVectorProvider< SCALAR > > > subproviders_
vector of Element Vector Providers representing already added linear forms
Detailed Description
template<typename SCALAR>
class projects::dpg::ProductElementVectorProviderBuilder< SCALAR >
Builder class to build a ProductElementVectorProvider.
Template Parameters
SCLAR type of entries of the element vectors. Fieldtype such as double.
This class can be used to construct a ProductElementVectorProvider on a product space
\[ V = V_0 \times V_1 \times \dots \times V_{m-1} \]
passed in the constructor. Methods are provided to add several linear forms
\[ l_k : V_{j_k} \rightarrow \mathbb{R} \]
on a specified component of the space.
the constructed ProductElementVectorProvider evalautes element vectors of the linear form \(l: V \rightarrow \mathbb{R} \) given by
\[ l((v_1, \dots v_{m-1})) = \sum_{k} l_k(v_{j_k}) \]
Definition at line 29 of file product_element_vector_provider_builder.h.
Constructor & Destructor Documentation
ProductElementVectorProviderBuilder() [1/3]
template<typename SCALAR> projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::ProductElementVectorProviderBuilder (const ProductElementVectorProviderBuilder< SCALAR > &) delete
standard constructor
References ProductElementVectorProviderBuilder().
Referenced by AddLoadElementVectorProvider(), operator=(), operator=(), ProductElementVectorProviderBuilder(), ProductElementVectorProviderBuilder(), and ProductElementVectorProviderBuilder().
ProductElementVectorProviderBuilder() [2/3]
template<typename SCALAR> projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::ProductElementVectorProviderBuilder (ProductElementVectorProviderBuilder< SCALAR > &&) delete noexcept
References ProductElementVectorProviderBuilder().
ProductElementVectorProviderBuilder() [3/3]
template<typename SCALAR> projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::ProductElementVectorProviderBuilder (std::shared_ptr< ProductUniformFESpace< SCALAR > > fe_space_test) inline explicit
main contructor, construct a new builder
Parameters
fe_space_test collection of specifications about the (product) space \(V \)
Definition at line 46 of file product_element_vector_provider_builder.h.
References fe_space_test_, and ProductElementVectorProviderBuilder().
~ProductElementVectorProviderBuilder()
template<typename SCALAR> projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::~ProductElementVectorProviderBuilder () default
default destructor
Member Function Documentation
AddLoadElementVectorProvider() [1/2]
template<typename SCALAR> template<typename FUNCTOR> ProductElementVectorProviderBuilder & projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::AddLoadElementVectorProvider (size_type test_component, FUNCTOR f)
Adds a linear form \(l_k \) to \(l \) representing a simple load linear form.
Parameters
test_component index of the component \(v \) of \(l_k \)
f mesh function for the scalar valued source function \(f \)
Template Parameters
FUNCTOR see the type requirements of the template parameter FUNCTOR of the LoadElementVectorProvider class.
The (local) added linear form \(l_k\) is
\[ v \mapsto \int_K f(\mathbf{x})\,v\,\mathrm{d}\mathbf{x}\;, \]
For further information about the added added linear form \(l_k \) see the documentation of LoadElementVectorProvider
References ProductElementVectorProviderBuilder().
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
AddLoadElementVectorProvider() [2/2]
template<typename SCALAR> template<typename FUNCTOR> ProductElementVectorProviderBuilder< SCALAR > & projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::AddLoadElementVectorProvider (size_type test_component, FUNCTOR f)
Definition at line 92 of file product_element_vector_provider_builder.h.
References fe_space_test_, and subproviders_.
Build()
template<typename SCALAR> std::shared_ptr< ProductElementVectorProvider< SCALAR > > projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::Build ()
Build the ProductElementVectorProvider based on the provided linear forms.
Definition at line 102 of file product_element_vector_provider_builder.h.
References fe_space_test_, and subproviders_.
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
operator=() [1/2]
template<typename SCALAR> ProductElementVectorProviderBuilder & projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::operator= (const ProductElementVectorProviderBuilder< SCALAR > &) delete
References ProductElementVectorProviderBuilder().
operator=() [2/2]
template<typename SCALAR> ProductElementVectorProviderBuilder & projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::operator= (ProductElementVectorProviderBuilder< SCALAR > &&) delete
References ProductElementVectorProviderBuilder().
Member Data Documentation
fe_space_test_
template<typename SCALAR> std::shared_ptr<ProductUniformFESpace<SCALAR> > projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::fe_space_test_ private
collection of specifications for the test space
Definition at line 83 of file product_element_vector_provider_builder.h.
Referenced by AddLoadElementVectorProvider(), Build(), and ProductElementVectorProviderBuilder().
subproviders_
template<typename SCALAR> std::vector<std::shared_ptr<SubElementVectorProvider<SCALAR> > > projects::dpg::ProductElementVectorProviderBuilder< SCALAR >::subproviders_ private
vector of Element Vector Providers representing already added linear forms
Definition at line 86 of file product_element_vector_provider_builder.h.
Referenced by AddLoadElementVectorProvider(), and Build().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/projects/dpg/product_element_vector_provider_builder.h