LehrFEM++: lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > Class Template Reference
lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > Class Template Reference final
EntityVectorProvider
Local computation of general element (load) vector for scalar finite elements; volume contributions only.
#include <lf/fe/fe.h>
Public Types
using scalar_t
using ElemVec = Eigen::Matrix<scalar_t, Eigen::Dynamic, 1>
Public Member Functions
ScalarLoadElementVectorProvider (std::shared_ptr< const ScalarFESpace< SCALAR > > fe_space, MESH_FUNCTION f)
Constructor, performs precomputations.
bool isActive (const lf::mesh::Entity &) const
all cells are active
ElemVec Eval (const lf::mesh::Entity &cell) const
~ScalarLoadElementVectorProvider ()=default
standard constructors
ScalarLoadElementVectorProvider (const ScalarLoadElementVectorProvider &)=delete
ScalarLoadElementVectorProvider (ScalarLoadElementVectorProvider &&) noexcept=default
ScalarLoadElementVectorProvider & operator= (const ScalarLoadElementVectorProvider &)=delete
ScalarLoadElementVectorProvider & operator= (ScalarLoadElementVectorProvider &&)=delete
Private Attributes
MESH_FUNCTION f_
An object providing the source function.
std::shared_ptr< const ScalarFESpace< SCALAR > > fe_space_
quad::QuadRuleCache qr_cache_
Detailed Description
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION>
class lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >
Local computation of general element (load) vector for scalar finite elements; volume contributions only.
Template Parameters
SCALAR underlying scalar type of the ScalarFESpace, usually double or complex<double>
MESH_FUNCTION MeshFunction which defines the source function \(f \)
The underlying local linear form is
\[ v \mapsto \int_K f(\mathbf{x})\,\overline{v(\mathbf{x})}\,\mathrm{d}\mathbf{x}\;, \]
where \(f\) is supposed to be a locally continuous source function.
Computation is based on a quadrature rules supplied by the LehrFEM++ lf::quad::QuadRule module.
This class complies with the requirements for the template parameter ELEM_VEC_COMP of the function assemble::AssembleVectorLocally().
Example usage
The following code snippet computes the solution of the BVP
\begin{align} - \Delta u &= 1 && \text{on }\Omega := [0,1]^2 \\ u &= 0 && \text{on }\partial \Omega \end{align}
  // Get a mesh
  auto mesh_p = lf::mesh::test_utils::GenerateHybrid2DTestMesh();
  // Create HierarchicalFESpace with uniform degree 5.
  const unsigned degree = 5;
  const auto fe_space =
      std::make_shared<lf::fe::HierarchicScalarFESpace<double>>(mesh_p, degree);
  // define diffusion coefficient
  const lf::mesh::utils::MeshFunctionConstant mf_alpha(1);
  // define rhs load
  auto mf_load = lf::mesh::utils::MeshFunctionConstant(1.);
  // Assemble the system matrix and right hand side
  Eigen::VectorXd rhs = Eigen::VectorXd::Zero(fe_space->LocGlobMap().NumDofs());
  const assemble::DofHandler &dofh = fe_space->LocGlobMap();
  assemble::COOMatrix<double> A_COO(dofh.NumDofs(), dofh.NumDofs());
  DiffusionElementMatrixProvider element_matrix_provider(fe_space, mf_alpha);
  AssembleMatrixLocally(0, dofh, dofh, element_matrix_provider, A_COO);
  ScalarLoadElementVectorProvider element_vector_provider(fe_space, mf_load);
  AssembleVectorLocally(0, dofh, element_vector_provider, rhs);
  // Enforce zero dirichlet boundary conditions
  const auto boundary = lf::mesh::utils::flagEntitiesOnBoundary(mesh_p);
  const auto selector = [&](unsigned int idx) -> std::pair<bool, double> {
    const auto &entity = dofh.Entity(idx);
    return {entity.Codim() > 0 && boundary(entity), 0};
  };
  FixFlaggedSolutionComponents(selector, A_COO, rhs);
  // Solve the LSE using the cholesky decomposition
  Eigen::SparseMatrix<double> A = A_COO.makeSparse();
  Eigen::SimplicialLDLT<Eigen::SparseMatrix<double>> solver(A);
  const Eigen::VectorXd solution = solver.solve(rhs);
  // visualize the solution:
  io::VtkWriter vtk(mesh_p, "solution.vtk", 0, 5);
  vtk.WritePointData("solution", MeshFunctionFE(fe_space, solution));
Definition at line 569 of file loc_comp_ellbvp.h.
Member Typedef Documentation
ElemVec
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> using lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ElemVec = Eigen::Matrix<scalar_t, Eigen::Dynamic, 1>
Definition at line 575 of file loc_comp_ellbvp.h.
scalar_t
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> using lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::scalar_t
Initial value:
      decltype(static_cast<SCALAR>(0) *
               static_cast<mesh::utils::MeshFunctionReturnType<MESH_FUNCTION>>(
                   0))
Definition at line 571 of file loc_comp_ellbvp.h.
Constructor & Destructor Documentation
ScalarLoadElementVectorProvider() [1/3]
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider (const ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &) delete
References ScalarLoadElementVectorProvider().
Referenced by operator=(), operator=(), ScalarLoadElementVectorProvider(), and ScalarLoadElementVectorProvider().
ScalarLoadElementVectorProvider() [2/3]
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider (ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &&) default noexcept
References ScalarLoadElementVectorProvider().
ScalarLoadElementVectorProvider() [3/3]
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider (std::shared_ptr< const ScalarFESpace< SCALAR > > fe_space, MESH_FUNCTION f)
Constructor, performs precomputations.
Parameters
fe_space specification of local shape functions
f functor object for source function
Uses quadrature rule of double the degree of exactness compared to the degree of the finite element space.
Definition at line 634 of file loc_comp_ellbvp.h.
References f_, and fe_space_.
~ScalarLoadElementVectorProvider()
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::~ScalarLoadElementVectorProvider () default
Member Function Documentation
Eval()
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ElemVec lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::Eval (const lf::mesh::Entity & cell) const
Definition at line 644 of file loc_comp_ellbvp.h.
References lf::geometry::Geometry::DimLocal(), f_, fe_space_, lf::mesh::Entity::Geometry(), lf::geometry::Geometry::Global(), lf::geometry::Geometry::IntegrationElement(), lf::base::RefEl::NodeCoords(), lf::quad::QuadRule::NumPoints(), lf::quad::QuadRule::Points(), qr_cache_, lf::mesh::Entity::RefEl(), lf::fe::ScalarLoadElementVectorProviderLogger(), and lf::quad::QuadRule::Weights().
isActive()
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> bool lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::isActive (const lf::mesh::Entity &) const inline
all cells are active
Definition at line 600 of file loc_comp_ellbvp.h.
References isActive().
Referenced by isActive().
operator=() [1/2]
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> ScalarLoadElementVectorProvider & lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::operator= (const ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &) delete
References ScalarLoadElementVectorProvider().
operator=() [2/2]
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> ScalarLoadElementVectorProvider & lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::operator= (ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &&) delete
References ScalarLoadElementVectorProvider().
Member Data Documentation
f_
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> MESH_FUNCTION lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::f_ private
An object providing the source function.
Definition at line 614 of file loc_comp_ellbvp.h.
Referenced by Eval(), and ScalarLoadElementVectorProvider().
fe_space_
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> std::shared_ptr<const ScalarFESpace<SCALAR> > lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::fe_space_ private
Definition at line 616 of file loc_comp_ellbvp.h.
Referenced by Eval(), and ScalarLoadElementVectorProvider().
qr_cache_
template<base::Scalar SCALAR, mesh::utils::MeshFunction MESH_FUNCTION> quad::QuadRuleCache lf::fe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::qr_cache_ private
Definition at line 618 of file loc_comp_ellbvp.h.
Referenced by Eval().
The documentation for this class was generated from the following file:
/home/runner/work/lehrfempp/lehrfempp/lib/lf/fe/loc_comp_ellbvp.h