LehrFEM++: projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider Class Reference
projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider Class Reference
Element vector provider for the stokes system.
#include </home/runner/work/lehrfempp/lehrfempp/projects/ipdg_stokes/assemble/piecewise_const_element_vector_provider.h>
Public Member Functions
PiecewiseConstElementVectorProvider (double sigma, std::function< Eigen::Vector2d(const Eigen::Vector2d &)> f, lf::quad::QuadRule quadrule, const lf::mesh::utils::MeshDataSet< bool > &boundary, const lf::mesh::utils::MeshDataSet< Eigen::Vector2d > &dirichlet_data)
Constructor.
Eigen::VectorXd Eval (const lf::mesh::Entity &entity) const
Compute the element vector for some entity of the mesh.
bool isActive (const lf::mesh::Entity &entity) const
All entities are regarded as active.
Private Attributes
const double sigma_
const std::function< Eigen::Vector2d(const Eigen::Vector2d &)> f_
const lf::quad::QuadRule quadrule_
const lf::mesh::utils::MeshDataSet< bool > & boundary_
const lf::mesh::utils::MeshDataSet< Eigen::Vector2d > & dirichlet_data_
Detailed Description
Element vector provider for the stokes system.
Note
Currently, only triangular meshes are supported
The linear form is given by
\[ v \mapsto \int_K\! f \cdot v \,\mathrm{d}x + \sum_{e\in\mathcal{E}^\partial(\mathcal{M})} \int_e\! \frac{\sigma}{|e|} \left(g_D\cdot\tau_e\right) \left[\!\left[v\cdot\tau_e\right]\!\right] \,\mathrm{d}x \]
Definition at line 35 of file piecewise_const_element_vector_provider.h.
Constructor & Destructor Documentation
PiecewiseConstElementVectorProvider()
projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::PiecewiseConstElementVectorProvider (double sigma, std::function< Eigen::Vector2d(const Eigen::Vector2d &)> f, lf::quad::QuadRule quadrule, const lf::mesh::utils::MeshDataSet< bool > & boundary, const lf::mesh::utils::MeshDataSet< Eigen::Vector2d > & dirichlet_data)
Constructor.
Parameters
sigma The stabilization parameter for IP-DG
f A function mapping coordinates to the volumetric forces
quadrule The quadrature rule used to compute the integral in the linear form
boundary A mesh data set marking the boundary edges
dirichlet_data A mesh data set containing the dirichlet data for the velocity on the boundary edges
Definition at line 11 of file piecewise_const_element_vector_provider.cc.
Member Function Documentation
Eval()
Eigen::VectorXd projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::Eval (const lf::mesh::Entity & entity) const
Compute the element vector for some entity of the mesh.
Parameters
entity The mesh entity to compute the element vector for
Returns
The element vector of the given entity
Note
This function currently only works for triangles
Definition at line 22 of file piecewise_const_element_vector_provider.cc.
References boundary_, projects::ipdg_stokes::mesh::computeOutwardNormals(), dirichlet_data_, f_, lf::mesh::Entity::Geometry(), lf::uscalfe::FeLagrangeO1Tria< SCALAR >::GradientsReferenceShapeFunctions(), lf::base::RefEl::NodeCoords(), lf::quad::QuadRule::NumPoints(), lf::quad::QuadRule::Points(), quadrule_, lf::mesh::Entity::RefEl(), lf::mesh::Entity::SubEntities(), and lf::quad::QuadRule::Weights().
isActive()
bool projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::isActive (const lf::mesh::Entity & entity) const inline
All entities are regarded as active.
Definition at line 65 of file piecewise_const_element_vector_provider.h.
Member Data Documentation
boundary_
const lf::mesh::utils::MeshDataSet<bool>& projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::boundary_ private
Definition at line 71 of file piecewise_const_element_vector_provider.h.
Referenced by Eval().
dirichlet_data_
const lf::mesh::utils::MeshDataSet<Eigen::Vector2d>& projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::dirichlet_data_ private
Definition at line 72 of file piecewise_const_element_vector_provider.h.
Referenced by Eval().
f_
const std::function<Eigen::Vector2d(const Eigen::Vector2d &)> projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::f_ private
Definition at line 69 of file piecewise_const_element_vector_provider.h.
Referenced by Eval().
quadrule_
const lf::quad::QuadRule projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::quadrule_ private
Definition at line 70 of file piecewise_const_element_vector_provider.h.
Referenced by Eval().
sigma_
const double projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::sigma_ private
Definition at line 68 of file piecewise_const_element_vector_provider.h.
The documentation for this class was generated from the following files:
/home/runner/work/lehrfempp/lehrfempp/projects/ipdg_stokes/assemble/piecewise_const_element_vector_provider.h
/home/runner/work/lehrfempp/lehrfempp/projects/ipdg_stokes/assemble/piecewise_const_element_vector_provider.cc