LehrFEM++: projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler Class Reference
projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler Class Reference
Local assembler for a matrix mapping boundary basis function coefficients to jumps.
#include </home/runner/work/lehrfempp/lehrfempp/projects/ipdg_stokes/assemble/offset_function.h>
Public Member Functions
PiecewiseBoundaryNormalJumpAssembler (std::shared_ptr< const lf::mesh::Mesh > mesh, const lf::mesh::utils::MeshDataSet< bool > &boundary)
Constructor.
Eigen::MatrixXd Eval (const lf::mesh::Entity &entity) const
Compute the element matrix for some triangle of the mesh.
bool isActive (const lf::mesh::Entity &entity) const
All entities are regarded as active.
Private Attributes
const std::shared_ptr< const lf::mesh::Mesh > mesh_
const lf::mesh::utils::MeshDataSet< bool > & boundary_
Detailed Description
Local assembler for a matrix mapping boundary basis function coefficients to jumps.
This assembler builds a matrix mapping the basis function coefficients f nodes on the mesh boundary to the normal component of the jump over the boundary edges. This is used for assembling the offset function, as the dirichlet data is given in terms of boundary jumps, but the actual solution uses the nodal values as basis function coefficients.
Definition at line 31 of file offset_function.h.
Constructor & Destructor Documentation
PiecewiseBoundaryNormalJumpAssembler()
projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler::PiecewiseBoundaryNormalJumpAssembler (std::shared_ptr< const lf::mesh::Mesh > mesh, const lf::mesh::utils::MeshDataSet< bool > & boundary)
Constructor.
Parameters
mesh A shared pointer to the mesh on which the PDE is solved
boundary A MeshDataSet marking the boundary entities
Definition at line 18 of file offset_function.cc.
References boundary_, and mesh_.
Member Function Documentation
Eval()
Eigen::MatrixXd projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler::Eval (const lf::mesh::Entity & entity) const
Compute the element matrix for some triangle of the mesh.
Parameters
entity The mesh entity to compute the element matrix for
Returns
The element matrix for the given entity
Definition at line 23 of file offset_function.cc.
References boundary_, projects::ipdg_stokes::mesh::computeOutwardNormals(), lf::mesh::Entity::Geometry(), lf::uscalfe::FeLagrangeO1Tria< SCALAR >::GradientsReferenceShapeFunctions(), and lf::mesh::Entity::SubEntities().
isActive()
bool projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler::isActive (const lf::mesh::Entity & entity) const inline
All entities are regarded as active.
Definition at line 52 of file offset_function.h.
Member Data Documentation
boundary_
const lf::mesh::utils::MeshDataSet<bool>& projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler::boundary_ private
Definition at line 56 of file offset_function.h.
Referenced by Eval(), and PiecewiseBoundaryNormalJumpAssembler().
mesh_
const std::shared_ptr<const lf::mesh::Mesh> projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler::mesh_ private
Definition at line 55 of file offset_function.h.
Referenced by PiecewiseBoundaryNormalJumpAssembler().
The documentation for this class was generated from the following files:
/home/runner/work/lehrfempp/lehrfempp/projects/ipdg_stokes/assemble/offset_function.h
/home/runner/work/lehrfempp/lehrfempp/projects/ipdg_stokes/assemble/offset_function.cc