LehrFEM++: Special "named" quadrature rules
Special "named" quadrature rules
Detailed Description
@breif Creation of special quadrature rules
These functions provide a number of special quadrature rules in the forms of QuadRule objects. They are meant to be used in low-order finite element methods when the quadrature rules can easily fixed a-priori and should feature a special location of quadrature points as is required, e.g., for mass-lumping techniques.
For some examples see Lecture Document Example 2.7.5.33.
QuadRule objects with a particular order but otherwise unspecified properties can be created by lf::quad::make_QuadRule().
Functions
QuadRule lf::quad::make_TriaQR_MidpointRule ()
midpoint quadrature rule for triangles
QuadRule lf::quad::make_TriaQR_P1O2 ()
QuadRule lf::quad::make_TriaQR_EdgeMidpointRule ()
edge midpoint quadrature rule for reference triangles
QuadRule lf::quad::make_TriaQR_P3O3 ()
QuadRule lf::quad::make_TriaQR_P7O6 ()
Seven point triangular quadrature rule of order 6.
QuadRule lf::quad::make_TriaQR_P6O4 ()
Six point triangular quadrature rule of order 4.
QuadRule lf::quad::make_QuadQR_MidpointRule ()
midpoint quadrature rule for quadrilaterals
QuadRule lf::quad::make_QuadQR_P1O2 ()
QuadRule lf::quad::make_QuadQR_EdgeMidpointRule ()
edge midpoint quadrature rule for unit square (= reference quad)
QuadRule lf::quad::make_QuadQR_P4O2 ()
QuadRule lf::quad::make_QuadQR_P4O4 ()
Fourth-order tensor product Gauss rule for quadrilaterals.
Function Documentation
make_QuadQR_EdgeMidpointRule()
QuadRule lf::quad::make_QuadQR_EdgeMidpointRule ()
edge midpoint quadrature rule for unit square (= reference quad)
This quadrature rule relies on point evaluations at the midpoints of all edges with equal weights = 1/4 for the unit square.
The rule is exact for bilinear polynomials.
Definition at line 189 of file make_quad_rule.cc.
References lf::base::RefEl::kQuad().
Referenced by lf::quad::make_QuadQR_P4O2().
make_QuadQR_MidpointRule()
QuadRule lf::quad::make_QuadQR_MidpointRule () inline
midpoint quadrature rule for quadrilaterals
This quadrature rule relies on the center of gravity as single quadrature node. It agrees with the lowest-order tensor product Gauss rule
Definition at line 78 of file make_quad_rule.h.
References lf::base::RefEl::kQuad(), and lf::quad::make_QuadRule().
Referenced by lf::quad::make_QuadQR_P1O2().
make_QuadQR_P1O2()
QuadRule lf::quad::make_QuadQR_P1O2 () inline
Definition at line 81 of file make_quad_rule.h.
References lf::quad::make_QuadQR_MidpointRule().
make_QuadQR_P4O2()
QuadRule lf::quad::make_QuadQR_P4O2 () inline
Definition at line 91 of file make_quad_rule.h.
References lf::quad::make_QuadQR_EdgeMidpointRule().
make_QuadQR_P4O4()
QuadRule lf::quad::make_QuadQR_P4O4 () inline
Fourth-order tensor product Gauss rule for quadrilaterals.
Rule uses four interior quadrature nodes and is exact for tensor-product polynomials up to degree 3.
Definition at line 98 of file make_quad_rule.h.
References lf::base::RefEl::kQuad(), and lf::quad::make_QuadRule().
make_TriaQR_EdgeMidpointRule()
QuadRule lf::quad::make_TriaQR_EdgeMidpointRule ()
edge midpoint quadrature rule for reference triangles
This quadrature rule relies on point evaluations at the midpoints of all edges with equal weights = 1/6 for the reference triangle.
The rule is exact for quadratic bi-variate polynomials
Definition at line 170 of file make_quad_rule.cc.
References lf::base::RefEl::kTria().
Referenced by lf::quad::make_TriaQR_P3O3().
make_TriaQR_MidpointRule()
QuadRule lf::quad::make_TriaQR_MidpointRule ()
midpoint quadrature rule for triangles
This quadrature rule relies on the center of gravity as single quadrature node
Definition at line 157 of file make_quad_rule.cc.
References lf::base::RefEl::kTria().
Referenced by lf::quad::make_TriaQR_P1O2().
make_TriaQR_P1O2()
QuadRule lf::quad::make_TriaQR_P1O2 () inline
Definition at line 55 of file make_quad_rule.h.
References lf::quad::make_TriaQR_MidpointRule().
make_TriaQR_P3O3()
QuadRule lf::quad::make_TriaQR_P3O3 () inline
Definition at line 65 of file make_quad_rule.h.
References lf::quad::make_TriaQR_EdgeMidpointRule().
make_TriaQR_P6O4()
QuadRule lf::quad::make_TriaQR_P6O4 ()
Six point triangular quadrature rule of order 4.
Definition at line 211 of file make_quad_rule.cc.
References lf::base::RefEl::kTria().
make_TriaQR_P7O6()
QuadRule lf::quad::make_TriaQR_P7O6 ()
Seven point triangular quadrature rule of order 6.
Definition at line 235 of file make_quad_rule.cc.