LehrFEM++: lf::uscalfe Namespace Reference
lf::uscalfe Namespace Reference
Collects data structures and algorithms designed for scalar finite element methods primarily meant for second-order elliptic boundary value problems.
Classes
class FeLagrangeO1Quad
Linear Lagrange finite element on the quadrilateral reference element.
class FeLagrangeO1Segment
Linear Lagrange finite element on a line segment.
class FeLagrangeO1Tria
Linear Lagrange finite element on triangular reference element.
class FeLagrangeO2Quad
Quadratic Lagrangian finite element on a quadrilateral reference element.
class FeLagrangeO2Segment
Quadratic Lagrangian finite element on a line segment.
class FeLagrangeO2Tria
Quadratic Lagrangian finite element on a triangular reference element.
class FeLagrangeO3Quad
Cubic Lagrangian finite element on a quadrilateral reference element.
class FeLagrangeO3Segment
Cubic Lagrangian finite element on a line segment.
class FeLagrangeO3Tria
Cubic Lagrangian finite elment on a triangular reference element.
class FeLagrangePoint
Linear Lagrange finite element on a point.
class FeSpaceLagrangeO1
(Bi)Linear Lagrangian Finite Element space
class FeSpaceLagrangeO2
Quadratic Lagrangian Finite Element space.
class FeSpaceLagrangeO3
Cubic Lagrangian Finite Element space.
class LinearFELaplaceElementMatrix
Computing the element matrix for the (negative) Laplacian and linear finite elements.
class LinearFELocalLoadVector
Class for computation of local load vector for linear finite elements.
class MassEdgeMatrixProvider
Quadrature-based computation of local mass matrix for an edge.
class MeshFunctionFE
A MeshFunction representing an element from a ScalarUniformFESpace (e.g. solution of BVP)
class MeshFunctionGradFE
A MeshFunction representing the gradient of a function from a finite element space (e.g. gradient of a solution of BVP).
class PrecomputedScalarReferenceFiniteElement
Helper class which stores a ScalarReferenceFiniteElement with precomputed values at the nodes of a quadrature rule.
class ReactionDiffusionElementMatrixProvider
Class for local quadrature based computations for Lagrangian finite elements and second-order scalar elliptic BVPs.
class ScalarLoadEdgeVectorProvider
Local edge contributions to element vector.
class ScalarLoadElementVectorProvider
Local computation of general element (load) vector for scalar finite elements; volume contributions only.
class ScalarReferenceFiniteElement
Interface class for parametric scalar valued finite elements.
class UniformScalarFESpace
Space of scalar valued finite element functions on a hybrid 2D mesh
Typedefs
using gdof_idx_t = lf::assemble::gdof_idx_t
using ldof_idx_t = lf::assemble::ldof_idx_t
using size_type = lf::assemble::size_type
using dim_t = lf::assemble::dim_t
using glb_idx_t = lf::assemble::glb_idx_t
using sub_idx_t = lf::base::sub_idx_t
using quad_rule_collection_t = std::map< lf::base::RefEl, lf::quad::QuadRule >
Auxiliary data structure for passing collections of quadrature rules.
Functions
template<class MF , class QR_SELECTOR , class ENTITY_PREDICATE = base::PredicateTrue>
auto IntegrateMeshFunction (const lf::mesh::Mesh &mesh, const MF &mf, const QR_SELECTOR &qr_selector, const ENTITY_PREDICATE &ep=base::PredicateTrue{}, int codim=0) -> mesh::utils::MeshFunctionReturnType< MF >
Integrate a MeshFunction over a mesh (with quadrature rules)
template<class MF , class ENTITY_PREDICATE = base::PredicateTrue>
auto IntegrateMeshFunction (const lf::mesh::Mesh &mesh, const MF &mf, int quad_degree, const ENTITY_PREDICATE &ep=base::PredicateTrue{}, int codim=0)
Integrate a mesh function over a mesh using quadrature rules of uniform order.
template<typename SCALAR , typename MF , typename SELECTOR = base::PredicateTrue>
auto NodalProjection (const UniformScalarFESpace< SCALAR > &fe_space, MF &&u, SELECTOR &&pred=base::PredicateTrue{})
Computes nodal projection of a mesh function and returns the finite element basis expansion coefficients of the result.
template<typename SCALAR , typename EDGESELECTOR , typename FUNCTION >
std::vector< std::pair< bool, SCALAR > > InitEssentialConditionFromFunction (const lf::assemble::DofHandler &dofh, const ScalarReferenceFiniteElement< SCALAR > &fe_spec_edge, EDGESELECTOR &&esscondflag, FUNCTION &&g)
Initialization of flags/values for dofs of a uniform Lagrangian finite element space whose values are imposed by a specified function.
template<typename LOC_COMP , typename COEFFVECTOR , typename SELECTOR >
double SumCellFEContrib (const lf::assemble::DofHandler &dofh, LOC_COMP &loc_comp, const COEFFVECTOR &uh, SELECTOR &&pred)
Summation of cell values computed based on a finite element function specified through its basis expansion coefficients.
template<typename LOC_COMP , typename COEFFVECTOR >
double SumCellFEContrib (const lf::assemble::DofHandler &dofh, LOC_COMP &loc_comp, const COEFFVECTOR &uh)
Summation of local contributions over all cells.
template<class PTR , class DIFF_COEFF , class REACTION_COEFF >
ReactionDiffusionElementMatrixProvider (PTR fe_space, DIFF_COEFF alpha, REACTION_COEFF gamma) -> ReactionDiffusionElementMatrixProvider< typename PTR::element_type::Scalar, DIFF_COEFF, REACTION_COEFF >
template<class PTR , class DIFF_COEFF , class REACTION_COEFF >
ReactionDiffusionElementMatrixProvider (PTR fe_space, DIFF_COEFF alpha, REACTION_COEFF gamma, std::map< lf::base::RefEl, lf::quad::QuadRule >) -> ReactionDiffusionElementMatrixProvider< typename PTR::element_type::Scalar, DIFF_COEFF, REACTION_COEFF >
template<class PTR , class COEFF , class EDGESELECTOR = base::PredicateTrue>
MassEdgeMatrixProvider (PTR, COEFF coeff, EDGESELECTOR edge_predicate=base::PredicateTrue{}) -> MassEdgeMatrixProvider< typename PTR::element_type::Scalar, COEFF, EDGESELECTOR >
template<class PTR , class MESH_FUNCTION >
ScalarLoadElementVectorProvider (PTR fe_space, MESH_FUNCTION mf) -> ScalarLoadElementVectorProvider< typename PTR::element_type::Scalar, MESH_FUNCTION >
template<class PTR , class FUNCTOR , class EDGESELECTOR = base::PredicateTrue>
ScalarLoadEdgeVectorProvider (PTR, FUNCTOR, EDGESELECTOR=base::PredicateTrue{}) -> ScalarLoadEdgeVectorProvider< typename PTR::element_type::Scalar, FUNCTOR, EDGESELECTOR >
template<class T , class SCALAR_COEFF >
MeshFunctionFE (std::shared_ptr< T >, const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > &) -> MeshFunctionFE< typename T::Scalar, SCALAR_COEFF >
template<class T , class SCALAR_COEFF >
MeshFunctionGradFE (std::shared_ptr< T >, const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > &) -> MeshFunctionGradFE< typename T::Scalar, SCALAR_COEFF >
template<typename SCALAR_COEFF , typename FES_COARSE , typename FES_FINE >
Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > prolongate (const lf::refinement::MeshHierarchy &mh, std::shared_ptr< const FES_COARSE > fespace_coarse, std::shared_ptr< const FES_FINE > fespace_fine, const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > &dofs_coarse, lf::base::size_type level_coarse)
Interpolate a vector of DOFs on a finer mesh.
template<typename SCALAR >
void PrintInfo (std::ostream &o, const UniformScalarFESpace< SCALAR > &fes, unsigned ctrl)
template<typename SCALAR >
std::ostream & operator<< (std::ostream &o, const UniformScalarFESpace< SCALAR > &fes)
Variables
static const unsigned int kout_l2_qr = 1
static const unsigned int kout_l2_rsfvals = 2
std::shared_ptr< spdlog::logger > linear_fe_local_load_vector_logger
Used by LinearFELocalLoadVector to log additional (debug) information during vector assembly.
std::shared_ptr< spdlog::logger > reaction_diffusion_element_matrix_provider_logger
logger for ReactionDiffusionElementMatrixProvider
std::shared_ptr< spdlog::logger > mass_edge_matrix_provider_logger
logger for MassEdgeMatrixProvider
std::shared_ptr< spdlog::logger > scalar_load_element_vector_provider_logger
logger used by ScalarLoadElementVectorProvider
std::shared_ptr< spdlog::logger > scalar_load_edge_vector_provider_logger
logger for ScalarLoadEdgeVectorProvider class template.
const unsigned int kUniformScalarFESpaceOutMesh = 1
mesh information will be printed
const unsigned int kUniformScalarFESpaceOutDofh = 2
information about the dof handler will be printed.
const unsigned int kUniformScalarFESpaceOutRsfs = 4
information about the reference shape functions will be printed
Detailed Description
Collects data structures and algorithms designed for scalar finite element methods primarily meant for second-order elliptic boundary value problems.
This namespace contains a number of classes/functions which can be used to solve boundary value problems with uniform, scalar Finite elements:
Uniform means that the approximation space has uniform order of approximation over the whole mesh. Or in other words: The shape functions of a given approximation space depend only on the underlying reference element of a mesh entity.
Scalar means that the approximation space is always scalar valued, the shape functions are scalar valued.
Examples of approximation spaces that the methods/classes in this namespace can represent/handle are:
n-th order Lagrangian Shape functions
1st order Crouzeix-Raviart approximation space
Broken spaces (e.g. for Discontinuous Galerkin Approximations)
Here are examples of use cases not supported by lf::uscalfe:
Approximation spaces where the polynomial degree depends on the mesh, respectively hierarchic approximation spaces (e.g. for hp-fem)
Non-Scalar valued approximation spaces such as EdgeFunctions/Nedelec elements or Thomas-Raviart elements.
Typedef Documentation
dim_t
using lf::uscalfe::dim_t = typedef lf::assemble::dim_t
Type for (co-)dimensions
Definition at line 29 of file lagr_fe.h.
gdof_idx_t
using lf::uscalfe::gdof_idx_t = typedef lf::assemble::gdof_idx_t
Type for indices into global matrices/vectors
Definition at line 23 of file lagr_fe.h.
glb_idx_t
using lf::uscalfe::glb_idx_t = typedef lf::assemble::glb_idx_t
Type for global index of entities
Definition at line 31 of file lagr_fe.h.
ldof_idx_t
using lf::uscalfe::ldof_idx_t = typedef lf::assemble::ldof_idx_t
Type for indices referring to entity matrices/vectors
Definition at line 25 of file lagr_fe.h.
quad_rule_collection_t
using lf::uscalfe::quad_rule_collection_t = typedef std::map<lf::base::RefEl, lf::quad::QuadRule>
Auxiliary data structure for passing collections of quadrature rules.
This type can be used to pass several quadrature rules to a function, when different quadrature rules for different types of entities are required.
Definition at line 35 of file loc_comp_ellbvp.h.
size_type
using lf::uscalfe::size_type = typedef lf::assemble::size_type
Type for vector length/matrix sizes
Definition at line 27 of file lagr_fe.h.
sub_idx_t
using lf::uscalfe::sub_idx_t = typedef lf::base::sub_idx_t
Type for indexing sub-entities
Definition at line 33 of file lagr_fe.h.
Function Documentation
InitEssentialConditionFromFunction()
template<typename SCALAR , typename EDGESELECTOR , typename FUNCTION > std::vector<std::pair<bool, SCALAR> > lf::uscalfe::InitEssentialConditionFromFunction (const lf::assemble::DofHandler & dofh, const ScalarReferenceFiniteElement< SCALAR > & fe_spec_edge, EDGESELECTOR && esscondflag, FUNCTION && g)
Initialization of flags/values for dofs of a uniform Lagrangian finite element space whose values are imposed by a specified function.
Template Parameters
SCALAR scalar type for BVP = return type of the function g
EDGESELECTOR predicate returning true for edges with fixed dofs
FUNCTION MeshFunction which defines the imposed values on the edges
Parameters
dofh local-to-global index mapping
fe_spec_edge description of arrangement for local shape functions for a kSegment-type entity
esscondflag predicate object whose evaluation operator returns true for all edges whose associated degrees of freedom should be set a fixed value.
Returns
a vector of flag-value pairs, a true first component indicating a fixed dof, with the second component providing the value in this case.
This function interpolates a scalar-valued function into a Lagrangian finite element space restricted to a set of edges. It relies on the method ScalarReferenceFiniteElement::NodalValuesToDofs().
The main use of this function is the interpolation of Dirichlet data on the Dirichlet part of the boundary of a domain.
Template parameter type requirements
SCALAR must be a type like complex<double>
EDGESELECTOR must be compatible with std::function<bool(const Entity &)>
FUNCTION is a scalar valued MeshFunction which is evaluated on edges
This function is meant to supply the information needed for the elimination of Dirichlet boundary conditions by means of the function lf::assemble::FixFlaggedSolutionComponents().
Example
  auto mesh_factory = std::make_unique<mesh::hybrid2d::MeshFactory>(2);
  auto gmsh_reader = io::GmshReader(std::move(mesh_factory), "mesh.msh");
  auto mesh = gmsh_reader.mesh();
  auto fe_space = std::make_shared<FeSpaceLagrangeO1<double>>(mesh);
  // We want to solve the pde
  // - \laplace u = 0
  // u = cos(x)*sin(y) on the boundary
  // 1) Setup a mesh function that represents the prescribed values of u on the
  // boundary
  auto mf_boundary =
      mesh::utils::MeshFunctionGlobal([&](const Eigen::Vector2d& x) {
        return std::cos(x[0]) * std::sin(x[1]);
      });
  // 2) determine the dofs on the boundary and to what value the should be set
  auto boundary_cond = InitEssentialConditionFromFunction(
      fe_space->LocGlobMap(),
      *fe_space->ShapeFunctionLayout(base::RefEl::kSegment()),
      base::PredicateTrue{}, mf_boundary);
  // 3) Assemble the stiffness matrix:
  assemble::COOMatrix<double> lhs(fe_space->LocGlobMap().NumDofs(),
                                  fe_space->LocGlobMap().NumDofs());
  auto mf_one = mesh::utils::MeshFunctionConstant(1.);
  auto mf_zero = mesh::utils::MeshFunctionConstant(0.);
  auto matrix_provider =
      ReactionDiffusionElementMatrixProvider(fe_space, mf_one, mf_zero);
  assemble::AssembleMatrixLocally(0, fe_space->LocGlobMap(),
                                  fe_space->LocGlobMap(), matrix_provider, lhs);
  // 4) Modify the system of equations such that the boundary values are
  // enforced
  Eigen::VectorXd rhs(fe_space->LocGlobMap().NumDofs());
  assemble::FixFlaggedSolutionComponents(
      [&](unsigned int idx) { return boundary_cond[idx]; }, lhs, rhs);
  // 5) solve the problem:
  auto lhs_sparse = lhs.makeSparse();
  Eigen::SimplicialLDLT<decltype(lhs_sparse)> solver;
  solver.compute(lhs_sparse);
  auto x = solver.solve(rhs);
Definition at line 298 of file fe_tools.h.
References lf::mesh::Mesh::Entities(), lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >::EvaluationNodes(), lf::assemble::DofHandler::GlobalDofIndices(), lf::mesh::utils::isMeshFunction, lf::base::RefEl::kSegment(), lf::assemble::DofHandler::Mesh(), lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >::NodalValuesToDofs(), lf::assemble::DofHandler::NumDofs(), lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >::NumEvaluationNodes(), lf::assemble::DofHandler::NumLocalDofs(), lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >::NumRefShapeFunctions(), and lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >::RefEl().
Referenced by projects::dpg::InitEssentialConditionsFromFunctions().
IntegrateMeshFunction() [1/2]
template<class MF , class QR_SELECTOR , class ENTITY_PREDICATE = base::PredicateTrue> auto lf::uscalfe::IntegrateMeshFunction (const lf::mesh::Mesh & mesh, const MF & mf, const QR_SELECTOR & qr_selector, const ENTITY_PREDICATE & ep = base::PredicateTrue{}, int codim = 0) -> mesh::utils::MeshFunctionReturnType<MF>
Integrate a MeshFunction over a mesh (with quadrature rules)
Template Parameters
MF The type of the mesh function.
QR_SELECTOR The type of qr_selector (see below)
ENTITY_PREDICATE The type of the entity predicate (see below)
Parameters
mesh The mesh to integrate over
mf The mesh function to integrate
qr_selector Provides the quadrature rule for every entity of the mesh.
ep Selects the entities over which mf is integrated (default: all entities)
codim The codimension of the entities over which mf is integrated.
Returns
The integrated value
Requirements for QR_SELECTOR
QR_SELECTOR should overload operator() as follows:
quad::QuadRule operator()(const mesh::Entity& e) const
i.e. it should return the quadrature rule for every entity e of the mesh that is to be used for computing the integral of mf over e.
Requirements for ENTITY_PREDICATE
The entity predicate should overload operator() as follows:
bool operator()(const mesh::Entity& e) const
It should return true, if e is part of the integration domain and false if it is not.
Example
  auto mesh_factory = std::make_unique<mesh::hybrid2d::MeshFactory>(2);
  auto gmsh_reader = io::GmshReader(std::move(mesh_factory), "mesh.msh");
  auto mesh = gmsh_reader.mesh();
  // integrate the function sin(x)*cos(y) over the mesh using 5th-degree
  // quadrature rules
  auto mf = mesh::utils::MeshFunctionGlobal(
      [](const Eigen::Vector2d& x) { return std::sin(x[0]) * std::cos(x[1]); });
  // select the quadrature rule explicitly for every element:
  auto integral = IntegrateMeshFunction(*mesh, mf, [](const mesh::Entity& e) {
    return quad::make_QuadRule(e.RefEl(), 5);
  });
Definition at line 108 of file fe_tools.h.
Referenced by projects::ipdg_stokes::post_processing::DGnorm(), projects::ipdg_stokes::post_processing::L2norm(), projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
IntegrateMeshFunction() [2/2]
template<class MF , class ENTITY_PREDICATE = base::PredicateTrue> auto lf::uscalfe::IntegrateMeshFunction (const lf::mesh::Mesh & mesh, const MF & mf, int quad_degree, const ENTITY_PREDICATE & ep = base::PredicateTrue{}, int codim = 0)
Integrate a mesh function over a mesh using quadrature rules of uniform order.
Template Parameters
MF type of mesh function to integrate
ENTITY_PREDICATE type of entity predicate (see below)
Parameters
mesh The mesh over which mf is integrated.
mf The mesh function which is integrated
quad_degree The quadrature degree of the quadrature rules that are to be used for integration. Internally Gauss-rules created by quad::make_QuadRule are used.
ep The entity predicate selecting the entities over which mf is integrated.
codim The codimension of the entities over which mf is integrated.
Returns
mf integrated over the entities e of mf where ep(e)==true.
Requirements for ENTITY_PREDICATE
The entity predicate should overload operator() as follows:
bool operator()(const mesh::Entity& e) const
It should return true, if e is part of the integration domain and false if it is not.
Example
  auto mesh_factory = std::make_unique<mesh::hybrid2d::MeshFactory>(2);
  auto gmsh_reader = io::GmshReader(std::move(mesh_factory), "mesh.msh");
  auto mesh = gmsh_reader.mesh();
  // integrate the function sin(x)*cos(y) over the mesh using 5th-degree
  // quadrature rules
  auto mf = mesh::utils::MeshFunctionGlobal(
      [](const Eigen::Vector2d& x) { return std::sin(x[0]) * std::cos(x[1]); });
  auto integral = IntegrateMeshFunction(*mesh, mf, 5);
Definition at line 154 of file fe_tools.h.
MassEdgeMatrixProvider()
template<class PTR , class COEFF , class EDGESELECTOR = base::PredicateTrue> lf::uscalfe::MassEdgeMatrixProvider (PTR , COEFF coeff, EDGESELECTOR edge_predicate = base::PredicateTrue{}) -> MassEdgeMatrixProvider< typename PTR::element_type::Scalar, COEFF, EDGESELECTOR >
MeshFunctionFE()
template<class T , class SCALAR_COEFF > lf::uscalfe::MeshFunctionFE (std::shared_ptr< T > , const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > &) -> MeshFunctionFE< typename T::Scalar, SCALAR_COEFF >
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
MeshFunctionGradFE()
template<class T , class SCALAR_COEFF > lf::uscalfe::MeshFunctionGradFE (std::shared_ptr< T > , const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > &) -> MeshFunctionGradFE< typename T::Scalar, SCALAR_COEFF >
Referenced by projects::dpg::test::TestConververgencePrimalDPGAdaptedNormConvectionDiffusionDirichletBVP(), and projects::dpg::test::TestConververgencePrimalDPGConvectionDiffusionDirichletBVP().
NodalProjection()
template<typename SCALAR , typename MF , typename SELECTOR = base::PredicateTrue> auto lf::uscalfe::NodalProjection (const UniformScalarFESpace< SCALAR > & fe_space, MF && u, SELECTOR && pred = base::PredicateTrue{})
Computes nodal projection of a mesh function and returns the finite element basis expansion coefficients of the result.
Template Parameters
SCALAR a scalar type
MF a MeshFunction representing the scalar valued function that should be projected
SELECTOR predicate type for selecting cells to be visited
Parameters
fe_space a uniform Lagrangian finite element space, providing finite element specifications for the cells of the mesh
u functor object supplying a scalar-valued function that is to be projected
pred predicate object for the selection of relevant cells
Returns
column vector of basis expansion coefficients for the resulting finite element function
The implementation relies on the method ScalarReferenceFiniteElement::NodalValuesToDofs(). Refer to its documentation. This method is called for each active cell to set the coefficients for the global shape functions associated with that cell.
Example
  auto mesh_factory = std::make_unique<mesh::hybrid2d::MeshFactory>(2);
  auto gmsh_reader = io::GmshReader(std::move(mesh_factory), "mesh.msh");
  auto mesh = gmsh_reader.mesh();
  // project a first-degree polynomial onto a first order lagrange space and
  // make sure the representation is exact:
  auto fe_space = std::make_shared<FeSpaceLagrangeO1<double>>(mesh);
  auto mf_linear = mesh::utils::MeshFunctionGlobal(
      [](const Eigen::Vector2d& x) { return 2 + 3 * x[0] + 4 * x[1]; });
  auto dof_vector = NodalProjection(*fe_space, mf_linear);
  auto mf_fe = MeshFunctionFE(fe_space, dof_vector);
  assert(IntegrateMeshFunction(*mesh, squaredNorm(mf_fe - mf_linear), 2) <
         1e-12);
Definition at line 196 of file fe_tools.h.
Referenced by prolongate().
operator<<()
template<typename SCALAR > std::ostream& lf::uscalfe::operator<< (std::ostream & o, const UniformScalarFESpace< SCALAR > & fes) related
output operator for scalar parametric finite element space
Definition at line 413 of file uniform_scalar_fe_space.h.
References lf::uscalfe::UniformScalarFESpace< SCALAR >::PrintInfo().
PrintInfo()
template<typename SCALAR > void lf::uscalfe::PrintInfo (std::ostream & o, const UniformScalarFESpace< SCALAR > & fes, unsigned ctrl)
Definition at line 388 of file uniform_scalar_fe_space.h.
References lf::base::RefEl::kPoint(), lf::base::RefEl::kQuad(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), kUniformScalarFESpaceOutDofh, kUniformScalarFESpaceOutMesh, kUniformScalarFESpaceOutRsfs, lf::uscalfe::UniformScalarFESpace< SCALAR >::LocGlobMap(), lf::uscalfe::UniformScalarFESpace< SCALAR >::Mesh(), lf::assemble::DofHandler::NumDofs(), and lf::uscalfe::UniformScalarFESpace< SCALAR >::NumRefShapeFunctions().
Referenced by lf::uscalfe::ScalarReferenceFiniteElement< SCALAR >::operator<<().
prolongate()
template<typename SCALAR_COEFF , typename FES_COARSE , typename FES_FINE > Eigen::Matrix<SCALAR_COEFF, Eigen::Dynamic, 1> lf::uscalfe::prolongate (const lf::refinement::MeshHierarchy & mh, std::shared_ptr< const FES_COARSE > fespace_coarse, std::shared_ptr< const FES_FINE > fespace_fine, const Eigen::Matrix< SCALAR_COEFF, Eigen::Dynamic, 1 > & dofs_coarse, lf::base::size_type level_coarse)
Interpolate a vector of DOFs on a finer mesh.
Template Parameters
SCALAR_COEFF The scalar of the coefficient vector
FES_COARSE The FE space on the coarse mesh
FES_FINE The FE space on the fine mesh
Parameters
mh A reference to the MeshHierarchy containing the underlying meshes
fespace_coarse The FE space on the coarse mesh
fespace_fine The FE space on the fine mesh
dofs_coarse A basis function coefficient vector on the coarse mesh
level_coarse The level of the coarse mesh
Returns
An interpolated vector of basis function coefficients on the fine mesh
Definition at line 26 of file prolongation.h.
References NodalProjection(), lf::assemble::DofHandler::NumDofs(), and lf::refinement::MeshHierarchy::NumLevels().
ReactionDiffusionElementMatrixProvider() [1/2]
template<class PTR , class DIFF_COEFF , class REACTION_COEFF > lf::uscalfe::ReactionDiffusionElementMatrixProvider (PTR fe_space, DIFF_COEFF alpha, REACTION_COEFF gamma) -> ReactionDiffusionElementMatrixProvider< typename PTR::element_type::Scalar, DIFF_COEFF, REACTION_COEFF >
ReactionDiffusionElementMatrixProvider() [2/2]
template<class PTR , class DIFF_COEFF , class REACTION_COEFF > lf::uscalfe::ReactionDiffusionElementMatrixProvider (PTR fe_space, DIFF_COEFF alpha, REACTION_COEFF gamma, std::map< lf::base::RefEl, lf::quad::QuadRule >) -> ReactionDiffusionElementMatrixProvider< typename PTR::element_type::Scalar, DIFF_COEFF, REACTION_COEFF >
ScalarLoadEdgeVectorProvider()
template<class PTR , class FUNCTOR , class EDGESELECTOR = base::PredicateTrue> lf::uscalfe::ScalarLoadEdgeVectorProvider (PTR , FUNCTOR , EDGESELECTOR = base::PredicateTrue{}) -> ScalarLoadEdgeVectorProvider< typename PTR::element_type::Scalar, FUNCTOR, EDGESELECTOR >
ScalarLoadElementVectorProvider()
template<class PTR , class MESH_FUNCTION > lf::uscalfe::ScalarLoadElementVectorProvider (PTR fe_space, MESH_FUNCTION mf) -> ScalarLoadElementVectorProvider< typename PTR::element_type::Scalar, MESH_FUNCTION >
SumCellFEContrib() [1/2]
template<typename LOC_COMP , typename COEFFVECTOR > double lf::uscalfe::SumCellFEContrib (const lf::assemble::DofHandler & dofh, LOC_COMP & loc_comp, const COEFFVECTOR & uh)
Summation of local contributions over all cells.
See also
SumCellFEContrib()
Definition at line 428 of file fe_tools.h.
References SumCellFEContrib().
SumCellFEContrib() [2/2]
template<typename LOC_COMP , typename COEFFVECTOR , typename SELECTOR > double lf::uscalfe::SumCellFEContrib (const lf::assemble::DofHandler & dofh, LOC_COMP & loc_comp, const COEFFVECTOR & uh, SELECTOR && pred)
Summation of cell values computed based on a finite element function specified through its basis expansion coefficients.
Template Parameters
LOC_COMP type taking care of local computations
COEFFVECTOR a vanilla vector type
SELECTOR a predicate for selecting cells
type requirements
The type LOC_COMP must feature an isActive() method for the selection of cells to be visited, must provide a type dofvector_t for passing coefficients of local shape functions and a method
double operator ()(const lf::mesh::Entity &cell, const DOFVECTOR &dofs);
that performs the local computations.
The type COEFFVECTOR must provide component access through [], a size() method telling the vector length, and value_type typedef telling the component type.
The type functor must provide an evaluation operator () taking a point coordinate vector Eigen::Vector2d as an argument.
Parameters
dofh Local-to-global index mapping belonging to a finite element space
loc_comp reference to helper object for local computations This object must be aware of the shape functions!
uh coefficient vector of finite element function
loop over cells (= codim-0 entities)
Definition at line 388 of file fe_tools.h.
References lf::mesh::Mesh::Entities(), lf::assemble::DofHandler::GlobalDofIndices(), lf::assemble::DofHandler::Mesh(), lf::assemble::DofHandler::NumDofs(), and lf::assemble::DofHandler::NumLocalDofs().
Referenced by SumCellFEContrib().
Variable Documentation
kout_l2_qr
const unsigned int lf::uscalfe::kout_l2_qr = 1 static
Definition at line 25 of file fe_tools.h.
kout_l2_rsfvals
const unsigned int lf::uscalfe::kout_l2_rsfvals = 2 static
Definition at line 26 of file fe_tools.h.
kUniformScalarFESpaceOutDofh
const unsigned int lf::uscalfe::kUniformScalarFESpaceOutDofh = 2
information about the dof handler will be printed.
To be used with PrintInfo(std::ostream&, const UniformScalarFESpace<SCALAR>&, unsigned int)
Definition at line 185 of file uniform_scalar_fe_space.h.
Referenced by PrintInfo().
kUniformScalarFESpaceOutMesh
const unsigned int lf::uscalfe::kUniformScalarFESpaceOutMesh = 1
mesh information will be printed
Output control variables for PrintInfo: To be used with PrintInfo(std::ostream&, const UniformScalarFESpace<SCALAR>&, unsigned int)
Definition at line 177 of file uniform_scalar_fe_space.h.
Referenced by PrintInfo().
kUniformScalarFESpaceOutRsfs
const unsigned int lf::uscalfe::kUniformScalarFESpaceOutRsfs = 4
information about the reference shape functions will be printed
To be used with PrintInfo(std::ostream&, const UniformScalarFESpace<SCALAR>&, unsigned int)
Definition at line 193 of file uniform_scalar_fe_space.h.
Referenced by PrintInfo().
linear_fe_local_load_vector_logger
std::shared_ptr< spdlog::logger > lf::uscalfe::linear_fe_local_load_vector_logger
Initial value:
=
    base::InitLogger("lf::uscalfe::linear_fe_local_load_vector_logger")
Used by LinearFELocalLoadVector to log additional (debug) information during vector assembly.
Definition at line 162 of file lin_fe.cc.
Referenced by lf::uscalfe::LinearFELocalLoadVector< SCALAR, FUNCTOR >::Eval().
mass_edge_matrix_provider_logger
std::shared_ptr< spdlog::logger > lf::uscalfe::mass_edge_matrix_provider_logger
Initial value:
=
    base::InitLogger("lf::uscalfe::mass_edge_matrix_provider_logger")
logger for MassEdgeMatrixProvider
Definition at line 24 of file loc_comp_ellbvp.cc.
reaction_diffusion_element_matrix_provider_logger
std::shared_ptr< spdlog::logger > lf::uscalfe::reaction_diffusion_element_matrix_provider_logger
Initial value:
= base::InitLogger(
        "lf::uscalfe::reaction_diffusion_element_matrix_provider_logger")
logger for ReactionDiffusionElementMatrixProvider
Definition at line 21 of file loc_comp_ellbvp.cc.
scalar_load_edge_vector_provider_logger
std::shared_ptr< spdlog::logger > lf::uscalfe::scalar_load_edge_vector_provider_logger
Initial value:
=
    base::InitLogger("scalar_load_edge_vector_provider_logger")
logger for ScalarLoadEdgeVectorProvider class template.
Definition at line 30 of file loc_comp_ellbvp.cc.
scalar_load_element_vector_provider_logger
std::shared_ptr< spdlog::logger > lf::uscalfe::scalar_load_element_vector_provider_logger
Initial value:
=
    base::InitLogger("lf::uscalfe::scalar_load_element_vector_provider_logger")
logger used by ScalarLoadElementVectorProvider
Definition at line 27 of file loc_comp_ellbvp.cc.