LehrFEM++: lf::fe::FeHierarchicSegment< SCALAR > Class Template Reference
lf::fe::FeHierarchicSegment< SCALAR > Class Template Reference final
Hierarchic Finite Elements of arbitrary degree on segments.
#include <lf/fe/fe.h>
Public Member Functions
FeHierarchicSegment (const FeHierarchicSegment &)=default
FeHierarchicSegment (FeHierarchicSegment &&) noexcept=default
FeHierarchicSegment & operator= (const FeHierarchicSegment &)=default
FeHierarchicSegment & operator= (FeHierarchicSegment &&) noexcept=default
~FeHierarchicSegment () override=default
FeHierarchicSegment (unsigned degree, const quad::QuadRuleCache &qr_cache)
lf::base::RefEl RefEl () const override
Tells the type of reference cell underlying the parametric finite element.
unsigned Degree () const override
Request the maximal polynomial degree of the basis functions in this finite element.
lf::base::size_type NumRefShapeFunctions () const override
The local shape functions.
lf::base::size_type NumRefShapeFunctions (dim_t codim) const override
One shape function for each vertex, p-1 shape functions for the segment.
lf::base::size_type NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const override
One shape function for each vertex, p-1 shape functions for the segment.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > EvalReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Evaluation of all reference shape functions in a number of points.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > GradientsReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Computation of the gradients of all reference shape functions in a number of points.
Eigen::MatrixXd EvaluationNodes () const override
Evaluation nodes are the endpoints of the segment and the Chebyshev nodes of degree p-1 on the segment.
lf::base::size_type NumEvaluationNodes () const override
Tell the number of evaluation (interpolation) nodes.
Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > NodalValuesToDofs (const Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > &nodevals) const override
Maps function evaluations to basis function coefficients.
Public Member Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
virtual ~ScalarReferenceFiniteElement ()=default
virtual base::RefEl RefEl () const =0
Tells the type of reference cell underlying the parametric finite element.
virtual unsigned int Degree () const =0
Request the maximal polynomial degree of the basis functions in this finite element.
dim_t Dimension () const
Returns the spatial dimension of the reference cell.
virtual size_type NumRefShapeFunctions () const
Total number of reference shape functions associated with the reference cell.
virtual size_type NumRefShapeFunctions (dim_t codim) const
The number of interior reference shape functions for sub-entities of a particular co-dimension.
virtual size_type NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const =0
The number of interior reference shape functions for every sub-entity.
virtual Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > EvalReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const =0
Evaluation of all reference shape functions in a number of points.
virtual Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > GradientsReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const =0
Computation of the gradients of all reference shape functions in a number of points.
virtual Eigen::MatrixXd EvaluationNodes () const =0
Returns reference coordinates of "evaluation nodes" for evaluation of parametric degrees of freedom, nodal interpolation in the simplest case.
virtual size_type NumEvaluationNodes () const =0
Tell the number of evaluation (interpolation) nodes.
virtual Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > NodalValuesToDofs (const Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > &nodvals) const
Computes the linear combination of reference shape functions matching function values at evaluation nodes.
Private Attributes
unsigned degree_
const lf::quad::QuadRule * qr_dual_
Additional Inherited Members
Public Types inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
using Scalar = SCALAR
The underlying scalar type.
Protected Member Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
ScalarReferenceFiniteElement ()=default
ScalarReferenceFiniteElement (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement (ScalarReferenceFiniteElement &&) noexcept=default
ScalarReferenceFiniteElement & operator= (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement & operator= (ScalarReferenceFiniteElement &&) noexcept=default
Related Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
template<class SCALAR >
void PrintInfo (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &srfe, unsigned int ctrl=0)
Print information about a ScalarReferenceFiniteElement to the given stream.
template<typename SCALAR >
std::ostream & operator<< (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &fe_desc)
Stream output operator: just calls the ScalarReferenceFiniteElement::print() method.
Detailed Description
template<typename SCALAR>
class lf::fe::FeHierarchicSegment< SCALAR >
Hierarchic Finite Elements of arbitrary degree on segments.
The shape functions associated with the vertices are given by
\[ \begin{align*} \widehat{b^\cdot}^1(\widehat{x}) &= 1 - \widehat{x} \\ \widehat{b^\cdot}^2(\widehat{x}) &= \widehat{x} \end{align*} \]
and the interior basis functions associated with the segment itself are given by the integrated shifted Legendre polynomials
\[ \widehat{b^-}^i(\widehat{x}) = L_i(\widehat{x}) = \int_0^{\widehat{x}}\! *P_{i-1}(\xi) \,\mathrm{d}\xi \quad\mbox{ for }\quad i= 2, \cdots, p \]
where \(P_i : [0, 1] \to \mathbb{R}\) is the shifted Legendre polynomial of degree \(i\).
To compute the basis function coefficients from point evaluations of a function, we make use of the dual basis given by
\[ \lambda_i^-[f] = *\begin{cases} f(0) &\mbox{ for } i = 0 \\ f(1) &\mbox{ for } i = 1 \\ \frac{1}{2i - 1} \left [P_{i-1}(1)f(1) - P_{i-1}(0)f(0) - \int_0^1\! *P_{i-1}'(x)f(x) \,\mathrm{d}x \right] &\mbox{ for } i \geq 2 \end{cases} \]
Attention
Note that the local coordinate \(\widehat{x}\) may be flipped by applying an affine transformation \(\widehat{x} \mapsto 1 - \widehat{x}\). This must be done if the relative orientation of the edge is lf::mesh::Orientation::negative in order to keep a global ordering of DOFs on the cell interfaces.
Note
The Shape Functions are taken from the following paper: https://arxiv.org/pdf/1504.03025.pdf
See also
ScalarReferenceFiniteElement
Definition at line 222 of file hierarchic_fe.h.
Constructor & Destructor Documentation
FeHierarchicSegment() [1/3]
template<typename SCALAR > lf::fe::FeHierarchicSegment< SCALAR >::FeHierarchicSegment (const FeHierarchicSegment< SCALAR > &) default
FeHierarchicSegment() [2/3]
template<typename SCALAR > lf::fe::FeHierarchicSegment< SCALAR >::FeHierarchicSegment (FeHierarchicSegment< SCALAR > &&) default noexcept
~FeHierarchicSegment()
template<typename SCALAR > lf::fe::FeHierarchicSegment< SCALAR >::~FeHierarchicSegment () override default
FeHierarchicSegment() [3/3]
template<typename SCALAR > lf::fe::FeHierarchicSegment< SCALAR >::FeHierarchicSegment (unsigned degree, const quad::QuadRuleCache & qr_cache) inline
Definition at line 230 of file hierarchic_fe.h.
Member Function Documentation
Degree()
template<typename SCALAR > unsigned lf::fe::FeHierarchicSegment< SCALAR >::Degree () const inline override virtual
Request the maximal polynomial degree of the basis functions in this finite element.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 239 of file hierarchic_fe.h.
References lf::fe::FeHierarchicSegment< SCALAR >::degree_.
EvalReferenceShapeFunctions()
template<typename SCALAR > Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > lf::fe::FeHierarchicSegment< SCALAR >::EvalReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline override virtual
Evaluation of all reference shape functions in a number of points.
Parameters
refcoords coordinates of N points in the reference cell passed as columns of a matrix of size dim x N, where dim is the dimension of the reference element, that is =0 for points, =1 for edges, =2 for triangles and quadrilaterals
Returns
An Eigen Matrix of size NumRefShapeFunctions() x refcoords.cols() which contains the shape functions evaluated at every quadrature point.
Concerning the numbering of local shape functions, please consult the documentation of lf::assemble::DofHandler or the documentation of the class.
Note
shape functions are assumed to be real-valued.
Example: Triangular Linear Lagrangian finite elements
There are three reference shape functions \(\hat{b}^1,\hat{b}^2,\hat{b}^3\) associated with the vertices of the reference triangle. Let us assume that the refcoords argument is a 2x2 matrix \([\mathbf{x}_1\;\mathbf{x}_2]\), which corresponds to passing the coordinates of two points in the reference triangle. Then this method will return a 3x2 matrix:
\[ \begin{pmatrix}\hat{b}^1(\mathbf{x}_1) & \hat{b}^1(\mathbf{x}_2) \\ \hat{b}^2(\mathbf{x}_1) & \hat{b}^2(\mathbf{x}_2) \\ \hat{b}^3(\mathbf{x}_1)\ & \hat{b}^3(\mathbf{x}_2) \end{pmatrix} \]
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 275 of file hierarchic_fe.h.
References lf::fe::FeHierarchicSegment< SCALAR >::degree_, lf::fe::ilegendre(), and lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions().
EvaluationNodes()
template<typename SCALAR > Eigen::MatrixXd lf::fe::FeHierarchicSegment< SCALAR >::EvaluationNodes () const inline override virtual
Evaluation nodes are the endpoints of the segment and the Chebyshev nodes of degree p-1 on the segment.
Returns reference coordinates of "evaluation nodes" for evaluation of parametric degrees of freedom, nodal interpolation in the simplest case.
Returns
A d x N matrix, where d is the dimension of the reference cell, and N the number of interpolation nodes. The columns of this matrix contain their reference coordinates.
Every parametric scalar finite element implicitly defines a local interpolation operator by duality with the reference shape functions. This interpolation operator can be realized through evaluations at certain evaluation nodes, which are provided by this method.
Unisolvence
The evaluation points must satisfy the following requirement: If the values of a function belonging to the span of the reference shape functions are known in the evaluation nodes, then this function is uniquely determined. This entails that the number of evaluation nodes must be at least as big as the number of reference shape functions.
Note
It is not required that any vector a values at evaluation nodes can be produced by a suitable linear combination of reference shape functions. For instance, this will not be possible, if there are more evaluation points than reference shape functions. If both sets have the same size, however, the interpolation problem has a solution for any vector of values at the evluation points.
Example: Principal lattice
For triangular Lagrangian finite elements of degree p the evaluation nodes, usually called "interpolation nodes" in this context, can be chosen as \(\left(\frac{j}{p},\frac{k}{p}\right),\; 0\leq j,k \leq p, j+k\leq p\).
Moment-based degrees of freedom
For some finite element spaces the interpolation functional may be defined based on integrals over edges. In this case the evaluation nodes will be quadrature nodes for the approximate evaluation of these integrals.
The quadrature rule must be exact for the polynomials contained in the local finite element spaces.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 315 of file hierarchic_fe.h.
References lf::fe::FeHierarchicSegment< SCALAR >::NumEvaluationNodes(), lf::quad::QuadRule::NumPoints(), lf::quad::QuadRule::Points(), and lf::fe::FeHierarchicSegment< SCALAR >::qr_dual_.
GradientsReferenceShapeFunctions()
template<typename SCALAR > Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > lf::fe::FeHierarchicSegment< SCALAR >::GradientsReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline override virtual
Computation of the gradients of all reference shape functions in a number of points.
Parameters
refcoords coordinates of N points in the reference cell passed as columns of a matrix of size dim x N.
Returns
An Eigen Matrix of size NumRefShapeFunctions() x (dim * refcoords.cols()) where dim is the dimension of the reference finite element. The gradients are returned in chunks of rows of this matrix.
Concerning the numbering of local shape functions, please consult the documentation of lf::assemble::DofHandler.
Example: Triangular Linear Lagrangian finite elements
There are three reference shape functions \(\hat{b}^1,\hat{b}^2,\hat{b}^3\) associated with the vertices of the reference triangle. Let us assume that the refcoords argument is a 2x2 matrix \([\mathbf{x}_1\;\mathbf{x}_2]\), which corresponds to passing the coordinates of two points in the reference triangle. Then this method will return a 3x4 matrix:
\[ \begin{pmatrix} \grad^T\hat{b}^1(\mathbf{x}_1) & \grad^T\hat{b}^1(\mathbf{x}_2) \\ \grad^T\hat{b}^2(\mathbf{x}_1) & \grad^T\hat{b}^2(\mathbf{x}_2) \\ \grad^T\hat{b}^3(\mathbf{x}_1) & \grad^T\hat{b}^3(\mathbf{x}_2) \end{pmatrix} \]
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 292 of file hierarchic_fe.h.
References lf::fe::FeHierarchicSegment< SCALAR >::degree_, lf::fe::ilegendre_dx(), and lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions().
NodalValuesToDofs()
template<typename SCALAR > Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > lf::fe::FeHierarchicSegment< SCALAR >::NodalValuesToDofs (const Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > & nodevals) const inline override virtual
Maps function evaluations to basis function coefficients.
Parameters
nodevals The value of the function at the evaluation nodes
This function computes the basis function coefficients using the dual basis of the basis functions on the segment. It is given by
\[ \lambda_i^-[f] = \begin{cases} f(0) &\mbox{ for } i = 0 \\ f(1) &\mbox{ for } i = 1 \\ \frac{1}{2i - 1} \left [P_{i-1}(1)f(1) - P_{i-1}(0)f(0) - \int_0^1\! *P_{i-1}'(x)f(x) \,\mathrm{d}x \right] &\mbox{ for } i \geq 2 \end{cases} \]
Reimplemented from lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 345 of file hierarchic_fe.h.
References lf::fe::ilegendre_dx(), lf::fe::legendre_dx(), lf::quad::QuadRule::NumPoints(), lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions(), lf::quad::QuadRule::Points(), lf::fe::FeHierarchicSegment< SCALAR >::qr_dual_, and lf::quad::QuadRule::Weights().
NumEvaluationNodes()
template<typename SCALAR > lf::base::size_type lf::fe::FeHierarchicSegment< SCALAR >::NumEvaluationNodes () const inline override virtual
Tell the number of evaluation (interpolation) nodes.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 328 of file hierarchic_fe.h.
References lf::quad::QuadRule::NumPoints(), and lf::fe::FeHierarchicSegment< SCALAR >::qr_dual_.
Referenced by lf::fe::FeHierarchicSegment< SCALAR >::EvaluationNodes().
NumRefShapeFunctions() [1/3]
template<typename SCALAR > lf::base::size_type lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions () const inline override virtual
The local shape functions.
Total number of reference shape functions associated with the reference cell.
Note
the total number of shape functions is the sum of the number of interior shape functions for all sub-entities and the entity itself.
Reimplemented from lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 245 of file hierarchic_fe.h.
References lf::fe::FeHierarchicSegment< SCALAR >::degree_.
Referenced by lf::fe::FeHierarchicSegment< SCALAR >::EvalReferenceShapeFunctions(), lf::fe::FeHierarchicSegment< SCALAR >::GradientsReferenceShapeFunctions(), lf::fe::FeHierarchicSegment< SCALAR >::NodalValuesToDofs(), and lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions().
NumRefShapeFunctions() [2/3]
template<typename SCALAR > lf::base::size_type lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions (dim_t codim) const inline override virtual
One shape function for each vertex, p-1 shape functions for the segment.
The number of interior reference shape functions for sub-entities of a particular co-dimension.
Parameters
codim co-dimension of the subentity
Returns
number of interior reference shape function belonging to the specified sub-entity.
Note
this method will throw an exception when different numbers of reference shape functions are assigned to different sub-entities of the same co-dimension
Reimplemented from lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 254 of file hierarchic_fe.h.
References lf::fe::FeHierarchicSegment< SCALAR >::degree_.
NumRefShapeFunctions() [3/3]
template<typename SCALAR > lf::base::size_type lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const inline override virtual
One shape function for each vertex, p-1 shape functions for the segment.
The number of interior reference shape functions for every sub-entity.
Parameters
codim do-dimension of the subentity
subidx local index of the sub-entity
Returns
number of interior reference shape function belonging to the specified sub-entity.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 267 of file hierarchic_fe.h.
References lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions().
operator=() [1/2]
template<typename SCALAR > FeHierarchicSegment & lf::fe::FeHierarchicSegment< SCALAR >::operator= (const FeHierarchicSegment< SCALAR > &) default
operator=() [2/2]
template<typename SCALAR > FeHierarchicSegment & lf::fe::FeHierarchicSegment< SCALAR >::operator= (FeHierarchicSegment< SCALAR > &&) default noexcept
RefEl()
template<typename SCALAR > lf::base::RefEl lf::fe::FeHierarchicSegment< SCALAR >::RefEl () const inline override virtual
Tells the type of reference cell underlying the parametric finite element.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 235 of file hierarchic_fe.h.
References lf::base::RefEl::kSegment().
Member Data Documentation
degree_
template<typename SCALAR > unsigned lf::fe::FeHierarchicSegment< SCALAR >::degree_ private
Definition at line 370 of file hierarchic_fe.h.
Referenced by lf::fe::FeHierarchicSegment< SCALAR >::Degree(), lf::fe::FeHierarchicSegment< SCALAR >::EvalReferenceShapeFunctions(), lf::fe::FeHierarchicSegment< SCALAR >::GradientsReferenceShapeFunctions(), and lf::fe::FeHierarchicSegment< SCALAR >::NumRefShapeFunctions().
qr_dual_
template<typename SCALAR > const lf::quad::QuadRule* lf::fe::FeHierarchicSegment< SCALAR >::qr_dual_ private
Definition at line 371 of file hierarchic_fe.h.
Referenced by lf::fe::FeHierarchicSegment< SCALAR >::EvaluationNodes(), lf::fe::FeHierarchicSegment< SCALAR >::NodalValuesToDofs(), and lf::fe::FeHierarchicSegment< SCALAR >::NumEvaluationNodes().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/lib/lf/fe/hierarchic_fe.h