LehrFEM++: projects::hldo_sphere::mesh::SphereTriagMeshBuilder Class Reference
projects::hldo_sphere::mesh::SphereTriagMeshBuilder Class Reference
A mesh builder for regular 3-Sphere.
#include <sphere_triag_mesh_builder.h>
Public Member Functions
SphereTriagMeshBuilder (std::unique_ptr< lf::mesh::MeshFactory > mesh_factory)
Constructor.
void setRadius (double r)
Sets the radius.
void setRefinementLevel (lf::base::size_type n)
Set the refinement level.
std::shared_ptr< lf::mesh::Mesh > Build ()
Build the mesh.
Private Attributes
double radius_
lf::base::size_type refinement_level_
std::unique_ptr< lf::mesh::MeshFactory > mesh_factory_
Detailed Description
A mesh builder for regular 3-Sphere.
The radius of the Sphere is controlled by setRadius(). The refinement level can be set with setRefinementLevel(). The refinement level indicates how fine the mesh should be inital structure (octahedron, see https://de.wikipedia.org/wiki/Octahedron) The radius defaults to 1.0 while refinement level defaults to 0.
Definition at line 29 of file sphere_triag_mesh_builder.h.
Constructor & Destructor Documentation
SphereTriagMeshBuilder()
projects::hldo_sphere::mesh::SphereTriagMeshBuilder::SphereTriagMeshBuilder (std::unique_ptr< lf::mesh::MeshFactory > mesh_factory) inline explicit
Constructor.
Parameters
mesh_factory A unique pointer to a mesh factory object used for the assembly of the mesh
Definition at line 36 of file sphere_triag_mesh_builder.h.
Member Function Documentation
Build()
std::shared_ptr< lf::mesh::Mesh > projects::hldo_sphere::mesh::SphereTriagMeshBuilder::Build ()
Build the mesh.
Returns
A shared pointer to a mesh in the form of a sphere. The radius is set with setRadius(r) and the refinement level is set with setRefinementLevel(n).
Definition at line 13 of file sphere_triag_mesh_builder.cc.
References lf::base::RefEl::kTria(), mesh_factory_, radius_, and refinement_level_.
Referenced by projects::hldo_sphere::examples::DiracOperatorExample::Compute(), and projects::hldo_sphere::examples::HodgeLaplacianExample::Compute().
setRadius()
void projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRadius (double r) inline
Sets the radius.
Parameters
r The radius of the sphere
requries r > 0
Definition at line 50 of file sphere_triag_mesh_builder.h.
References radius_.
Referenced by projects::hldo_sphere::examples::DiracOperatorExample::Compute(), and projects::hldo_sphere::examples::HodgeLaplacianExample::Compute().
setRefinementLevel()
void projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel (lf::base::size_type n) inline
Set the refinement level.
Parameters
n The nummber of refinements
The refinement level indicates by how fine the mesh should become. Inital structure (octahedron, see https://en.wikipedia.org/wiki/Octahedron) on which new vertices are introduced for every refinement level.
For refinement level l the mesh will have \(8\cdot 4^l \) cells, \(12 \cdot 2^l + 24 \cdot (2^{2\, l - 1} - 2^{l -1}) \) edges and \(14 + 12 \cdot (2^l - 1) + 6 \cdot 2^{2\, l -1} - 18 \cdot 2^{l -1} \) vertices.
Definition at line 79 of file sphere_triag_mesh_builder.h.
References refinement_level_.
Referenced by projects::hldo_sphere::examples::DiracOperatorExample::Compute(), projects::hldo_sphere::examples::HodgeLaplacianExample::Compute(), projects::hldo_sphere::discretization::DiracOperator::DiracOperator(), projects::hldo_sphere::discretization::DiracOperatorSourceProblem::DiracOperatorSourceProblem(), projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::HodgeLaplaciansSourceProblems(), projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::WhitneyOneHodgeLaplace(), and projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::WhitneyZeroHodgeLaplace().
Member Data Documentation
mesh_factory_
std::unique_ptr<lf::mesh::MeshFactory> projects::hldo_sphere::mesh::SphereTriagMeshBuilder::mesh_factory_ private
Definition at line 92 of file sphere_triag_mesh_builder.h.
Referenced by Build().
radius_
double projects::hldo_sphere::mesh::SphereTriagMeshBuilder::radius_ private
Definition at line 90 of file sphere_triag_mesh_builder.h.
Referenced by Build(), and setRadius().
refinement_level_
lf::base::size_type projects::hldo_sphere::mesh::SphereTriagMeshBuilder::refinement_level_ private
Definition at line 91 of file sphere_triag_mesh_builder.h.
Referenced by Build(), and setRefinementLevel().
The documentation for this class was generated from the following files:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/mesh/sphere_triag_mesh_builder.h
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/mesh/sphere_triag_mesh_builder.cc