LehrFEM++: lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > Class Template Reference
lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > Class Template Reference
Concepts » EntityVectorProvider
Local computation of general element (load) vector for scalar finite elements; volume contributions only.
#include <lf/uscalfe/uscalfe.h>
Public Types
using scalar_t = decltype(SCALAR(0) *mesh::utils::MeshFunctionReturnType< MESH_FUNCTION >(0))
Scalar type of the element matrix.
using ElemVec = Eigen::Matrix< scalar_t, Eigen::Dynamic, 1 >
Public Member Functions
ScalarLoadElementVectorProvider (std::shared_ptr< const UniformScalarFESpace< SCALAR > > fe_space, MESH_FUNCTION f)
Constructor, performs precomputations.
ScalarLoadElementVectorProvider (std::shared_ptr< const UniformScalarFESpace< SCALAR > > fe_space, MESH_FUNCTION f, quad_rule_collection_t qr_collection)
Constructor, performs precomputations based on user-supplied quadrature rules.
virtual bool isActive (const lf::mesh::Entity &)
Default implement: all cells are active.
ElemVec Eval (const lf::mesh::Entity &cell)
virtual ~ScalarLoadElementVectorProvider ()=default
standard constructors
ScalarLoadElementVectorProvider (const ScalarLoadElementVectorProvider &)=delete
ScalarLoadElementVectorProvider (ScalarLoadElementVectorProvider &&) noexcept=default
ScalarLoadElementVectorProvider & operator= (const ScalarLoadElementVectorProvider &)=delete
ScalarLoadElementVectorProvider & operator= (ScalarLoadElementVectorProvider &&)=delete
Private Attributes
MESH_FUNCTION f_
An object providing the source function.
std::array< PrecomputedScalarReferenceFiniteElement< SCALAR >, 5 > fe_precomp_
Detailed Description
template<typename SCALAR, typename MESH_FUNCTION>
class lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >
Local computation of general element (load) vector for scalar finite elements; volume contributions only.
Template Parameters
SCALAR Scalar type of the Finite Element Space.
MESH_FUNCTION MeshFunction which defines the source function \(f \)
The underlying local linear form is
\[ v \mapsto \int_K f(\mathbf{x})\,\overline{v(\mathbf{x})}\,\mathrm{d}\mathbf{x}\;, \]
where \(f\) is supposed to be a locally continuous source function.
Computation is based on a quadrature rules supplied by the LehrFEM++ lf::quad::QuadRule module.
This class complies with the requirements for the template parameter ELEM_VEC_COMP of the function AssembleVectorLocally().
Logger
This class logs additional information to ScalarLoadElementVectorProvider(). See Loggers and Debug output for more information.
Definition at line 557 of file loc_comp_ellbvp.h.
Member Typedef Documentation
ElemVec
template<typename SCALAR , typename MESH_FUNCTION > using lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ElemVec = Eigen::Matrix<scalar_t, Eigen::Dynamic, 1>
Definition at line 564 of file loc_comp_ellbvp.h.
scalar_t
template<typename SCALAR , typename MESH_FUNCTION > using lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::scalar_t = decltype(SCALAR(0) * mesh::utils::MeshFunctionReturnType<MESH_FUNCTION>(0))
Scalar type of the element matrix.
Definition at line 562 of file loc_comp_ellbvp.h.
Constructor & Destructor Documentation
ScalarLoadElementVectorProvider() [1/4]
template<typename SCALAR , typename MESH_FUNCTION > lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider (const ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &) delete
ScalarLoadElementVectorProvider() [2/4]
template<typename SCALAR , typename MESH_FUNCTION > lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider (ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &&) default noexcept
ScalarLoadElementVectorProvider() [3/4]
template<typename SCALAR , typename MESH_FUNCTION > lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider (std::shared_ptr< const UniformScalarFESpace< SCALAR > > fe_space, MESH_FUNCTION f)
Constructor, performs precomputations.
Parameters
fe_space specification of local shape functions
f functor object for source function
Uses quadrature rule of double the degree of exactness compared to the degree of the finite element space.
Definition at line 633 of file loc_comp_ellbvp.h.
References lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::fe_precomp_, lf::base::RefEl::kQuad(), lf::base::RefEl::kTria(), and lf::quad::make_QuadRule().
ScalarLoadElementVectorProvider() [4/4]
template<typename SCALAR , typename MESH_FUNCTION > lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider (std::shared_ptr< const UniformScalarFESpace< SCALAR > > fe_space, MESH_FUNCTION f, quad_rule_collection_t qr_collection)
Constructor, performs precomputations based on user-supplied quadrature rules.
Parameters
fe_space specification of local shape functions
f functor object for source function
qr_collection collection of quadrature rule.
Definition at line 653 of file loc_comp_ellbvp.h.
References lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::fe_precomp_, lf::base::RefEl::kQuad(), lf::base::RefEl::kTria(), and lf::quad::QuadRule::RefEl().
~ScalarLoadElementVectorProvider()
template<typename SCALAR , typename MESH_FUNCTION > virtual lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::~ScalarLoadElementVectorProvider () virtual default
Member Function Documentation
Eval()
template<typename SCALAR , typename MESH_FUNCTION > ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ElemVec lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::Eval (const lf::mesh::Entity & cell)
Definition at line 687 of file loc_comp_ellbvp.h.
References lf::geometry::Geometry::DimLocal(), lf::mesh::Entity::Geometry(), lf::geometry::Geometry::Global(), lf::geometry::Geometry::IntegrationElement(), lf::mesh::Entity::RefEl(), and lf::uscalfe::ScalarLoadElementVectorProviderLogger().
isActive()
template<typename SCALAR , typename MESH_FUNCTION > virtual bool lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::isActive (const lf::mesh::Entity &) inline virtual
Default implement: all cells are active.
Definition at line 601 of file loc_comp_ellbvp.h.
operator=() [1/2]
template<typename SCALAR , typename MESH_FUNCTION > ScalarLoadElementVectorProvider & lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::operator= (const ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &) delete
operator=() [2/2]
template<typename SCALAR , typename MESH_FUNCTION > ScalarLoadElementVectorProvider & lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::operator= (ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION > &&) delete
Member Data Documentation
f_
template<typename SCALAR , typename MESH_FUNCTION > MESH_FUNCTION lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::f_ private
An object providing the source function.
Definition at line 615 of file loc_comp_ellbvp.h.
fe_precomp_
template<typename SCALAR , typename MESH_FUNCTION > std::array<PrecomputedScalarReferenceFiniteElement<SCALAR>, 5> lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::fe_precomp_ private
Definition at line 617 of file loc_comp_ellbvp.h.
Referenced by lf::uscalfe::ScalarLoadElementVectorProvider< SCALAR, MESH_FUNCTION >::ScalarLoadElementVectorProvider().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/lib/lf/uscalfe/loc_comp_ellbvp.h