LehrFEM++: projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace Class Reference
projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace Class Reference
Computes the Galerkin LSE for the Hodge Laplacian of the whitney two form.
#include <whitney_two_hodge_laplacian.h>
Public Member Functions
WhitneyTwoHodgeLaplace ()
Constructor initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f.
void Compute ()
Computes the Galerkin LSE.
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh and creates dof_handler.
void SetLoadFunction (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> &f)
Sets the load function.
Eigen::Matrix< double, Eigen::Dynamic, 1 > GetLoadVector ()
returns the Loadvector
lf::assemble::COOMatrix< double > GetGalerkinMatrix ()
returns the Galerkin Matrix
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_
lf::assemble::COOMatrix< double > coo_matrix_
Eigen::Matrix< double, Eigen::Dynamic, 1 > phi_
Detailed Description
Computes the Galerkin LSE for the Hodge Laplacian of the whitney two form.
\[ -\Delta_2 = -\text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ -\Delta_2 u + k^2 u = f \]
Basis functions used are the rotated Whitney 1-forms and the cellwise constant functions
Note
Only triangular meshes are supported
Definition at line 49 of file whitney_two_hodge_laplacian.h.
Constructor & Destructor Documentation
WhitneyTwoHodgeLaplace()
projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::WhitneyTwoHodgeLaplace () inline
Constructor initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f.
Definition at line 57 of file whitney_two_hodge_laplacian.h.
Member Function Documentation
Compute()
void projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::Compute () inline
Computes the Galerkin LSE.
The Galerkin matrix will be accessable with GetGalerkinMatrix() The load vector will be accessable with GetLoadVector()
Definition at line 83 of file whitney_two_hodge_laplacian.h.
References lf::assemble::AssembleVectorLocally(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), lf::assemble::DofHandler::NumDofs(), lf::assemble::COOMatrix< SCALAR >::setZero(), and lf::assemble::COOMatrix< SCALAR >::triplets().
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
GetGalerkinMatrix()
lf::assemble::COOMatrix< double > projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::GetGalerkinMatrix () inline
returns the Galerkin Matrix
This is the Matrix of the LSE containing the negative laplacian
Note
The Galerkin matrix must be computed with Compute() before calling this funciton
Definition at line 229 of file whitney_two_hodge_laplacian.h.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
GetLoadVector()
Eigen::Matrix< double, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::GetLoadVector () inline
returns the Loadvector
This is the righthandside of the LSE
Note
The loadvector must be computed with Compute() before calling this function
Definition at line 218 of file whitney_two_hodge_laplacian.h.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
SetLoadFunction()
void projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::SetLoadFunction (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> & f) inline
Sets the load function.
Parameters
f load function
\[ \Delta_2 = \text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ \Delta_2 u + k^2 u = f \]
Definition at line 204 of file whitney_two_hodge_laplacian.h.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
SetMesh()
void projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh and creates dof_handler.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 179 of file whitney_two_hodge_laplacian.h.
References lf::base::RefEl::kTria(), and lf::base::RefEl::RefEl().
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
Member Data Documentation
coo_matrix_
lf::assemble::COOMatrix<double> projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::coo_matrix_ private
Definition at line 234 of file whitney_two_hodge_laplacian.h.
f_
std::function<double(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::f_ private
Definition at line 233 of file whitney_two_hodge_laplacian.h.
mesh_p_
std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::mesh_p_ private
Definition at line 232 of file whitney_two_hodge_laplacian.h.
phi_
Eigen::Matrix<double, Eigen::Dynamic, 1> projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::phi_ private
Definition at line 235 of file whitney_two_hodge_laplacian.h.
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_two_hodge_laplacian.h