LehrFEM++: projects::ipdg_stokes::mesh Namespace Reference
projects::ipdg_stokes::mesh Namespace Reference
Classes
class AnnulusTriagMeshBuilder
A mesh builder for disks with a hole in the middle.
Functions
Eigen::Matrix< double, 2, 3 > computeOutwardNormals (const lf::mesh::Entity &entity)
Compute the outward pointing normals of a triangle.
Eigen::Matrix< double, 2, 3 > computeTangentials (const lf::mesh::Entity &entity)
Compute the tangentials onto a triangle.
Function Documentation
computeOutwardNormals()
Eigen::Matrix< double, 2, 3 > projects::ipdg_stokes::mesh::computeOutwardNormals (const lf::mesh::Entity & entity)
Compute the outward pointing normals of a triangle.
Parameters
entity The triangle for which the outward pointing normals should be computed
Returns
A matrix containing the outward pointing normals in its columns
The n-th column of the matrix returned corresponds to the outward pointing normal on the n-th edge of the given triangle.
Definition at line 7 of file utils.cc.
References lf::mesh::Entity::Geometry(), lf::geometry::Geometry::Global(), lf::base::RefEl::NodeCoords(), and lf::mesh::Entity::RefEl().
Referenced by computeTangentials(), projects::ipdg_stokes::assemble::createOffsetFunction(), projects::ipdg_stokes::post_processing::DGnorm(), projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler::Eval(), projects::ipdg_stokes::assemble::PiecewiseConstElementMatrixProvider::Eval(), and projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::Eval().
computeTangentials()
Eigen::Matrix< double, 2, 3 > projects::ipdg_stokes::mesh::computeTangentials (const lf::mesh::Entity & entity)
Compute the tangentials onto a triangle.
Parameters
entity The triangle for which the tangentials should be computed
Returns
A matrix containing the tangentials in its columns
The n-th column of the matrix returned corresponds to the tangential vector on the n-th edge of the given triangle. The tangentials on an edge are guaranteed to point in opposite directions when taken from the left or the right adjacent triangle.
Definition at line 36 of file utils.cc.
References computeOutwardNormals().