LehrFEM++: projects::hldo_sphere::assemble::WhitneyOneCurlCurlMatrixProvider Class Reference
projects::hldo_sphere::assemble::WhitneyOneCurlCurlMatrixProvider Class Reference
An elment matrix provider computed with the whitney one form, a vector valued basis function.
#include <whitney_one_curl_curl_matrix_provider.h>
Public Member Functions
WhitneyOneCurlCurlMatrixProvider ()
Constructor.
Eigen::MatrixXd Eval (const lf::mesh::Entity &entity) const
Compute the element matrix for some triangle of a mesh.
bool isActive (const lf::mesh::Entity &entity) const
All entities are regarded as active.
Detailed Description
An elment matrix provider computed with the whitney one form, a vector valued basis function.
The element matrix provider works in a 3 dimensional world with 2 dimensional triangular cells.
\[ (\mathbf{u}, \mathbf{v}) \mapto \int\limits_K \text{curl}_{\Gamma}(\mathbf{u}) \ \text{curl}_{\Gamma}(\mathbf{v}) dx \]
The whitney 1-forms, surface edge elements are associated with edges and defined as
\[ b_i = s_i (\lambda_i \mathbf{grad}_{\Gamma}(\lambda_{i+1}) - \lambda_{i+1} \mathbf{grad}_{\Gamma}(\lambda_{i})) \]
Note
This class complies with the type requirements for the template argument ENTITY_MATRIX_PROVIDER of the function lf::assemble::AssembleMatrixLocally().
Only triangular meshes are supported
Definition at line 43 of file whitney_one_curl_curl_matrix_provider.h.
Constructor & Destructor Documentation
WhitneyOneCurlCurlMatrixProvider()
projects::hldo_sphere::assemble::WhitneyOneCurlCurlMatrixProvider::WhitneyOneCurlCurlMatrixProvider () inline
Constructor.
Definition at line 48 of file whitney_one_curl_curl_matrix_provider.h.
Member Function Documentation
Eval()
Eigen::MatrixXd projects::hldo_sphere::assemble::WhitneyOneCurlCurlMatrixProvider::Eval (const lf::mesh::Entity & entity) const
Compute the element matrix for some triangle of a mesh.
Parameters
entity The mesh triangle to compute the element matrix for
Returns
The 3 by 3 element matrix of the triangle
Note
Currently, only triangular cells are supported
Definition at line 11 of file whitney_one_curl_curl_matrix_provider.cc.
References lf::mesh::Entity::Geometry(), lf::geometry::Geometry::Global(), lf::base::RefEl::kTria(), lf::base::RefEl::NodeCoords(), lf::mesh::Entity::RefEl(), lf::mesh::Entity::RelativeOrientations(), lf::mesh::to_sign(), and lf::geometry::Volume().
isActive()
bool projects::hldo_sphere::assemble::WhitneyOneCurlCurlMatrixProvider::isActive (const lf::mesh::Entity & entity) const inline
All entities are regarded as active.
Definition at line 62 of file whitney_one_curl_curl_matrix_provider.h.
The documentation for this class was generated from the following files:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/whitney_one_curl_curl_matrix_provider.h
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/whitney_one_curl_curl_matrix_provider.cc