LehrFEM++: projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems Class Reference
projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems Class Reference
Creates and solves the discretised Hodge Laplacian source problems.
#include <hodge_laplacians_source_problems.h>
Public Member Functions
HodgeLaplaciansSourceProblems ()
Constructor initializes basic mesh (Octaeder with radius 1.0)
void Compute ()
Computes the Galerkin LSE for all three source problems.
void Solve ()
solves the linear systems build in Compute
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh and creates dof_handler.
void SetLoadFunctions (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> &f0, std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> &f1, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> &f2)
Sets the load functions.
void SetK (double k)
Sets k for the souce problems.
Eigen::Matrix< double, Eigen::Dynamic, 1 > GetLoadVector (int index)
returns the Loadvector
lf::assemble::COOMatrix< double > GetGalerkinMatrix (int index)
returns the Galerkin Matrix
Eigen::Matrix< double, Eigen::Dynamic, 1 > GetMuZero ()
retunrs the basis expansion coefficiants for the solution of the zero form
std::tuple< Eigen::Matrix< double, Eigen::Dynamic, 1 >, Eigen::Matrix< double, Eigen::Dynamic, 1 > > GetMuOne ()
retunrs the basis expansion coefficiants for the solution of the one form
std::tuple< Eigen::Matrix< double, Eigen::Dynamic, 1 >, Eigen::Matrix< double, Eigen::Dynamic, 1 > > GetMuTwo ()
retunrs the basis expansion coefficiants for the solution of the two form
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f0_
std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f1_
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f2_
std::vector< lf::assemble::COOMatrix< double > > coo_matrix_
std::vector< Eigen::Matrix< double, Eigen::Dynamic, 1 > > phi_
std::vector< Eigen::Matrix< double, Eigen::Dynamic, 1 > > mu_
double k_
Detailed Description
Creates and solves the discretised Hodge Laplacian source problems.
Note
Only triangular meshes are supported
Definition at line 29 of file hodge_laplacians_source_problems.h.
Constructor & Destructor Documentation
HodgeLaplaciansSourceProblems()
projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::HodgeLaplaciansSourceProblems () inline
Constructor initializes basic mesh (Octaeder with radius 1.0)
set k to 1
For all three Hodge Laplacians initializes zerovalued functions f
Definition at line 41 of file hodge_laplacians_source_problems.h.
References coo_matrix_, f0_, f1_, f2_, k_, mesh_p_, mu_, phi_, and projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel().
Member Function Documentation
Compute()
void projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute () inline
Computes the Galerkin LSE for all three source problems.
\[ - \Delta_l u + k^2 u = f_l \qquad l = 0, 1, 2 \]
The Galerkin matrix will be accessable with GetGalerkinMatrix(int index) The load vector will be accessable with GetLoadVector(int index)
Definition at line 90 of file hodge_laplacians_source_problems.h.
References lf::assemble::COOMatrix< SCALAR >::AddToEntry(), lf::assemble::COOMatrix< SCALAR >::cols(), projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::Compute(), projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::Compute(), projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::Compute(), coo_matrix_, f0_, f1_, f2_, projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::GetGalerkinMatrix(), projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::GetGalerkinMatrix(), projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::GetGalerkinMatrix(), projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::GetLoadVector(), projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::GetLoadVector(), projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::GetLoadVector(), k_, lf::base::RefEl::kPoint(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), mesh_p_, lf::assemble::DofHandler::NumDofs(), phi_, lf::assemble::COOMatrix< SCALAR >::rows(), projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::SetLoadFunction(), projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::SetLoadFunction(), projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::SetLoadFunction(), projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::SetMesh(), projects::hldo_sphere::discretization::WhitneyTwoHodgeLaplace::SetMesh(), projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::SetMesh(), lf::assemble::COOMatrix< SCALAR >::setZero(), and lf::assemble::COOMatrix< SCALAR >::triplets().
GetGalerkinMatrix()
lf::assemble::COOMatrix< double > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::GetGalerkinMatrix (int index) inline
returns the Galerkin Matrix
This is the Matrix of the LSE with index index
Note
The Galerkin matrix must be computed with Compute() before calling this funciton
Definition at line 349 of file hodge_laplacians_source_problems.h.
References coo_matrix_.
GetLoadVector()
Eigen::Matrix< double, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::GetLoadVector (int index) inline
returns the Loadvector
This is the righthandside of LSE with index index
Note
The loadvector must be computed with Compute before calling this function
Definition at line 336 of file hodge_laplacians_source_problems.h.
References phi_.
GetMuOne()
std::tuple< Eigen::Matrix< double, Eigen::Dynamic, 1 >, Eigen::Matrix< double, Eigen::Dynamic, 1 > > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::GetMuOne () inline
retunrs the basis expansion coefficiants for the solution of the one form
The first vector of the return value are the coefficiants with respect to whitney one form basis function. They represent an approximation of
\[ u \]
The second vector of the return value are the coefficiants with respect to to the barycentric basis functions. They represent the approximation for
\[ p := \text{div}_{\Gamma}(u) \]
on the mesh.
Returns
basis expansion coefficiants of one form
Note
the methods Compute() and Solve() must be called before the result is available
Definition at line 392 of file hodge_laplacians_source_problems.h.
References mesh_p_, and mu_.
GetMuTwo()
std::tuple< Eigen::Matrix< double, Eigen::Dynamic, 1 >, Eigen::Matrix< double, Eigen::Dynamic, 1 > > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::GetMuTwo () inline
retunrs the basis expansion coefficiants for the solution of the two form
The first vector of the return value are the coefficiants with respect to rotated (90 degree colckwise) whitney one form basis function. They represent an approximation of
\[ j = \textbf{grad}_{\Gamma}(u) \]
The second vector of the return value are the coefficiants with respect to to the piecewise constant basis functions. They represent the approximation for
\[ u \]
on the mesh.
Returns
basis expansion coefficiants of two form
Note
the methods Compute() and Solve() must be called before the result is available
Definition at line 425 of file hodge_laplacians_source_problems.h.
References mesh_p_, and mu_.
GetMuZero()
Eigen::Matrix< double, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::GetMuZero () inline
retunrs the basis expansion coefficiants for the solution of the zero form
The basis expansion coefficiants are with respect to the barycentric basis functions on the mesh.
Returns
basis expansion coefficiants of zero form
Note
the methods Compute() and Solve() must be called before the result is available
Definition at line 366 of file hodge_laplacians_source_problems.h.
References mu_.
SetK()
void projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::SetK (double k) inline
Sets k for the souce problems.
Parameters
k real valued parameter scaling the mass matrix
Definition at line 325 of file hodge_laplacians_source_problems.h.
References k_.
SetLoadFunctions()
void projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::SetLoadFunctions (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> & f0, std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> & f1, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> & f2) inline
Sets the load functions.
Parameters
f0 load function in L^2
f1 load functions in L^2_t vector valued
f2 load functions in L^2
Definition at line 310 of file hodge_laplacians_source_problems.h.
References f0_, f1_, and f2_.
Referenced by projects::hldo_sphere::examples::HodgeLaplacianExample::Compute().
SetMesh()
void projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh and creates dof_handler.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 288 of file hodge_laplacians_source_problems.h.
References lf::base::RefEl::kTria(), mesh_p_, and lf::base::RefEl::RefEl().
Solve()
void projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Solve () inline
solves the linear systems build in Compute
Uses the Matrices stored in coo_matrix_ and the righthandside vectors stored in phi_ to compute the basis expansion coefficiants mu_ approximating
Note
the method Compute() has to be called prior to calling Solve()
\[ - \Delta_l u + k^2 u = f_l \qquad l = 0, 1, 2 \]
Definition at line 268 of file hodge_laplacians_source_problems.h.
References coo_matrix_, mu_, and phi_.
Member Data Documentation
coo_matrix_
std::vector<lf::assemble::COOMatrix<double> > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::coo_matrix_ private
Definition at line 440 of file hodge_laplacians_source_problems.h.
Referenced by Compute(), GetGalerkinMatrix(), HodgeLaplaciansSourceProblems(), and Solve().
f0_
std::function<double(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::f0_ private
Definition at line 435 of file hodge_laplacians_source_problems.h.
Referenced by Compute(), HodgeLaplaciansSourceProblems(), and SetLoadFunctions().
f1_
std::function<Eigen::Matrix<double, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::f1_ private
Definition at line 438 of file hodge_laplacians_source_problems.h.
Referenced by Compute(), HodgeLaplaciansSourceProblems(), and SetLoadFunctions().
f2_
std::function<double(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::f2_ private
Definition at line 439 of file hodge_laplacians_source_problems.h.
Referenced by Compute(), HodgeLaplaciansSourceProblems(), and SetLoadFunctions().
k_
double projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::k_ private
Definition at line 443 of file hodge_laplacians_source_problems.h.
Referenced by Compute(), HodgeLaplaciansSourceProblems(), and SetK().
mesh_p_
std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::mesh_p_ private
Definition at line 434 of file hodge_laplacians_source_problems.h.
Referenced by Compute(), GetMuOne(), GetMuTwo(), HodgeLaplaciansSourceProblems(), and SetMesh().
mu_
std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::mu_ private
Definition at line 442 of file hodge_laplacians_source_problems.h.
Referenced by GetMuOne(), GetMuTwo(), GetMuZero(), HodgeLaplaciansSourceProblems(), and Solve().
phi_
std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::phi_ private
Definition at line 441 of file hodge_laplacians_source_problems.h.
Referenced by Compute(), GetLoadVector(), HodgeLaplaciansSourceProblems(), and Solve().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/hodge_laplacians_source_problems.h