LehrFEM++: FisherKPP Namespace Reference
FisherKPP Namespace Reference
Classes
class StrangSplit
Functions
template<typename FUNCTOR >
auto localQuadFunction (const lf::mesh::Mesh &mesh, std::map< lf::base::RefEl, lf::quad::QuadRule > quadrules, FUNCTOR &&f, unsigned int codim, const std::function< bool(const lf::mesh::Entity &)> &pred)
template<typename DIFF_COEFF , typename NONLOC_BC >
std::pair< Eigen::SparseMatrix< double >, Eigen::SparseMatrix< double > > assembleGalerkinMatrices (const lf::assemble::DofHandler &dofh, DIFF_COEFF &&c, NONLOC_BC &&h, const Eigen::MatrixXd &L)
Function Documentation
assembleGalerkinMatrices()
template<typename DIFF_COEFF , typename NONLOC_BC > std::pair< Eigen::SparseMatrix< double >, Eigen::SparseMatrix< double > > FisherKPP::assembleGalerkinMatrices (const lf::assemble::DofHandler & dofh, DIFF_COEFF && c, NONLOC_BC && h, const Eigen::MatrixXd & L)
Definition at line 121 of file strangsplitting.h.
References lf::assemble::AssembleMatrixLocally(), lf::mesh::utils::flagEntitiesOnBoundary(), lf::assemble::COOMatrix< SCALAR >::makeSparse(), lf::assemble::DofHandler::Mesh(), and lf::assemble::DofHandler::NumDofs().
Referenced by FisherKPP::StrangSplit::StrangSplit().
localQuadFunction()
template<typename FUNCTOR > auto FisherKPP::localQuadFunction (const lf::mesh::Mesh & mesh, std::map< lf::base::RefEl, lf::quad::QuadRule > quadrules, FUNCTOR && f, unsigned int codim, const std::function< bool(const lf::mesh::Entity &)> & pred)
Definition at line 76 of file strangsplitting.h.
References lf::mesh::Mesh::DimMesh(), lf::mesh::Mesh::Entities(), lf::geometry::Geometry::Geometry(), and lf::quad::QuadRule::NumPoints().