LehrFEM++: projects::hldo_sphere::discretization::DiracOperatorSourceProblem Class Reference
projects::hldo_sphere::discretization::DiracOperatorSourceProblem Class Reference
Computes the Galerkin LSE for the Dirac Operator source problem.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/dirac_operator_source_problem.h>
Public Member Functions
DiracOperatorSourceProblem ()
Constructor creates basic mesh (Octaeder with radius 1.0)
void Compute ()
Computes the Galerkin LSE for the dirac operator source problem.
void Solve ()
solves the linear systems build in Compute
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh.
void SetLoadFunctions (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f0, std::function< Eigen::Matrix< SCALAR, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f1, std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f2)
Sets the load functions.
void SetK (double k)
Sets k for the souce problems.
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > GetLoadVector ()
returns the Loadvector
lf::assemble::COOMatrix< SCALAR > GetGalerkinMatrix ()
returns the Galerkin Matrix
Eigen::Matrix< double, Eigen::Dynamic, 1 > GetMu (int index)
retunrs the basis expansion coefficiants for the solution of the source problem
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f0_
std::function< Eigen::Matrix< SCALAR, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f1_
std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f2_
lf::assemble::COOMatrix< SCALAR > coo_matrix_
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > phi_
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > mu_
SCALAR k_
Detailed Description
Computes the Galerkin LSE for the Dirac Operator source problem.
\[ D \vec{u} + \imath k \vec{u} = \vec{f} \]
The computation must be complex valued since the problem definition involves a complex i
Note
Only triangular meshes are supported
Definition at line 51 of file dirac_operator_source_problem.h.
Constructor & Destructor Documentation
DiracOperatorSourceProblem()
projects::hldo_sphere::discretization::DiracOperatorSourceProblem::DiracOperatorSourceProblem () inline
Constructor creates basic mesh (Octaeder with radius 1.0)
set k to 1
For all three Hodge Laplacians creates zerovalued functions f
Definition at line 63 of file dirac_operator_source_problem.h.
References f0_, f1_, f2_, k_, mesh_p_, mu_, phi_, and projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel().
Member Function Documentation
Compute()
void projects::hldo_sphere::discretization::DiracOperatorSourceProblem::Compute () inline
Computes the Galerkin LSE for the dirac operator source problem.
\[ D \vec{u} + \imath k \vec{u} = \vec{f} \]
The Galerkin matrix will be accessable with GetGalerkinMatrix() The load vector will be accessable with GetLoadVector()
Definition at line 107 of file dirac_operator_source_problem.h.
References lf::assemble::COOMatrix< SCALAR >::AddToEntry(), projects::hldo_sphere::discretization::DiracOperator::Compute(), coo_matrix_, f0_, f1_, f2_, projects::hldo_sphere::discretization::DiracOperator::GetGalerkinMatrix(), projects::hldo_sphere::discretization::DiracOperator::GetLoadVector(), k_, lf::base::RefEl::kPoint(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), mesh_p_, lf::assemble::DofHandler::NumDofs(), phi_, projects::hldo_sphere::discretization::DiracOperator::SetLoadFunctions(), projects::hldo_sphere::discretization::DiracOperator::SetMesh(), lf::assemble::COOMatrix< SCALAR >::setZero(), and lf::assemble::COOMatrix< SCALAR >::triplets().
GetGalerkinMatrix()
lf::assemble::COOMatrix< SCALAR > projects::hldo_sphere::discretization::DiracOperatorSourceProblem::GetGalerkinMatrix () inline
returns the Galerkin Matrix
This is the Matrix of the LSE
Note
The Galerkin matrix must be computed with Compute before calling this funciton
Definition at line 292 of file dirac_operator_source_problem.h.
References coo_matrix_.
GetLoadVector()
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::DiracOperatorSourceProblem::GetLoadVector () inline
returns the Loadvector
This is the righthandside of LSE
Note
The loadvector must be computed with Compute before calling this function
Definition at line 281 of file dirac_operator_source_problem.h.
References phi_.
GetMu()
Eigen::Matrix< double, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::DiracOperatorSourceProblem::GetMu (int index) inline
retunrs the basis expansion coefficiants for the solution of the source problem
BUT ONLY THE REAL PART
The basis expansion coefficiants for the first number of vertices entries are with respect to the barycentric basis functions on the mesh.
The basis expansion coefficiants for the next number of edge entries are with respect to the whitney one form basis functions.
The last number of cells basis expansion coefficiants are with respect to the cellwise constant basis functions
Parameters
index of the basis (0 -> barycentric basis, 1 -> Whitney 1-forms, surface edge elements, 2 -> cellwise constant)
Returns
basis expansion coefficiants
Note
the methods Compute() and Solve() must be called before the result is available
Definition at line 320 of file dirac_operator_source_problem.h.
References mesh_p_, and mu_.
SetK()
void projects::hldo_sphere::discretization::DiracOperatorSourceProblem::SetK (double k) inline
Sets k for the souce problems.
Parameters
k real valued parameter scaling the mass matrix
Definition at line 270 of file dirac_operator_source_problem.h.
References k_.
SetLoadFunctions()
void projects::hldo_sphere::discretization::DiracOperatorSourceProblem::SetLoadFunctions (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f0, std::function< Eigen::Matrix< SCALAR, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f1, std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f2) inline
Sets the load functions.
Parameters
f0 load function in \(L^2 \)
f1 load functions in \(L^2_t \) tangential vector field on the sphere
f2 load functions in \(L^2 \)
Definition at line 254 of file dirac_operator_source_problem.h.
References f0_, f1_, and f2_.
Referenced by projects::hldo_sphere::examples::DiracOperatorExample::Compute().
SetMesh()
void projects::hldo_sphere::discretization::DiracOperatorSourceProblem::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 231 of file dirac_operator_source_problem.h.
References lf::base::RefEl::kTria(), mesh_p_, and lf::base::RefEl::RefEl().
Solve()
void projects::hldo_sphere::discretization::DiracOperatorSourceProblem::Solve () inline
solves the linear systems build in Compute
Uses the Matrices stored in coo_matrix_ and the righthandside vectors stored in phi_ to compute the basis expansion coefficiants mu_ approximating
Note
the method Compute() has to be called prior to calling Solve()
\[ D \vec{u} + \imath k \vec{u} = \vec{f} \]
Definition at line 211 of file dirac_operator_source_problem.h.
References coo_matrix_, mu_, and phi_.
Member Data Documentation
coo_matrix_
lf::assemble::COOMatrix<SCALAR> projects::hldo_sphere::discretization::DiracOperatorSourceProblem::coo_matrix_ private
Definition at line 342 of file dirac_operator_source_problem.h.
Referenced by Compute(), GetGalerkinMatrix(), and Solve().
f0_
std::function<SCALAR(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::DiracOperatorSourceProblem::f0_ private
Definition at line 337 of file dirac_operator_source_problem.h.
Referenced by Compute(), DiracOperatorSourceProblem(), and SetLoadFunctions().
f1_
std::function<Eigen::Matrix<SCALAR, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::DiracOperatorSourceProblem::f1_ private
Definition at line 340 of file dirac_operator_source_problem.h.
Referenced by Compute(), DiracOperatorSourceProblem(), and SetLoadFunctions().
f2_
std::function<SCALAR(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::DiracOperatorSourceProblem::f2_ private
Definition at line 341 of file dirac_operator_source_problem.h.
Referenced by Compute(), DiracOperatorSourceProblem(), and SetLoadFunctions().
k_
SCALAR projects::hldo_sphere::discretization::DiracOperatorSourceProblem::k_ private
Definition at line 345 of file dirac_operator_source_problem.h.
Referenced by Compute(), DiracOperatorSourceProblem(), and SetK().
mesh_p_
std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::discretization::DiracOperatorSourceProblem::mesh_p_ private
Definition at line 336 of file dirac_operator_source_problem.h.
Referenced by Compute(), DiracOperatorSourceProblem(), GetMu(), and SetMesh().
mu_
Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> projects::hldo_sphere::discretization::DiracOperatorSourceProblem::mu_ private
Definition at line 344 of file dirac_operator_source_problem.h.
Referenced by DiracOperatorSourceProblem(), GetMu(), and Solve().
phi_
Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> projects::hldo_sphere::discretization::DiracOperatorSourceProblem::phi_ private
Definition at line 343 of file dirac_operator_source_problem.h.
Referenced by Compute(), DiracOperatorSourceProblem(), GetLoadVector(), and Solve().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/dirac_operator_source_problem.h