LehrFEM++: projects::hldo_sphere::assemble::WhitneyTwoMassMatrixProvider Class Reference
projects::hldo_sphere::assemble::WhitneyTwoMassMatrixProvider Class Reference
Element matrix provider for the bilinear form with cellwise constant basis functions.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/whitney_two_mass_matrix_provider.h>
Public Member Functions
WhitneyTwoMassMatrixProvider ()
Constructor.
Eigen::MatrixXd Eval (const lf::mesh::Entity &entity) const
Compute the element matrix for some cell of a mesh.
bool isActive (const lf::mesh::Entity &entity) const
All entities are regarded as active.
Detailed Description
Element matrix provider for the bilinear form with cellwise constant basis functions.
\[ (u, v) \mapsto \int\limits_{K} u \, v \ dx \]
The element matrix provider works in a 3 dimensional world with 2 dimensional triangular cells.
Basis functions are the piecewise constant functions Hence the retuned matrix is of size 1x1 and contains the area of the cell
Note
This class complies with the type requirements for the template argument ENTITY_MATRIX_PROVIDER of the function lf::assemble::AssembleMatrixLocally().
Only triangular meshes are supported
Definition at line 37 of file whitney_two_mass_matrix_provider.h.
Constructor & Destructor Documentation
WhitneyTwoMassMatrixProvider()
projects::hldo_sphere::assemble::WhitneyTwoMassMatrixProvider::WhitneyTwoMassMatrixProvider () inline
Constructor.
Definition at line 42 of file whitney_two_mass_matrix_provider.h.
Member Function Documentation
Eval()
Eigen::MatrixXd projects::hldo_sphere::assemble::WhitneyTwoMassMatrixProvider::Eval (const lf::mesh::Entity & entity) const
Compute the element matrix for some cell of a mesh.
Parameters
entity The mesh cell to compute the element matrix for
Returns
The 1 by 1 element matrix of the cell
Note
Only triangluar meshes are supported
Definition at line 11 of file whitney_two_mass_matrix_provider.cc.
References lf::mesh::Entity::Geometry(), lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), and lf::geometry::Volume().
isActive()
bool projects::hldo_sphere::assemble::WhitneyTwoMassMatrixProvider::isActive (const lf::mesh::Entity & entity) const inline
All entities are regarded as active.
Definition at line 56 of file whitney_two_mass_matrix_provider.h.
The documentation for this class was generated from the following files:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/whitney_two_mass_matrix_provider.h
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/whitney_two_mass_matrix_provider.cc