LehrFEM++: lf::uscalfe::FeLagrangeO1Tria< SCALAR > Class Template Reference
lf::uscalfe::FeLagrangeO1Tria< SCALAR > Class Template Reference final
Linear Lagrange finite element on triangular reference element.
#include <lf/uscalfe/uscalfe.h>
Public Member Functions
FeLagrangeO1Tria (const FeLagrangeO1Tria &)=default
FeLagrangeO1Tria (FeLagrangeO1Tria &&) noexcept=default
FeLagrangeO1Tria & operator= (const FeLagrangeO1Tria &)=default
FeLagrangeO1Tria & operator= (FeLagrangeO1Tria &&) noexcept=default
FeLagrangeO1Tria ()=default
~FeLagrangeO1Tria () override=default
base::RefEl RefEl () const override
Tells the type of reference cell underlying the parametric finite element.
unsigned Degree () const override
Request the maximal polynomial degree of the basis functions in this finite element.
size_type NumRefShapeFunctions () const override
The local shape functions: barycentric coordinate functions.
size_type NumRefShapeFunctions (dim_t codim) const override
Exactly one shape function attached to each node, none to other sub-entities.
size_type NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const override
Exactly one shape function attached to each node, none to other sub-entities.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > EvalReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Evaluation of all reference shape functions in a number of points.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > GradientsReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const override
Computation of the gradients of all reference shape functions in a number of points.
Eigen::MatrixXd EvaluationNodes () const override
Evalutation nodes are just the vertices of the triangle.
size_type NumEvaluationNodes () const override
Three evaluation nodes.
Public Member Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
virtual ~ScalarReferenceFiniteElement ()=default
virtual base::RefEl RefEl () const =0
Tells the type of reference cell underlying the parametric finite element.
virtual unsigned int Degree () const =0
Request the maximal polynomial degree of the basis functions in this finite element.
dim_t Dimension () const
Returns the spatial dimension of the reference cell.
virtual size_type NumRefShapeFunctions () const
Total number of reference shape functions associated with the reference cell.
virtual size_type NumRefShapeFunctions (dim_t codim) const
The number of interior reference shape functions for sub-entities of a particular co-dimension.
virtual size_type NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const =0
The number of interior reference shape functions for every sub-entity.
virtual Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > EvalReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const =0
Evaluation of all reference shape functions in a number of points.
virtual Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > GradientsReferenceShapeFunctions (const Eigen::MatrixXd &refcoords) const =0
Computation of the gradients of all reference shape functions in a number of points.
virtual Eigen::MatrixXd EvaluationNodes () const =0
Returns reference coordinates of "evaluation nodes" for evaluation of parametric degrees of freedom, nodal interpolation in the simplest case.
virtual size_type NumEvaluationNodes () const =0
Tell the number of evaluation (interpolation) nodes.
virtual Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > NodalValuesToDofs (const Eigen::Matrix< SCALAR, 1, Eigen::Dynamic > &nodvals) const
Computes the linear combination of reference shape functions matching function values at evaluation nodes.
Additional Inherited Members
Public Types inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
using Scalar = SCALAR
The underlying scalar type.
Protected Member Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
ScalarReferenceFiniteElement ()=default
ScalarReferenceFiniteElement (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement (ScalarReferenceFiniteElement &&) noexcept=default
ScalarReferenceFiniteElement & operator= (const ScalarReferenceFiniteElement &)=default
ScalarReferenceFiniteElement & operator= (ScalarReferenceFiniteElement &&) noexcept=default
Related Functions inherited from lf::fe::ScalarReferenceFiniteElement< SCALAR >
template<class SCALAR >
void PrintInfo (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &srfe, unsigned int ctrl=0)
Print information about a ScalarReferenceFiniteElement to the given stream.
template<typename SCALAR >
std::ostream & operator<< (std::ostream &o, const ScalarReferenceFiniteElement< SCALAR > &fe_desc)
Stream output operator: just calls the ScalarReferenceFiniteElement::print() method.
Detailed Description
template<typename SCALAR>
class lf::uscalfe::FeLagrangeO1Tria< SCALAR >
Linear Lagrange finite element on triangular reference element.
This is a specialization of fe::ScalarReferenceFiniteElement. Refer to its documentation.
The reference shape functions are
\[ \widehat{b}^1(\widehat{\mathbf{x}}) = 1-\widehat{x}_1-\widehat{x}_2\quad,\quad \widehat{b}^2(\widehat{\mathbf{x}}) = \widehat{x}_1\quad,\quad \widehat{b}^3(\widehat{\mathbf{x}}) = \widehat{x}_2 \;. \]
The basis function \(\widehat{b}^i\) is associated with vertex \(i\) of the triangle.
See also
fe::ScalarReferenceFiniteElement
Definition at line 57 of file lagr_fe.h.
Constructor & Destructor Documentation
FeLagrangeO1Tria() [1/3]
template<typename SCALAR > lf::uscalfe::FeLagrangeO1Tria< SCALAR >::FeLagrangeO1Tria (const FeLagrangeO1Tria< SCALAR > &) default
FeLagrangeO1Tria() [2/3]
template<typename SCALAR > lf::uscalfe::FeLagrangeO1Tria< SCALAR >::FeLagrangeO1Tria (FeLagrangeO1Tria< SCALAR > &&) default noexcept
FeLagrangeO1Tria() [3/3]
template<typename SCALAR > lf::uscalfe::FeLagrangeO1Tria< SCALAR >::FeLagrangeO1Tria () default
~FeLagrangeO1Tria()
template<typename SCALAR > lf::uscalfe::FeLagrangeO1Tria< SCALAR >::~FeLagrangeO1Tria () override default
Member Function Documentation
Degree()
template<typename SCALAR > unsigned lf::uscalfe::FeLagrangeO1Tria< SCALAR >::Degree () const inline override virtual
Request the maximal polynomial degree of the basis functions in this finite element.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 71 of file lagr_fe.h.
EvalReferenceShapeFunctions()
template<typename SCALAR > Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > lf::uscalfe::FeLagrangeO1Tria< SCALAR >::EvalReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline override virtual
Evaluation of all reference shape functions in a number of points.
Parameters
refcoords coordinates of N points in the reference cell passed as columns of a matrix of size dim x N, where dim is the dimension of the reference element, that is =0 for points, =1 for edges, =2 for triangles and quadrilaterals
Returns
An Eigen Matrix of size NumRefShapeFunctions() x refcoords.cols() which contains the shape functions evaluated at every quadrature point.
Concerning the numbering of local shape functions, please consult the documentation of lf::assemble::DofHandler or the documentation of the class.
Note
shape functions are assumed to be real-valued.
Example: Triangular Linear Lagrangian finite elements
There are three reference shape functions \(\hat{b}^1,\hat{b}^2,\hat{b}^3\) associated with the vertices of the reference triangle. Let us assume that the refcoords argument is a 2x2 matrix \([\mathbf{x}_1\;\mathbf{x}_2]\), which corresponds to passing the coordinates of two points in the reference triangle. Then this method will return a 3x2 matrix:
\[ \begin{pmatrix}\hat{b}^1(\mathbf{x}_1) & \hat{b}^1(\mathbf{x}_2) \\ \hat{b}^2(\mathbf{x}_1) & \hat{b}^2(\mathbf{x}_2) \\ \hat{b}^3(\mathbf{x}_1)\ & \hat{b}^3(\mathbf{x}_2) \end{pmatrix} \]
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 104 of file lagr_fe.h.
Referenced by projects::hldo_sphere::assemble::LoadVectorProvider< SCALAR >::Eval(), and projects::hldo_sphere::assemble::WhitneyOneVectorProvider< SCALAR >::Eval().
EvaluationNodes()
template<typename SCALAR > Eigen::MatrixXd lf::uscalfe::FeLagrangeO1Tria< SCALAR >::EvaluationNodes () const inline override virtual
Evalutation nodes are just the vertices of the triangle.
Returns reference coordinates of "evaluation nodes" for evaluation of parametric degrees of freedom, nodal interpolation in the simplest case.
Returns
A d x N matrix, where d is the dimension of the reference cell, and N the number of interpolation nodes. The columns of this matrix contain their reference coordinates.
Every parametric scalar finite element implicitly defines a local interpolation operator by duality with the reference shape functions. This interpolation operator can be realized through evaluations at certain evaluation nodes, which are provided by this method.
Unisolvence
The evaluation points must satisfy the following requirement: If the values of a function belonging to the span of the reference shape functions are known in the evaluation nodes, then this function is uniquely determined. This entails that the number of evaluation nodes must be at least as big as the number of reference shape functions.
Note
It is not required that any vector a values at evaluation nodes can be produced by a suitable linear combination of reference shape functions. For instance, this will not be possible, if there are more evaluation points than reference shape functions. If both sets have the same size, however, the interpolation problem has a solution for any vector of values at the evluation points.
Example: Principal lattice
For triangular Lagrangian finite elements of degree p the evaluation nodes, usually called "interpolation nodes" in this context, can be chosen as \(\left(\frac{j}{p},\frac{k}{p}\right),\; 0\leq j,k \leq p, j+k\leq p\).
Moment-based degrees of freedom
For some finite element spaces the interpolation functional may be defined based on integrals over edges. In this case the evaluation nodes will be quadrature nodes for the approximate evaluation of these integrals.
The quadrature rule must be exact for the polynomials contained in the local finite element spaces.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 134 of file lagr_fe.h.
References lf::base::RefEl::NodeCoords(), and lf::uscalfe::FeLagrangeO1Tria< SCALAR >::RefEl().
GradientsReferenceShapeFunctions()
template<typename SCALAR > Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > lf::uscalfe::FeLagrangeO1Tria< SCALAR >::GradientsReferenceShapeFunctions (const Eigen::MatrixXd & refcoords) const inline override virtual
Computation of the gradients of all reference shape functions in a number of points.
Parameters
refcoords coordinates of N points in the reference cell passed as columns of a matrix of size dim x N.
Returns
An Eigen Matrix of size NumRefShapeFunctions() x (dim * refcoords.cols()) where dim is the dimension of the reference finite element. The gradients are returned in chunks of rows of this matrix.
Concerning the numbering of local shape functions, please consult the documentation of lf::assemble::DofHandler.
Example: Triangular Linear Lagrangian finite elements
There are three reference shape functions \(\hat{b}^1,\hat{b}^2,\hat{b}^3\) associated with the vertices of the reference triangle. Let us assume that the refcoords argument is a 2x2 matrix \([\mathbf{x}_1\;\mathbf{x}_2]\), which corresponds to passing the coordinates of two points in the reference triangle. Then this method will return a 3x4 matrix:
\[ \begin{pmatrix} \grad^T\hat{b}^1(\mathbf{x}_1) & \grad^T\hat{b}^1(\mathbf{x}_2) \\ \grad^T\hat{b}^2(\mathbf{x}_1) & \grad^T\hat{b}^2(\mathbf{x}_2) \\ \grad^T\hat{b}^3(\mathbf{x}_1) & \grad^T\hat{b}^3(\mathbf{x}_2) \end{pmatrix} \]
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 117 of file lagr_fe.h.
Referenced by projects::hldo_sphere::debugging::WhitneyOneBasisExpansionCoeffs::Compute(), projects::hldo_sphere::assemble::LaplaceMatrixProvider::Eval(), projects::hldo_sphere::assemble::WhitneyOneGradMatrixProvider::Eval(), projects::hldo_sphere::assemble::WhitneyOneMassMatrixProvider::Eval(), projects::hldo_sphere::assemble::WhitneyOneVectorProvider< SCALAR >::Eval(), projects::ipdg_stokes::assemble::PiecewiseBoundaryNormalJumpAssembler::Eval(), projects::ipdg_stokes::assemble::PiecewiseConstElementMatrixProvider::Eval(), projects::ipdg_stokes::assemble::PiecewiseConstElementVectorProvider::Eval(), and projects::ipdg_stokes::post_processing::extractVelocity().
NumEvaluationNodes()
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO1Tria< SCALAR >::NumEvaluationNodes () const inline override virtual
Three evaluation nodes.
Tell the number of evaluation (interpolation) nodes.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 141 of file lagr_fe.h.
References lf::base::RefEl::NumNodes(), and lf::uscalfe::FeLagrangeO1Tria< SCALAR >::RefEl().
NumRefShapeFunctions() [1/3]
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO1Tria< SCALAR >::NumRefShapeFunctions () const inline override virtual
The local shape functions: barycentric coordinate functions.
Total number of reference shape functions associated with the reference cell.
Note
the total number of shape functions is the sum of the number of interior shape functions for all sub-entities and the entity itself.
Reimplemented from lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 76 of file lagr_fe.h.
NumRefShapeFunctions() [2/3]
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO1Tria< SCALAR >::NumRefShapeFunctions (dim_t codim) const inline override virtual
Exactly one shape function attached to each node, none to other sub-entities.
The number of interior reference shape functions for sub-entities of a particular co-dimension.
Parameters
codim co-dimension of the subentity
Returns
number of interior reference shape function belonging to the specified sub-entity.
Note
this method will throw an exception when different numbers of reference shape functions are assigned to different sub-entities of the same co-dimension
Reimplemented from lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 84 of file lagr_fe.h.
NumRefShapeFunctions() [3/3]
template<typename SCALAR > size_type lf::uscalfe::FeLagrangeO1Tria< SCALAR >::NumRefShapeFunctions (dim_t codim, sub_idx_t subidx) const inline override virtual
Exactly one shape function attached to each node, none to other sub-entities.
The number of interior reference shape functions for every sub-entity.
Parameters
codim do-dimension of the subentity
subidx local index of the sub-entity
Returns
number of interior reference shape function belonging to the specified sub-entity.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 94 of file lagr_fe.h.
operator=() [1/2]
template<typename SCALAR > FeLagrangeO1Tria & lf::uscalfe::FeLagrangeO1Tria< SCALAR >::operator= (const FeLagrangeO1Tria< SCALAR > &) default
operator=() [2/2]
template<typename SCALAR > FeLagrangeO1Tria & lf::uscalfe::FeLagrangeO1Tria< SCALAR >::operator= (FeLagrangeO1Tria< SCALAR > &&) default noexcept
RefEl()
template<typename SCALAR > base::RefEl lf::uscalfe::FeLagrangeO1Tria< SCALAR >::RefEl () const inline override virtual
Tells the type of reference cell underlying the parametric finite element.
Implements lf::fe::ScalarReferenceFiniteElement< SCALAR >.
Definition at line 67 of file lagr_fe.h.
References lf::base::RefEl::kTria().
Referenced by lf::uscalfe::FeLagrangeO1Tria< SCALAR >::EvaluationNodes(), and lf::uscalfe::FeLagrangeO1Tria< SCALAR >::NumEvaluationNodes().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/lib/lf/uscalfe/lagr_fe.h