LehrFEM++: projects::hldo_sphere::assemble::RotWhitneyOneDivMatrixProvider Class Reference
projects::hldo_sphere::assemble::RotWhitneyOneDivMatrixProvider Class Reference
Element matrix provider for rotated whitney one form.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/rot_whitney_one_div_matrix_provider.h>
Public Member Functions
RotWhitneyOneDivMatrixProvider ()
Constructor.
Eigen::MatrixXd Eval (const lf::mesh::Entity &entity) const
Compute the element matrix for some triangle of a mesh.
bool isActive (const lf::mesh::Entity &entity) const
All entities are regarded as active.
Detailed Description
Element matrix provider for rotated whitney one form.
\[ (\mathbf{v}, u) \mapsto \int\limits_K \text{div}_{\Gamma}(\mathbf{v})\, u \ dx \]
The element matrix provider works in a 3 dimensional world with 2 dimensional triangular cells.
As basis functions, the rotated Whitney 1-forms, surface edge elements are used for \(\mathbf{v}\) and the cellwise constant basis functions are used for u
The whitney 1-forms, surface edge elements are associated with edges and defined as
\[ \mathbf{b}_i = s_i (\lambda_i \mathbf{grad}_{\Gamma}(\lambda_{i+1}) - \lambda_{i+1} \mathbf{grad}_{\Gamma}(\lambda_{i})) \]
with \(\lambda_i \) barycentric basis functions and \(s_i \) is a sign of the function based on the relative orientation of the edge in the mesh.
The element matrices are equivalent to the element Matrices for
\[ (\mathbf{v}', u) \mapsto \int\limits_K \text{curl}_{\Gamma}(\mathbf{v}')\, u \ dx \]
with the normal whintey one basis functions for \(\mathbf{v}'\)
Note
This class complies with the type requirements for the template argument ENTITY_MATRIX_PROVIDER of the function lf::assemble::AssembleMatrixLocally().
Only triangular meshes are supported
Definition at line 56 of file rot_whitney_one_div_matrix_provider.h.
Constructor & Destructor Documentation
RotWhitneyOneDivMatrixProvider()
projects::hldo_sphere::assemble::RotWhitneyOneDivMatrixProvider::RotWhitneyOneDivMatrixProvider () inline
Constructor.
Definition at line 61 of file rot_whitney_one_div_matrix_provider.h.
Member Function Documentation
Eval()
Eigen::MatrixXd projects::hldo_sphere::assemble::RotWhitneyOneDivMatrixProvider::Eval (const lf::mesh::Entity & entity) const
Compute the element matrix for some triangle of a mesh.
Parameters
entity The mesh triangle to compute the element matrix for
Returns
The 3 by 1 element matrix of the triangle
Note
Only triangular cells are supported
Definition at line 11 of file rot_whitney_one_div_matrix_provider.cc.
References lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), lf::mesh::Entity::RelativeOrientations(), and lf::mesh::to_sign().
isActive()
bool projects::hldo_sphere::assemble::RotWhitneyOneDivMatrixProvider::isActive (const lf::mesh::Entity & entity) const inline
All entities are regarded as active.
Definition at line 75 of file rot_whitney_one_div_matrix_provider.h.
The documentation for this class was generated from the following files:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/rot_whitney_one_div_matrix_provider.h
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/rot_whitney_one_div_matrix_provider.cc