LehrFEM++: projects::hldo_sphere::experiments::DiracOperatorExperiment Class Reference
projects::hldo_sphere::experiments::DiracOperatorExperiment Class Reference
Creates and solves the discretised Dirac Operator source problems for a given list of levels and values of k.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/experiments/dirac_operators/dirac_operator_experiment.h>
Public Member Functions
DiracOperatorExperiment (std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> u_zero, std::function< Eigen::Matrix< complex, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> u_one, std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> u_two, std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> f_zero, std::function< Eigen::Matrix< complex, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f_one, std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> f_two, double &k, std::string name)
Constructor setting all the functions and the reference k.
void Compute (std::vector< unsigned > refinement_levels, std::vector< double > ks)
Solves the hodge laplacian source problems for the tensor product of passed refinement levels and ks.
Private Attributes
std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> u_zero_
std::function< Eigen::Matrix< complex, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> u_one_
std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> u_two_
std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> f_zero_
std::function< Eigen::Matrix< complex, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f_one_
std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> f_two_
double & k_
std::string name_
Detailed Description
Creates and solves the discretised Dirac Operator source problems for a given list of levels and values of k.
Definition at line 40 of file dirac_operator_experiment.h.
Constructor & Destructor Documentation
DiracOperatorExperiment()
projects::hldo_sphere::experiments::DiracOperatorExperiment::DiracOperatorExperiment (std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> u_zero, std::function< Eigen::Matrix< complex, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> u_one, std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> u_two, std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> f_zero, std::function< Eigen::Matrix< complex, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f_one, std::function< complex(const Eigen::Matrix< double, 3, 1 > &)> f_two, double & k, std::string name) inline
Constructor setting all the functions and the reference k.
Parameters
u_zero analytical soltions corresponding to the load function f_zero
u_one analytical soltions corresponding to the load function f_one
u_two analytical soltions corresponding to the load function f_two
f_zero load function corresponding to the analytical solution u_zero
f_one load function corresponding to the analytical solution u_one
f_two load function corresponding to the analytical solution u_two
k reference used in all the functions such that changes of k affect the functions
name identifier of the example (cretes a folder with this name for the results)
Definition at line 58 of file dirac_operator_experiment.h.
Member Function Documentation
Compute()
void projects::hldo_sphere::experiments::DiracOperatorExperiment::Compute (std::vector< unsigned > refinement_levels, std::vector< double > ks) inline
Solves the hodge laplacian source problems for the tensor product of passed refinement levels and ks.
Parameters
refinement_levels integer list containig all the levels
ks list of all ks to be used
Definition at line 88 of file dirac_operator_experiment.h.
References projects::hldo_sphere::mesh::SphereTriagMeshBuilder::Build(), f_one_, f_two_, f_zero_, projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::k, k_, projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::levels, projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::mesh, name_, projects::hldo_sphere::post_processing::process_results(), projects::hldo_sphere::operators::DiracOperatorSourceProblem::SetLoadFunctions(), projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRadius(), projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel(), projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::solutions, u_one_, u_two_, and u_zero_.
Member Data Documentation
f_one_
std::function<Eigen::Matrix<complex, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::experiments::DiracOperatorExperiment::f_one_ private
Definition at line 225 of file dirac_operator_experiment.h.
Referenced by Compute().
f_two_
std::function<complex(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::experiments::DiracOperatorExperiment::f_two_ private
Definition at line 226 of file dirac_operator_experiment.h.
Referenced by Compute().
f_zero_
std::function<complex(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::experiments::DiracOperatorExperiment::f_zero_ private
Definition at line 222 of file dirac_operator_experiment.h.
Referenced by Compute().
k_
double& projects::hldo_sphere::experiments::DiracOperatorExperiment::k_ private
Definition at line 227 of file dirac_operator_experiment.h.
Referenced by Compute().
name_
std::string projects::hldo_sphere::experiments::DiracOperatorExperiment::name_ private
Definition at line 228 of file dirac_operator_experiment.h.
Referenced by Compute().
u_one_
std::function<Eigen::Matrix<complex, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::experiments::DiracOperatorExperiment::u_one_ private
Definition at line 220 of file dirac_operator_experiment.h.
Referenced by Compute().
u_two_
std::function<complex(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::experiments::DiracOperatorExperiment::u_two_ private
Definition at line 221 of file dirac_operator_experiment.h.
Referenced by Compute().
u_zero_
std::function<complex(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::experiments::DiracOperatorExperiment::u_zero_ private
Definition at line 217 of file dirac_operator_experiment.h.
Referenced by Compute().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/experiments/dirac_operators/dirac_operator_experiment.h