LehrFEM++: projects::hldo_sphere::assemble::MassMatrixProvider Class Reference
projects::hldo_sphere::assemble::MassMatrixProvider Class Reference
Element Matrix Provider for the mass matrix using picewise linear barycentric basis functions.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/mass_matrix_provider.h>
Public Member Functions
MassMatrixProvider ()
Constructor.
Eigen::MatrixXd Eval (const lf::mesh::Entity &entity) const
Compute the element matrix for a given cell of a mesh.
bool isActive (const lf::mesh::Entity &entity) const
All entities are regarded as active.
Detailed Description
Element Matrix Provider for the mass matrix using picewise linear barycentric basis functions.
The element matrix provider works in a 3 dimensional world with 2 dimensional triangular cells.
The bilinear form is locally evaluated for the basis functions. The locally evaluated bilinear form is
\[ (u,v) \mapsto \int\limits_{K} u \, v\, dx \]
Note
This class complies with the type requirements for the template argument ENTITY_MATRIX_PROVIDER of the function lf::assemble::AssembleMatrixLocally().
Only triangular meshes are supported
Definition at line 36 of file mass_matrix_provider.h.
Constructor & Destructor Documentation
MassMatrixProvider()
projects::hldo_sphere::assemble::MassMatrixProvider::MassMatrixProvider () inline
Constructor.
Definition at line 41 of file mass_matrix_provider.h.
Member Function Documentation
Eval()
Eigen::MatrixXd projects::hldo_sphere::assemble::MassMatrixProvider::Eval (const lf::mesh::Entity & entity) const
Compute the element matrix for a given cell of a mesh.
Parameters
entity The mesh cell on which the element matrix will be computed
Returns
The 3 by 3 element matrix of the cell
Note
Only triangular cells are supported
Definition at line 11 of file mass_matrix_provider.cc.
References lf::mesh::Entity::Geometry(), lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), and lf::geometry::Volume().
isActive()
bool projects::hldo_sphere::assemble::MassMatrixProvider::isActive (const lf::mesh::Entity & entity) const inline
All entities are regarded as active.
Definition at line 56 of file mass_matrix_provider.h.
The documentation for this class was generated from the following files:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/mass_matrix_provider.h
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/assemble/mass_matrix_provider.cc