LehrFEM++: projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace Class Reference
projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace Class Reference
Computes the Galerkin LSE for the Hodge Laplacian of the whitney zero form and the source problem.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_zero_hodge_laplacian.h>
Public Member Functions
WhitneyZeroHodgeLaplace ()
Basic Constructor.
void Compute ()
Computes the Galerkin LSE.
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh for later computations.
void SetLoadFunction (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> &f)
Sets the load function for later computations.
Eigen::Matrix< double, Eigen::Dynamic, 1 > GetLoadVector ()
returns the Loadvector
lf::assemble::COOMatrix< double > GetGalerkinMatrix ()
returns the Galerkin Matrix
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_
lf::assemble::COOMatrix< double > coo_matrix_
Eigen::Matrix< double, Eigen::Dynamic, 1 > phi_
Detailed Description
Computes the Galerkin LSE for the Hodge Laplacian of the whitney zero form and the source problem.
\[ -\Delta_0 = -\text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ -\Delta_0 u + k^2 u = f \]
As basis functions, the barycentric basis functions are used
Note
Only triangular meshes are supported
Definition at line 44 of file whitney_zero_hodge_laplacian.h.
Constructor & Destructor Documentation
WhitneyZeroHodgeLaplace()
projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::WhitneyZeroHodgeLaplace () inline
Basic Constructor.
initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f
Definition at line 53 of file whitney_zero_hodge_laplacian.h.
References f_, mesh_p_, and projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel().
Member Function Documentation
Compute()
void projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::Compute () inline
Computes the Galerkin LSE.
The Galerkin matrix will be accessable with GetGalerkinMatrix() The load vector will be accessable with GetLoadVector
Definition at line 80 of file whitney_zero_hodge_laplacian.h.
References lf::assemble::AssembleVectorLocally(), coo_matrix_, f_, lf::base::RefEl::kPoint(), mesh_p_, lf::assemble::DofHandler::NumDofs(), phi_, and lf::assemble::COOMatrix< SCALAR >::setZero().
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
GetGalerkinMatrix()
lf::assemble::COOMatrix< double > projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::GetGalerkinMatrix () inline
returns the Galerkin Matrix
This is the Matrix of the LSE
Note
The Galerkin matrix must be computed with Compute() before calling this funciton
Definition at line 171 of file whitney_zero_hodge_laplacian.h.
References coo_matrix_.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
GetLoadVector()
Eigen::Matrix< double, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::GetLoadVector () inline
returns the Loadvector
This is the righthandside of the LSE
Note
The loadvector must be computed with Compute() before calling this function
Definition at line 160 of file whitney_zero_hodge_laplacian.h.
References phi_.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
SetLoadFunction()
void projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::SetLoadFunction (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> & f) inline
Sets the load function for later computations.
Parameters
f load function
\[ -\Delta_0 = \text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ -\Delta_0 u + k^2 u = f \]
Definition at line 146 of file whitney_zero_hodge_laplacian.h.
References f_.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
SetMesh()
void projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh for later computations.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 121 of file whitney_zero_hodge_laplacian.h.
References lf::base::RefEl::kTria(), mesh_p_, and lf::base::RefEl::RefEl().
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
Member Data Documentation
coo_matrix_
lf::assemble::COOMatrix<double> projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::coo_matrix_ private
Definition at line 176 of file whitney_zero_hodge_laplacian.h.
Referenced by Compute(), and GetGalerkinMatrix().
f_
std::function<double(const Eigen::Matrix<double, 3, 1>&)> projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::f_ private
Definition at line 175 of file whitney_zero_hodge_laplacian.h.
Referenced by Compute(), SetLoadFunction(), and WhitneyZeroHodgeLaplace().
mesh_p_
std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::mesh_p_ private
Definition at line 174 of file whitney_zero_hodge_laplacian.h.
Referenced by Compute(), SetMesh(), and WhitneyZeroHodgeLaplace().
phi_
Eigen::Matrix<double, Eigen::Dynamic, 1> projects::hldo_sphere::discretization::WhitneyZeroHodgeLaplace::phi_ private
Definition at line 177 of file whitney_zero_hodge_laplacian.h.
Referenced by Compute(), and GetLoadVector().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_zero_hodge_laplacian.h