LehrFEM++: projects::hldo_sphere::examples::HodgeLaplacianExample Class Reference
projects::hldo_sphere::examples::HodgeLaplacianExample Class Reference
Creates and solves the discretised Hodge Laplacian source problems for a given list of levels and values of k.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/experiments/hodge_laplacians/hodge_laplacian_example.h>
Public Member Functions
HodgeLaplacianExample (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> u_zero, std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> u_one, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> u_two, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_zero, std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f_one, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_two, double &k, std::string name)
Constructor setting all the functions and the reference k.
void Compute (std::vector< unsigned > refinement_levels, std::vector< double > ks)
Solves the hodge laplacian source problems for the tensor product of passed refinement levels and ks.
Private Attributes
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> u_zero_
std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> u_one_
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> u_two_
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_zero_
std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f_one_
std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_two_
double & k_
std::string name_
Detailed Description
Creates and solves the discretised Hodge Laplacian source problems for a given list of levels and values of k.
Definition at line 38 of file hodge_laplacian_example.h.
Constructor & Destructor Documentation
HodgeLaplacianExample()
projects::hldo_sphere::examples::HodgeLaplacianExample::HodgeLaplacianExample (std::function< double(const Eigen::Matrix< double, 3, 1 > &)> u_zero, std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> u_one, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> u_two, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_zero, std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f_one, std::function< double(const Eigen::Matrix< double, 3, 1 > &)> f_two, double & k, std::string name) inline
Constructor setting all the functions and the reference k.
Parameters
u_zero analytical soltions corresponding to the load function f_zero
u_one analytical soltions corresponding to the load function f_one
u_two analytical soltions corresponding to the load function f_two
f_zero load function corresponding to the analytical solution u_zero
f_one load function corresponding to the analytical solution u_one
f_two load function corresponding to the analytical solution u_two
k reference used in all the functions such that changes of k affect the functions
name identifier of the example (cretes a folder with this name for the results)
Definition at line 56 of file hodge_laplacian_example.h.
Member Function Documentation
Compute()
void projects::hldo_sphere::examples::HodgeLaplacianExample::Compute (std::vector< unsigned > refinement_levels, std::vector< double > ks) inline
Solves the hodge laplacian source problems for the tensor product of passed refinement levels and ks.
Parameters
refinement_levels integer list containig all the levels
ks list of all ks to be used
Definition at line 86 of file hodge_laplacian_example.h.
References projects::hldo_sphere::mesh::SphereTriagMeshBuilder::Build(), f_one_, f_two_, f_zero_, projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::k, k_, projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::levels, projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::mesh, name_, projects::hldo_sphere::post_processing::process_results(), projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::SetLoadFunctions(), projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRadius(), projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel(), projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::solutions, u_one_, u_two_, and u_zero_.
Member Data Documentation
f_one_
std::function<Eigen::Matrix<double, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::examples::HodgeLaplacianExample::f_one_ private
Definition at line 226 of file hodge_laplacian_example.h.
Referenced by Compute().
f_two_
std::function<double(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::examples::HodgeLaplacianExample::f_two_ private
Definition at line 227 of file hodge_laplacian_example.h.
Referenced by Compute().
f_zero_
std::function<double(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::examples::HodgeLaplacianExample::f_zero_ private
Definition at line 223 of file hodge_laplacian_example.h.
Referenced by Compute().
k_
double& projects::hldo_sphere::examples::HodgeLaplacianExample::k_ private
Definition at line 228 of file hodge_laplacian_example.h.
Referenced by Compute().
name_
std::string projects::hldo_sphere::examples::HodgeLaplacianExample::name_ private
Definition at line 229 of file hodge_laplacian_example.h.
Referenced by Compute().
u_one_
std::function<Eigen::Matrix<double, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::examples::HodgeLaplacianExample::u_one_ private
Definition at line 221 of file hodge_laplacian_example.h.
Referenced by Compute().
u_two_
std::function<double(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::examples::HodgeLaplacianExample::u_two_ private
Definition at line 222 of file hodge_laplacian_example.h.
Referenced by Compute().
u_zero_
std::function<double(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::examples::HodgeLaplacianExample::u_zero_ private
Definition at line 218 of file hodge_laplacian_example.h.
Referenced by Compute().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/experiments/hodge_laplacians/hodge_laplacian_example.h