LehrFEM++: projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR > Class Template Reference
projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR > Class Template Reference
Computes the Galerkin LSE for the Hodge Laplacian of the whitney two form.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_two_hodge_laplacian.h>
Public Member Functions
WhitneyTwoHodgeLaplace ()
Constructor initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f.
void Compute ()
Computes the Galerkin LSE.
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh and creates dof_handler.
void SetLoadFunction (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> &f)
Sets the load function.
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > GetLoadVector ()
returns the Loadvector
lf::assemble::COOMatrix< SCALAR > GetGalerkinMatrix ()
returns the Galerkin Matrix
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f_
lf::assemble::COOMatrix< SCALAR > coo_matrix_
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > phi_
Detailed Description
template<typename SCALAR>
class projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >
Computes the Galerkin LSE for the Hodge Laplacian of the whitney two form.
\[ -\Delta_2 = -\text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ -\Delta_2 u = f \]
Basis functions used are the rotated Whitney 1-forms and the cellwise constant functions
Note
Only triangular meshes are supported
Definition at line 50 of file whitney_two_hodge_laplacian.h.
Constructor & Destructor Documentation
WhitneyTwoHodgeLaplace()
template<typename SCALAR > projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::WhitneyTwoHodgeLaplace () inline
Constructor initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f.
Definition at line 58 of file whitney_two_hodge_laplacian.h.
Member Function Documentation
Compute()
template<typename SCALAR > void projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::Compute () inline
Computes the Galerkin LSE.
The Galerkin matrix will be accessable with GetGalerkinMatrix() The load vector will be accessable with GetLoadVector()
Definition at line 84 of file whitney_two_hodge_laplacian.h.
References lf::assemble::AssembleVectorLocally(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), lf::assemble::DofHandler::NumDofs(), lf::assemble::COOMatrix< SCALAR >::setZero(), and lf::assemble::COOMatrix< SCALAR >::triplets().
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
GetGalerkinMatrix()
template<typename SCALAR > lf::assemble::COOMatrix< SCALAR > projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::GetGalerkinMatrix () inline
returns the Galerkin Matrix
This is the Matrix of the LSE containing the negative laplacian
Note
The Galerkin matrix must be computed with Compute() before calling this funciton
Definition at line 230 of file whitney_two_hodge_laplacian.h.
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
GetLoadVector()
template<typename SCALAR > Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::GetLoadVector () inline
returns the Loadvector
This is the righthandside of the LSE
Note
The loadvector must be computed with Compute() before calling this function
Definition at line 219 of file whitney_two_hodge_laplacian.h.
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
SetLoadFunction()
template<typename SCALAR > void projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::SetLoadFunction (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> & f) inline
Sets the load function.
Parameters
f load function
\[ \Delta_2 = \text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ \Delta_2 u = f \]
Definition at line 205 of file whitney_two_hodge_laplacian.h.
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
SetMesh()
template<typename SCALAR > void projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh and creates dof_handler.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 180 of file whitney_two_hodge_laplacian.h.
References lf::base::RefEl::kTria(), and lf::base::RefEl::RefEl().
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
Member Data Documentation
coo_matrix_
template<typename SCALAR > lf::assemble::COOMatrix<SCALAR> projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::coo_matrix_ private
Definition at line 235 of file whitney_two_hodge_laplacian.h.
f_
template<typename SCALAR > std::function<SCALAR(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::f_ private
Definition at line 234 of file whitney_two_hodge_laplacian.h.
mesh_p_
template<typename SCALAR > std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::mesh_p_ private
Definition at line 233 of file whitney_two_hodge_laplacian.h.
phi_
template<typename SCALAR > Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> projects::hldo_sphere::operators::WhitneyTwoHodgeLaplace< SCALAR >::phi_ private
Definition at line 236 of file whitney_two_hodge_laplacian.h.
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_two_hodge_laplacian.h