LehrFEM++: projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR > Class Template Reference
projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR > Class Template Reference
Computes the Galerkin LSE for the Hodge Laplacian of the whitney zero form.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_zero_hodge_laplacian.h>
Public Member Functions
WhitneyZeroHodgeLaplace ()
Basic Constructor.
void Compute ()
Computes the Galerkin LSE.
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh for later computations.
void SetLoadFunction (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> &f)
Sets the load function for later computations.
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > GetLoadVector ()
returns the Loadvector
lf::assemble::COOMatrix< SCALAR > GetGalerkinMatrix ()
returns the Galerkin Matrix
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f_
lf::assemble::COOMatrix< SCALAR > coo_matrix_
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > phi_
Detailed Description
template<typename SCALAR>
class projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >
Computes the Galerkin LSE for the Hodge Laplacian of the whitney zero form.
\[ -\Delta_0 = -\text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ -\Delta_0 u = f \]
As basis functions, the barycentric basis functions are used
Note
Only triangular meshes are supported
Definition at line 45 of file whitney_zero_hodge_laplacian.h.
Constructor & Destructor Documentation
WhitneyZeroHodgeLaplace()
template<typename SCALAR > projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::WhitneyZeroHodgeLaplace () inline
Basic Constructor.
initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f
Definition at line 54 of file whitney_zero_hodge_laplacian.h.
References projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::f_, projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::mesh_p_, and projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel().
Member Function Documentation
Compute()
template<typename SCALAR > void projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::Compute () inline
Computes the Galerkin LSE.
The Galerkin matrix will be accessable with GetGalerkinMatrix() The load vector will be accessable with GetLoadVector
Definition at line 81 of file whitney_zero_hodge_laplacian.h.
References lf::assemble::AssembleVectorLocally(), projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::coo_matrix_, projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::f_, lf::base::RefEl::kPoint(), projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::mesh_p_, lf::assemble::DofHandler::NumDofs(), projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::phi_, and lf::assemble::COOMatrix< SCALAR >::setZero().
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
GetGalerkinMatrix()
template<typename SCALAR > lf::assemble::COOMatrix< SCALAR > projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::GetGalerkinMatrix () inline
returns the Galerkin Matrix
This is the Matrix of the LSE
Note
The Galerkin matrix must be computed with Compute() before calling this funciton
Definition at line 172 of file whitney_zero_hodge_laplacian.h.
References projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::coo_matrix_.
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
GetLoadVector()
template<typename SCALAR > Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::GetLoadVector () inline
returns the Loadvector
This is the righthandside of the LSE
Note
The loadvector must be computed with Compute() before calling this function
Definition at line 161 of file whitney_zero_hodge_laplacian.h.
References projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::phi_.
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
SetLoadFunction()
template<typename SCALAR > void projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::SetLoadFunction (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> & f) inline
Sets the load function for later computations.
Parameters
f load function
\[ -\Delta_0 = \text{div}_{\Gamma} \circ \mathbf{grad}_{\Gamma} \\ -\Delta_0 u + k^2 u = f \]
Definition at line 147 of file whitney_zero_hodge_laplacian.h.
References projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::f_.
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
SetMesh()
template<typename SCALAR > void projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh for later computations.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 122 of file whitney_zero_hodge_laplacian.h.
References lf::base::RefEl::kTria(), projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::mesh_p_, and lf::base::RefEl::RefEl().
Referenced by projects::hldo_sphere::operators::HodgeLaplaciansSourceProblems< SCALAR >::Compute().
Member Data Documentation
coo_matrix_
template<typename SCALAR > lf::assemble::COOMatrix<SCALAR> projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::coo_matrix_ private
Definition at line 177 of file whitney_zero_hodge_laplacian.h.
Referenced by projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::Compute(), and projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::GetGalerkinMatrix().
f_
template<typename SCALAR > std::function<SCALAR(const Eigen::Matrix<double, 3, 1>&)> projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::f_ private
Definition at line 176 of file whitney_zero_hodge_laplacian.h.
Referenced by projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::Compute(), projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::SetLoadFunction(), and projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::WhitneyZeroHodgeLaplace().
mesh_p_
template<typename SCALAR > std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::mesh_p_ private
Definition at line 175 of file whitney_zero_hodge_laplacian.h.
Referenced by projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::Compute(), projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::SetMesh(), and projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::WhitneyZeroHodgeLaplace().
phi_
template<typename SCALAR > Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::phi_ private
Definition at line 178 of file whitney_zero_hodge_laplacian.h.
Referenced by projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::Compute(), and projects::hldo_sphere::operators::WhitneyZeroHodgeLaplace< SCALAR >::GetLoadVector().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_zero_hodge_laplacian.h