LehrFEM++: projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace Class Reference
projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace Class Reference
Computes the Galerkin LSE for the Hodge Laplacian of the whitney one form.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_one_hodge_laplacian.h>
Public Member Functions
WhitneyOneHodgeLaplace ()
Constructor initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f.
void Compute ()
Computes the Galerkin LSE.
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh and creates dof_handler.
void SetLoadFunction (std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> &f)
Sets the load function.
Eigen::Matrix< double, Eigen::Dynamic, 1 > GetLoadVector ()
returns the Loadvector
lf::assemble::COOMatrix< double > GetGalerkinMatrix ()
returns the Galerkin Matrix
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f_
lf::assemble::COOMatrix< double > coo_matrix_
Eigen::Matrix< double, Eigen::Dynamic, 1 > phi_
Detailed Description
Computes the Galerkin LSE for the Hodge Laplacian of the whitney one form.
\[ \Delta_1 u = -\mathbf{curl}_{\Gamma} \circ \text{curl}_{\Gamma} + \mathbf{grad}_{\Gamma} \circ \text{div}_{\Gamma} \\ -\Delta_1 u + k^2 u = f \]
Basis functions are the Whitney 1-forms and the barycentric coordinate functions
Note
Only triangular meshes are supported
Definition at line 47 of file whitney_one_hodge_laplacian.h.
Constructor & Destructor Documentation
WhitneyOneHodgeLaplace()
projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::WhitneyOneHodgeLaplace () inline
Constructor initializes basic mesh (Octaeder with radius 1.0) initializes zerovalued function f.
Definition at line 55 of file whitney_one_hodge_laplacian.h.
References f_, mesh_p_, and projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel().
Member Function Documentation
Compute()
void projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::Compute () inline
Computes the Galerkin LSE.
The Galerkin matrix will be accessable with GetGalerkinMatrix() The load vector will be accessable with GetLoadVector()
Definition at line 84 of file whitney_one_hodge_laplacian.h.
References lf::assemble::AssembleVectorLocally(), coo_matrix_, f_, lf::base::RefEl::kPoint(), lf::base::RefEl::kSegment(), mesh_p_, lf::assemble::DofHandler::NumDofs(), phi_, lf::assemble::COOMatrix< SCALAR >::setZero(), and lf::assemble::COOMatrix< SCALAR >::triplets().
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
GetGalerkinMatrix()
lf::assemble::COOMatrix< double > projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::GetGalerkinMatrix () inline
returns the Galerkin Matrix
This is the Matrix of the LSE
Note
The Galerkin matrix must be computed with Compute() before calling this funciton
Definition at line 243 of file whitney_one_hodge_laplacian.h.
References coo_matrix_.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
GetLoadVector()
Eigen::Matrix< double, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::GetLoadVector () inline
returns the Loadvector
This is the righthandside of the LSE
Note
The loadvector must be computed with Compute() before calling this function
Definition at line 232 of file whitney_one_hodge_laplacian.h.
References phi_.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
SetLoadFunction()
void projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::SetLoadFunction (std::function< Eigen::Matrix< double, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> & f) inline
Sets the load function.
Parameters
f load function
\[ \Delta_1 u = -\mathbf{curl}_{\Gamma} \circ \text{curl}_{\Gamma} + \mathbf{grad}_{\Gamma} \circ \text{div}_{\Gamma} \\ -\Delta_1 u + k^2 u = f \]
Definition at line 218 of file whitney_one_hodge_laplacian.h.
References f_.
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
SetMesh()
void projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh and creates dof_handler.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 192 of file whitney_one_hodge_laplacian.h.
References lf::base::RefEl::kTria(), mesh_p_, and lf::base::RefEl::RefEl().
Referenced by projects::hldo_sphere::discretization::HodgeLaplaciansSourceProblems::Compute().
Member Data Documentation
coo_matrix_
lf::assemble::COOMatrix<double> projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::coo_matrix_ private
Definition at line 250 of file whitney_one_hodge_laplacian.h.
Referenced by Compute(), and GetGalerkinMatrix().
f_
std::function<Eigen::Matrix<double, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::f_ private
Definition at line 249 of file whitney_one_hodge_laplacian.h.
Referenced by Compute(), SetLoadFunction(), and WhitneyOneHodgeLaplace().
mesh_p_
std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::mesh_p_ private
Definition at line 246 of file whitney_one_hodge_laplacian.h.
Referenced by Compute(), SetMesh(), and WhitneyOneHodgeLaplace().
phi_
Eigen::Matrix<double, Eigen::Dynamic, 1> projects::hldo_sphere::discretization::WhitneyOneHodgeLaplace::phi_ private
Definition at line 251 of file whitney_one_hodge_laplacian.h.
Referenced by Compute(), and GetLoadVector().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/whitney_one_hodge_laplacian.h