LehrFEM++: projects::hldo_sphere::discretization::DiracOperator Class Reference
projects::hldo_sphere::discretization::DiracOperator Class Reference
Computes the Galerkin LSE for the Dirac Operator and the load vector.
#include </home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/dirac_operator.h>
Public Member Functions
DiracOperator ()
Constructor creates basic mesh (Octaeder with radius 1.0) creates zerovalued function f.
void Compute ()
Computes the Galerkin LSE.
void SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Sets the mesh and creates dof_handler.
void SetLoadFunctions (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f0, std::function< Eigen::Matrix< SCALAR, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f1, std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f2)
Sets the load functions.
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > GetLoadVector ()
returns the Loadvector
lf::assemble::COOMatrix< SCALAR > GetGalerkinMatrix ()
returns the Galerkin Matrix
Private Attributes
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f0_
std::function< Eigen::Matrix< SCALAR, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f1_
std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f2_
lf::assemble::COOMatrix< SCALAR > coo_matrix_
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > phi_
Detailed Description
Computes the Galerkin LSE for the Dirac Operator and the load vector.
\[ \begin{pmatrix} & \int\limits_{\partial \mathbf{S}} \mathbf{u} \cdot \mathbf{grad}_{\Gamma} v \, dS & \\ \int_{\partial \mathbf{S}} \mathbf{grad}_{\Gamma} u \cdot \mathbf{v} \, dS & & \int\limits_{\partial \mathbf{S}} \mu \ \ \text{curl}_{\Gamma} \mathbf{v} \, dS \\ & \int\limits_{\partial \mathbf{S}} \text{curl}_{\Gamma} \mathbf{u} \ \ \nu \, dS & \end{pmatrix} , \begin{pmatrix} \int\limits_{\partial \mathbf{S}} f v \, dS \\ \int\limits_{\partial \mathbf{S}} \mathbf{f} \cdot \mathbf{v} \, dS \\ \int\limits_{\partial \mathbf{S}} \varphi \nu \, dS \end{pmatrix} \]
Note
Only triangular meshes are supported
Definition at line 57 of file dirac_operator.h.
Constructor & Destructor Documentation
DiracOperator()
projects::hldo_sphere::discretization::DiracOperator::DiracOperator () inline
Constructor creates basic mesh (Octaeder with radius 1.0) creates zerovalued function f.
Definition at line 65 of file dirac_operator.h.
References f0_, f1_, f2_, mesh_p_, and projects::hldo_sphere::mesh::SphereTriagMeshBuilder::setRefinementLevel().
Member Function Documentation
Compute()
void projects::hldo_sphere::discretization::DiracOperator::Compute () inline
Computes the Galerkin LSE.
The Galerkin matrix will be accessable with GetGalerkinMatrix() The load vector will be accessable with GetLoadVector()
Definition at line 98 of file dirac_operator.h.
References lf::assemble::AssembleVectorLocally(), coo_matrix_, f0_, f1_, f2_, lf::base::RefEl::kPoint(), lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), mesh_p_, lf::assemble::DofHandler::NumDofs(), phi_, lf::assemble::COOMatrix< SCALAR >::setZero(), and lf::assemble::COOMatrix< SCALAR >::triplets().
Referenced by projects::hldo_sphere::discretization::DiracOperatorSourceProblem::Compute().
GetGalerkinMatrix()
lf::assemble::COOMatrix< SCALAR > projects::hldo_sphere::discretization::DiracOperator::GetGalerkinMatrix () inline
returns the Galerkin Matrix
This is the Matrix of the LSE
Note
The Galerkin matrix must be computed with Compute() before calling this funciton
Definition at line 272 of file dirac_operator.h.
References coo_matrix_.
Referenced by projects::hldo_sphere::discretization::DiracOperatorSourceProblem::Compute().
GetLoadVector()
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > projects::hldo_sphere::discretization::DiracOperator::GetLoadVector () inline
returns the Loadvector
This is the righthandside of the LSE
Note
The loadvector must be computed with Compute() before calling this function
Definition at line 261 of file dirac_operator.h.
References phi_.
Referenced by projects::hldo_sphere::discretization::DiracOperatorSourceProblem::Compute().
SetLoadFunctions()
void projects::hldo_sphere::discretization::DiracOperator::SetLoadFunctions (std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f0, std::function< Eigen::Matrix< SCALAR, 3, 1 >(const Eigen::Matrix< double, 3, 1 > &)> f1, std::function< SCALAR(const Eigen::Matrix< double, 3, 1 > &)> f2) inline
Sets the load functions.
Parameters
f0 load function in \(L^2 \)
f1 load functions in \(L^2_t \) vector valued
f2 load functions in \(L^2 \)
Definition at line 241 of file dirac_operator.h.
References f0_, f1_, and f2_.
Referenced by projects::hldo_sphere::discretization::DiracOperatorSourceProblem::Compute().
SetMesh()
void projects::hldo_sphere::discretization::DiracOperator::SetMesh (std::shared_ptr< const lf::mesh::Mesh > mesh_p) inline
Sets the mesh and creates dof_handler.
Parameters
mesh_p pointer to the mesh
requries all cells in the mesh are triangles requries mesh global dimension to be 3
Definition at line 219 of file dirac_operator.h.
References lf::base::RefEl::kTria(), mesh_p_, and lf::base::RefEl::RefEl().
Referenced by projects::hldo_sphere::discretization::DiracOperatorSourceProblem::Compute().
Member Data Documentation
coo_matrix_
lf::assemble::COOMatrix<SCALAR> projects::hldo_sphere::discretization::DiracOperator::coo_matrix_ private
Definition at line 281 of file dirac_operator.h.
Referenced by Compute(), and GetGalerkinMatrix().
f0_
std::function<SCALAR(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::DiracOperator::f0_ private
Definition at line 276 of file dirac_operator.h.
Referenced by Compute(), DiracOperator(), and SetLoadFunctions().
f1_
std::function<Eigen::Matrix<SCALAR, 3, 1>(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::DiracOperator::f1_ private
Definition at line 279 of file dirac_operator.h.
Referenced by Compute(), DiracOperator(), and SetLoadFunctions().
f2_
std::function<SCALAR(const Eigen::Matrix<double, 3, 1> &)> projects::hldo_sphere::discretization::DiracOperator::f2_ private
Definition at line 280 of file dirac_operator.h.
Referenced by Compute(), DiracOperator(), and SetLoadFunctions().
mesh_p_
std::shared_ptr<const lf::mesh::Mesh> projects::hldo_sphere::discretization::DiracOperator::mesh_p_ private
Definition at line 275 of file dirac_operator.h.
Referenced by Compute(), DiracOperator(), and SetMesh().
phi_
Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> projects::hldo_sphere::discretization::DiracOperator::phi_ private
Definition at line 282 of file dirac_operator.h.
Referenced by Compute(), and GetLoadVector().
The documentation for this class was generated from the following file:
/home/nico/bildung/SemVI/thesis/lehrfempp/projects/hldo_sphere/operators/dirac_operator.h