LehrFEM++: lf::mesh Namespace Reference
lf::mesh Namespace Reference
Defines a set of interface classes that define a mesh manager and provides mesh-related tools that build on these interfaces.
Namespaces
namespace hybrid2d
An alternative implementation of a hybrid2d mesh manager that uses Pointers to store sub-entity relations.
namespace test_utils
Utilities for testing sanity of mesh data structures and tests involving meshes.
namespace utils
Contains helper functions and classes that all operate on the interface classes defined in lf::mesh.
Classes
class Entity
Interface class representing a topological entity in a cellular complex
class Mesh
Abstract interface for objects representing a single mesh.
class MeshFactory
Interface class for initialization of a mesh object.
Enumerations
enum class Orientation : int { positive = 1 , negative = -1 }
Relative orientation of a sub-entity.
Functions
int to_sign (Orientation o)
char to_char (Orientation o)
std::ostream & operator<< (std::ostream &stream, const lf::mesh::Entity &entity)
Operator overload to print the reference element of Entity to a stream, such as std::cout.
Detailed Description
Defines a set of interface classes that define a mesh manager and provides mesh-related tools that build on these interfaces.
See also
lf::mesh::hybrid2d for a concrete implementation of a mesh manager.
For a discussion of the functionality and design of mesh data structures see Lecture Document Subsection 2.7.2. A mathematical definition of a finite element mesh is given in Lecture Document Subsection 2.5.1.
Enumeration Type Documentation
Orientation
enum class lf::mesh::Orientation : int strong
Relative orientation of a sub-entity.
Relative orientation is a fundamental topological concept describing the relationship of of an entity and its subentities.
For 2D meshes it is mainly relevant for edges: If the intrinsic orientation of an edge defined by the ordering of its vertices agrees with the local orientation of that edge in a cell, its relative orientation is positive, otherwise negative.
Enumerator
positive
negative
Definition at line 19 of file entity.h.
Function Documentation
operator<<()
std::ostream & lf::mesh::operator<< (std::ostream & stream, const lf::mesh::Entity & entity)
Operator overload to print the reference element of Entity to a stream, such as std::cout.
Parameters
stream The stream to which this function should output
entity The entity to write to stream.
Returns
The stream itself.
Definition at line 20 of file entity.cc.
References lf::mesh::Entity::RefEl().
to_char()
char lf::mesh::to_char (Orientation o)
Definition at line 8 of file entity.cc.
References negative, and positive.
to_sign()
int lf::mesh::to_sign (Orientation o)
Definition at line 7 of file entity.cc.
Referenced by projects::hldo_sphere::assemble::RotWhitneyOneDivMatrixProvider::Eval(), projects::hldo_sphere::assemble::WhitneyOneCurlCurlMatrixProvider::Eval(), projects::hldo_sphere::assemble::WhitneyOneGradMatrixProvider::Eval(), projects::hldo_sphere::assemble::WhitneyOneMassMatrixProvider::Eval(), and projects::hldo_sphere::assemble::WhitneyOneVectorProvider< SCALAR >::Eval().