LehrFEM++: projects::hldo_sphere::debugging Namespace Reference
projects::hldo_sphere::debugging Namespace Reference
Contains debugging experiments mainly for the Dirac Opeartor.
Classes
class DiracConvergenceTest
Class to test the convergence of the Dirac operator.
struct SolutionList
stores solutions for a number of refinement levels
class WhitneyOneBasisExpansionCoeffs
Class to find the "best" basisexpansion coefficients with the analytical solution.
class WhitneyOneCurlTest
Tests convergence of the below bilinear form on the Mesh to the analytical solution.
Typedefs
using complex = std::complex< double >
Functions
template<typename... Args>
static std::string concat (Args &&...args)
Concatenate objects defining an operator<<(std::ostream&)
Detailed Description
Contains debugging experiments mainly for the Dirac Opeartor.
This namespace was constructed to chase an error which turned out to be a sign error in the file projects::hldo_sphere::operators::dirac_operator.cc
Details about the experiments implemented in this section and the reasoning behind, can be found in the thesis Hodge-Laplacians and Dirac Operators on the Surface of the 3-Sphere chapter 5.
Typedef Documentation
complex
using projects::hldo_sphere::debugging::complex = typedef std::complex<double>
Definition at line 34 of file dirac_convergence_test.h.
Function Documentation
concat()
template<typename... Args> static std::string projects::hldo_sphere::debugging::concat (Args &&... args) static
Concatenate objects defining an operator<<(std::ostream&)
Parameters
args A variadic pack of objects implementing operator<<(std::ostream&)
Returns
A string with the objects concatenated
Definition at line 26 of file debugging.h.
Referenced by projects::hldo_sphere::debugging::WhitneyOneCurlTest::Compute(), projects::hldo_sphere::debugging::DiracConvergenceTest::Compute(), and projects::hldo_sphere::debugging::WhitneyOneBasisExpansionCoeffs::Experiemnt().