LehrFEM++: projects::hldo_sphere::post_processing Namespace Reference
projects::hldo_sphere::post_processing Namespace Reference
Classes
class MeshFunctionWhitneyOne
class MeshFunctionWhitneyTwo
class MeshFunctionWhitneyZero
struct ProblemSolution
stores solutions for several k and one refinement level
struct ProblemSolutionWrapper
stores solutions and setupinformation for a list of refinement levels and k values
Functions
template<typename MF , typename SQ_F >
std::pair< double, lf::mesh::utils::CodimMeshDataSet< double > > L2norm (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p, const MF &f, const SQ_F &sq_f, const lf::quad::QuadRule &quadrule)
Computes the L2Norm of some MeshFunction (type MF) f.
template<typename MF , typename SQ_F >
std::pair< double, lf::mesh::utils::CodimMeshDataSet< double > > SupNorm (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p, const MF &f, const SQ_F &sq_f, const lf::quad::QuadRule &quadrule)
Computes the supremum norm of the squared values of some MeshFunction (type MF) f.
template<typename... Args>
static std::string concat (Args &&...args)
Concatenate objects defining an operator<<(std::ostream&)
template<typename U_ZERO , typename U_ONE , typename U_TWO , typename SCALAR >
void process_results (std::string name, ProblemSolutionWrapper< SCALAR > &results, U_ZERO &u_zero, U_ONE &u_one, U_TWO &u_two, double &k)
Generate vtk files containing meshdata and a csv table with results.
Function Documentation
concat()
template<typename... Args> static std::string projects::hldo_sphere::post_processing::concat (Args &&... args) static
Concatenate objects defining an operator<<(std::ostream&)
Parameters
args A variadic pack of objects implementing operator<<(std::ostream&)
Returns
A string with the objects concatenated
Definition at line 68 of file results_processing.h.
Referenced by process_results().
L2norm()
template<typename MF , typename SQ_F > std::pair< double, lf::mesh::utils::CodimMeshDataSet< double > > projects::hldo_sphere::post_processing::L2norm (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p, const MF & f, const SQ_F & sq_f, const lf::quad::QuadRule & quadrule)
Computes the L2Norm of some MeshFunction (type MF) f.
Template Parameters
MF type of the mesh function to take to norm form
SQ_F type of the square function sq_f
Parameters
mesh_p pointer to the mesh
f meshfunction to evaluate
sq_f square function for the output of f \(sq\_f(x) \mapsto \|x\|^2\)
quadrule quadrature rule used for each cell in the mesh
Returns
pair with the squared norm of the inputfunction f on the mesh and CodimMeshDataSet containing the cellwise integrals over the squared errors
Iterates over all cells in the mesh and compute the squared integral locally, then add up and square
Definition at line 32 of file norms.h.
References lf::quad::QuadRule::NumPoints(), lf::quad::QuadRule::Points(), and lf::quad::QuadRule::Weights().
Referenced by process_results().
process_results()
template<typename U_ZERO , typename U_ONE , typename U_TWO , typename SCALAR > void projects::hldo_sphere::post_processing::process_results (std::string name, ProblemSolutionWrapper< SCALAR > & results, U_ZERO & u_zero, U_ONE & u_one, U_TWO & u_two, double & k)
Generate vtk files containing meshdata and a csv table with results.
The Table contains for each refinement level, the number of cells, edges and vetices, as well as the global mesh width (the maximum edgelenght of a triangle). Moreover it contains the l2 error and the Supremum error as well as the approximate orders for every value of k and all three forms.
Template Parameters
U_ZERO functor for the analytical solution of the zero form
U_ONE functor for the analytical solution of the one form
U_TWO functor for the analytical solution of the two form
SCALAR base type of the resultvectors
Parameters
name identifying the experiment (used to name the outputs)
results ProblemSolutionWrapper with the results for all levels and ks
u_zero vector with the analytical solutions for u_zero of every k
u_one vector with the analytical solutions for u_one of every k
u_two vector with the analytical solutions for u_two of every k
k reference to the variable used in the functions u_one, u_two, u_zero
Definition at line 97 of file results_processing.h.
References concat(), projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::k, lf::base::RefEl::kTria(), L2norm(), projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::levels, lf::quad::make_QuadRule(), projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::mesh, projects::hldo_sphere::post_processing::ProblemSolutionWrapper< SCALAR >::solutions, SupNorm(), lf::geometry::Volume(), and lf::io::VtkWriter::WriteCellData().
Referenced by projects::hldo_sphere::examples::DiracOperatorExample::Compute(), and projects::hldo_sphere::examples::HodgeLaplacianExample::Compute().
SupNorm()
template<typename MF , typename SQ_F > std::pair< double, lf::mesh::utils::CodimMeshDataSet< double > > projects::hldo_sphere::post_processing::SupNorm (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p, const MF & f, const SQ_F & sq_f, const lf::quad::QuadRule & quadrule)
Computes the supremum norm of the squared values of some MeshFunction (type MF) f.
Template Parameters
MF type of the mesh function to take to norm form
SQ_F type of the square function sq_f
Parameters
mesh_p pointer to the mesh
f meshfunction to evaluate
sq_f square function for the output of f \(sq\_f(x) \mapsto \|x\|^2 \)
quadrule quadrature rule only used to determine the evalueation points
Returns
pair with the supremum norm of the root of the input function sq_f(f(x)) on the mesh and CodimMeshDataSet containing the cellwise supremums
Definition at line 83 of file norms.h.
References lf::quad::QuadRule::NumPoints(), and lf::quad::QuadRule::Points().
Referenced by process_results().