/********************************************************************
    created:    2016-02-11  19:37
    filename:   dummy.cpp
    author:     Raffael Casagrande

    purpose:    Do not edit this file. It is empty and is just included in every 
                 Header only library to make the library non-header only
*********************************************************************/
//                           LEGAL NOTICE                           //
//          This file is property of ABB Switzerland Ltd.           //
//                    This file is confidential.                    //
//                                                                  //
//    The use of this software for any purpose by anyone except     //
//      ABB Switzerland is subject to prior written permission      //
//                      from ABB Switzerland.                       //

