name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  windows-debug:
    # Name the Job
    name: Windows Debug x64
    # Set the type of machine to run on
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Restore cache:
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: C:\.hunter
          key:  ${{ runner.os }}-build3
          #restore-keys: |
          #  ${{ runner.os }}-build2
      
      # Note that windows has a recent version cmake installed
      - name: Build dependencies
        run: |
          mkdir build
          cd build
          mkdir C:\.hunter
          cd C:\.hunter
          dir
          echo "hello cache" > C:\.hunter\hello2.txt
        #  dir
        #  type C:\hunter\hello.txt
        #  echo "hello cache" > C:\.hunter\hello.txt
           
          
        # cmake -A x64 -D HUNTER_CONFIGURATION_TYPES=Debug ..
    
        
